// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message defines the data needed by consensus to communicate between nodes over network in all subslots
type Message struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlockHeaderHash    []byte                 `protobuf:"bytes,1,opt,name=BlockHeaderHash,proto3" json:"BlockHeaderHash,omitempty"`
	SignatureShare     []byte                 `protobuf:"bytes,2,opt,name=SignatureShare,proto3" json:"SignatureShare,omitempty"`
	Header             []byte                 `protobuf:"bytes,3,opt,name=Header,proto3" json:"Header,omitempty"`
	PubKey             []byte                 `protobuf:"bytes,5,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Signature          []byte                 `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty"`
	MsgType            int64                  `protobuf:"varint,7,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	SlotIndex          int64                  `protobuf:"varint,8,opt,name=SlotIndex,proto3" json:"SlotIndex,omitempty"`
	ChainID            []byte                 `protobuf:"bytes,9,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	PubKeysBitmap      []byte                 `protobuf:"bytes,10,opt,name=PubKeysBitmap,proto3" json:"PubKeysBitmap,omitempty"`
	AggregateSignature []byte                 `protobuf:"bytes,11,opt,name=AggregateSignature,proto3" json:"AggregateSignature,omitempty"`
	LeaderSignature    []byte                 `protobuf:"bytes,12,opt,name=LeaderSignature,proto3" json:"LeaderSignature,omitempty"`
	OriginatorPid      []byte                 `protobuf:"bytes,13,opt,name=OriginatorPid,proto3" json:"OriginatorPid,omitempty"`
	Nonce              uint64                 `protobuf:"varint,20,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBlockHeaderHash() []byte {
	if x != nil {
		return x.BlockHeaderHash
	}
	return nil
}

func (x *Message) GetSignatureShare() []byte {
	if x != nil {
		return x.SignatureShare
	}
	return nil
}

func (x *Message) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Message) GetSlotIndex() int64 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *Message) GetChainID() []byte {
	if x != nil {
		return x.ChainID
	}
	return nil
}

func (x *Message) GetPubKeysBitmap() []byte {
	if x != nil {
		return x.PubKeysBitmap
	}
	return nil
}

func (x *Message) GetAggregateSignature() []byte {
	if x != nil {
		return x.AggregateSignature
	}
	return nil
}

func (x *Message) GetLeaderSignature() []byte {
	if x != nil {
		return x.LeaderSignature
	}
	return nil
}

func (x *Message) GetOriginatorPid() []byte {
	if x != nil {
		return x.OriginatorPid
	}
	return nil
}

func (x *Message) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proto\"\xb7\x03\n" +
	"\aMessage\x12(\n" +
	"\x0fBlockHeaderHash\x18\x01 \x01(\fR\x0fBlockHeaderHash\x12&\n" +
	"\x0eSignatureShare\x18\x02 \x01(\fR\x0eSignatureShare\x12\x16\n" +
	"\x06Header\x18\x03 \x01(\fR\x06Header\x12\x16\n" +
	"\x06PubKey\x18\x05 \x01(\fR\x06PubKey\x12\x1c\n" +
	"\tSignature\x18\x06 \x01(\fR\tSignature\x12\x18\n" +
	"\aMsgType\x18\a \x01(\x03R\aMsgType\x12\x1c\n" +
	"\tSlotIndex\x18\b \x01(\x03R\tSlotIndex\x12\x18\n" +
	"\aChainID\x18\t \x01(\fR\aChainID\x12$\n" +
	"\rPubKeysBitmap\x18\n" +
	" \x01(\fR\rPubKeysBitmap\x12.\n" +
	"\x12AggregateSignature\x18\v \x01(\fR\x12AggregateSignature\x12(\n" +
	"\x0fLeaderSignature\x18\f \x01(\fR\x0fLeaderSignature\x12$\n" +
	"\rOriginatorPid\x18\r \x01(\fR\rOriginatorPid\x12\x14\n" +
	"\x05Nonce\x18\x14 \x01(\x04R\x05NonceB\x0eZ\f./;consensusb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*Message)(nil), // 0: proto.Message
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
