FROM golang:1.22-bookworm  as builder

COPY . /go/src/github.com/klever-io/klever-go

WORKDIR /go/src/github.com/klever-io/klever-go

ARG arg_version
ENV VERSION=$arg_version

RUN make build-validator

FROM debian:bookworm

RUN apt-get update \
    && apt-get install -y ca-certificates curl --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates 

RUN addgroup klever \
    && adduser --disabled-password --gecos "" klever --uid 1000 --ingroup klever \
    && chown klever:root /etc/ssl/private

COPY --from=builder --chown=klever:klever /go/src/github.com/klever-io/klever-go/bin/validator /usr/local/bin/
RUN chmod +x /usr/local/bin/validator

USER klever

COPY --chown=klever:klever config/seednode/config.yaml /opt/klever-blockchain/config/seednode/config.yaml
RUN mkdir -p /opt/klever-blockchain/stats && \
    mkdir -p /opt/klever-blockchain/db && \
    mkdir -p /opt/klever-blockchain/logs && \
    chown -R klever:klever /opt/klever-blockchain
WORKDIR /opt/klever-blockchain

HEALTHCHECK --interval=10s CMD exit 0

ENTRYPOINT [ "/usr/local/bin/validator", "--use-log-view" ]
