// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kappAccountData.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KAppAccountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,json=address,omitempty,proto3" json:"Address,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=Name,json=name,omitempty,proto3" json:"Name,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,3,opt,name=RootHash,json=rootHash,omitempty,proto3" json:"RootHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KAppAccountData) Reset() {
	*x = KAppAccountData{}
	mi := &file_kappAccountData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KAppAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KAppAccountData) ProtoMessage() {}

func (x *KAppAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_kappAccountData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KAppAccountData.ProtoReflect.Descriptor instead.
func (*KAppAccountData) Descriptor() ([]byte, []int) {
	return file_kappAccountData_proto_rawDescGZIP(), []int{0}
}

func (x *KAppAccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *KAppAccountData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *KAppAccountData) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

var File_kappAccountData_proto protoreflect.FileDescriptor

const file_kappAccountData_proto_rawDesc = "" +
	"\n" +
	"\x15kappAccountData.proto\x12\x05proto\"y\n" +
	"\x0fKAppAccountData\x12\"\n" +
	"\aAddress\x18\x01 \x01(\fR\x11address,omitempty\x12\x1c\n" +
	"\x04Name\x18\x02 \x01(\fR\x0ename,omitempty\x12$\n" +
	"\bRootHash\x18\x03 \x01(\fR\x12rootHash,omitemptyB\n" +
	"Z\b./;stateb\x06proto3"

var (
	file_kappAccountData_proto_rawDescOnce sync.Once
	file_kappAccountData_proto_rawDescData []byte
)

func file_kappAccountData_proto_rawDescGZIP() []byte {
	file_kappAccountData_proto_rawDescOnce.Do(func() {
		file_kappAccountData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kappAccountData_proto_rawDesc), len(file_kappAccountData_proto_rawDesc)))
	})
	return file_kappAccountData_proto_rawDescData
}

var file_kappAccountData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kappAccountData_proto_goTypes = []any{
	(*KAppAccountData)(nil), // 0: proto.KAppAccountData
}
var file_kappAccountData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kappAccountData_proto_init() }
func file_kappAccountData_proto_init() {
	if File_kappAccountData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kappAccountData_proto_rawDesc), len(file_kappAccountData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kappAccountData_proto_goTypes,
		DependencyIndexes: file_kappAccountData_proto_depIdxs,
		MessageInfos:      file_kappAccountData_proto_msgTypes,
	}.Build()
	File_kappAccountData_proto = out.File
	file_kappAccountData_proto_goTypes = nil
	file_kappAccountData_proto_depIdxs = nil
}
