// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.27.0
// source: kappAccountData.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KAppAccountData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte `protobuf:"bytes,1,opt,name=Address,json=address,omitempty,proto3" json:"Address,omitempty"`
	Name     []byte `protobuf:"bytes,2,opt,name=Name,json=name,omitempty,proto3" json:"Name,omitempty"`
	RootHash []byte `protobuf:"bytes,3,opt,name=RootHash,json=rootHash,omitempty,proto3" json:"RootHash,omitempty"`
}

func (x *KAppAccountData) Reset() {
	*x = KAppAccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappAccountData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KAppAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KAppAccountData) ProtoMessage() {}

func (x *KAppAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_kappAccountData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KAppAccountData.ProtoReflect.Descriptor instead.
func (*KAppAccountData) Descriptor() ([]byte, []int) {
	return file_kappAccountData_proto_rawDescGZIP(), []int{0}
}

func (x *KAppAccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *KAppAccountData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *KAppAccountData) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

var File_kappAccountData_proto protoreflect.FileDescriptor

var file_kappAccountData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6b, 0x61, 0x70, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79,
	0x0a, 0x0f, 0x4b, 0x41, 0x70, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2c, 0x6f, 0x6d, 0x69, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x2c,
	0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kappAccountData_proto_rawDescOnce sync.Once
	file_kappAccountData_proto_rawDescData = file_kappAccountData_proto_rawDesc
)

func file_kappAccountData_proto_rawDescGZIP() []byte {
	file_kappAccountData_proto_rawDescOnce.Do(func() {
		file_kappAccountData_proto_rawDescData = protoimpl.X.CompressGZIP(file_kappAccountData_proto_rawDescData)
	})
	return file_kappAccountData_proto_rawDescData
}

var file_kappAccountData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kappAccountData_proto_goTypes = []interface{}{
	(*KAppAccountData)(nil), // 0: proto.KAppAccountData
}
var file_kappAccountData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kappAccountData_proto_init() }
func file_kappAccountData_proto_init() {
	if File_kappAccountData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kappAccountData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KAppAccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kappAccountData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kappAccountData_proto_goTypes,
		DependencyIndexes: file_kappAccountData_proto_depIdxs,
		MessageInfos:      file_kappAccountData_proto_msgTypes,
	}.Build()
	File_kappAccountData_proto = out.File
	file_kappAccountData_proto_rawDesc = nil
	file_kappAccountData_proto_goTypes = nil
	file_kappAccountData_proto_depIdxs = nil
}
