// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: peerAccountData.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type List int32

const (
	List_inactive List = 0
	List_observer List = 1
	List_waiting  List = 2
	List_eligible List = 3
	List_elected  List = 4
	List_leaving  List = 5
	List_jailed   List = 6
)

// Enum value maps for List.
var (
	List_name = map[int32]string{
		0: "inactive",
		1: "observer",
		2: "waiting",
		3: "eligible",
		4: "elected",
		5: "leaving",
		6: "jailed",
	}
	List_value = map[string]int32{
		"inactive": 0,
		"observer": 1,
		"waiting":  2,
		"eligible": 3,
		"elected":  4,
		"leaving":  5,
		"jailed":   6,
	}
)

func (x List) Enum() *List {
	p := new(List)
	*p = x
	return p
}

func (x List) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (List) Descriptor() protoreflect.EnumDescriptor {
	return file_peerAccountData_proto_enumTypes[0].Descriptor()
}

func (List) Type() protoreflect.EnumType {
	return &file_peerAccountData_proto_enumTypes[0]
}

func (x List) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use List.Descriptor instead.
func (List) EnumDescriptor() ([]byte, []int) {
	return file_peerAccountData_proto_rawDescGZIP(), []int{0}
}

// ValidatorApiResponse represents the data which is fetched from each validator for returning it in API call
type ValidatorApiResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	TempRating                         float32                `protobuf:"fixed32,1,opt,name=TempRating,json=tempRating,proto3" json:"TempRating,omitempty"`
	NumLeaderSuccess                   uint32                 `protobuf:"varint,2,opt,name=NumLeaderSuccess,json=numLeaderSuccess,proto3" json:"NumLeaderSuccess,omitempty"`
	NumLeaderFailure                   uint32                 `protobuf:"varint,3,opt,name=NumLeaderFailure,json=numLeaderFailure,proto3" json:"NumLeaderFailure,omitempty"`
	NumValidatorSuccess                uint32                 `protobuf:"varint,4,opt,name=NumValidatorSuccess,json=numValidatorSuccess,proto3" json:"NumValidatorSuccess,omitempty"`
	NumValidatorFailure                uint32                 `protobuf:"varint,5,opt,name=NumValidatorFailure,json=numValidatorFailure,proto3" json:"NumValidatorFailure,omitempty"`
	NumValidatorIgnoredSignatures      uint32                 `protobuf:"varint,6,opt,name=NumValidatorIgnoredSignatures,json=numValidatorIgnoredSignatures,proto3" json:"NumValidatorIgnoredSignatures,omitempty"`
	Rating                             float32                `protobuf:"fixed32,7,opt,name=Rating,json=rating,proto3" json:"Rating,omitempty"`
	RatingModifier                     float32                `protobuf:"fixed32,8,opt,name=RatingModifier,json=ratingModifier,proto3" json:"RatingModifier,omitempty"`
	TotalNumLeaderSuccess              uint32                 `protobuf:"varint,9,opt,name=TotalNumLeaderSuccess,json=totalNumLeaderSuccess,proto3" json:"TotalNumLeaderSuccess,omitempty"`
	TotalNumLeaderFailure              uint32                 `protobuf:"varint,10,opt,name=TotalNumLeaderFailure,json=totalNumLeaderFailure,proto3" json:"TotalNumLeaderFailure,omitempty"`
	TotalNumValidatorSuccess           uint32                 `protobuf:"varint,11,opt,name=TotalNumValidatorSuccess,json=totalNumValidatorSuccess,proto3" json:"TotalNumValidatorSuccess,omitempty"`
	TotalNumValidatorFailure           uint32                 `protobuf:"varint,12,opt,name=TotalNumValidatorFailure,json=totalNumValidatorFailure,proto3" json:"TotalNumValidatorFailure,omitempty"`
	TotalNumValidatorIgnoredSignatures uint32                 `protobuf:"varint,13,opt,name=TotalNumValidatorIgnoredSignatures,json=totalNumValidatorIgnoredSignatures,proto3" json:"TotalNumValidatorIgnoredSignatures,omitempty"`
	ValidatorStatus                    string                 `protobuf:"bytes,14,opt,name=ValidatorStatus,json=validatorStatus,omitempty,proto3" json:"ValidatorStatus,omitempty"`
	Revoked                            bool                   `protobuf:"varint,15,opt,name=Revoked,json=revoked,omitempty,proto3" json:"Revoked,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ValidatorApiResponse) Reset() {
	*x = ValidatorApiResponse{}
	mi := &file_peerAccountData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorApiResponse) ProtoMessage() {}

func (x *ValidatorApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peerAccountData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorApiResponse.ProtoReflect.Descriptor instead.
func (*ValidatorApiResponse) Descriptor() ([]byte, []int) {
	return file_peerAccountData_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorApiResponse) GetTempRating() float32 {
	if x != nil {
		return x.TempRating
	}
	return 0
}

func (x *ValidatorApiResponse) GetNumLeaderSuccess() uint32 {
	if x != nil {
		return x.NumLeaderSuccess
	}
	return 0
}

func (x *ValidatorApiResponse) GetNumLeaderFailure() uint32 {
	if x != nil {
		return x.NumLeaderFailure
	}
	return 0
}

func (x *ValidatorApiResponse) GetNumValidatorSuccess() uint32 {
	if x != nil {
		return x.NumValidatorSuccess
	}
	return 0
}

func (x *ValidatorApiResponse) GetNumValidatorFailure() uint32 {
	if x != nil {
		return x.NumValidatorFailure
	}
	return 0
}

func (x *ValidatorApiResponse) GetNumValidatorIgnoredSignatures() uint32 {
	if x != nil {
		return x.NumValidatorIgnoredSignatures
	}
	return 0
}

func (x *ValidatorApiResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ValidatorApiResponse) GetRatingModifier() float32 {
	if x != nil {
		return x.RatingModifier
	}
	return 0
}

func (x *ValidatorApiResponse) GetTotalNumLeaderSuccess() uint32 {
	if x != nil {
		return x.TotalNumLeaderSuccess
	}
	return 0
}

func (x *ValidatorApiResponse) GetTotalNumLeaderFailure() uint32 {
	if x != nil {
		return x.TotalNumLeaderFailure
	}
	return 0
}

func (x *ValidatorApiResponse) GetTotalNumValidatorSuccess() uint32 {
	if x != nil {
		return x.TotalNumValidatorSuccess
	}
	return 0
}

func (x *ValidatorApiResponse) GetTotalNumValidatorFailure() uint32 {
	if x != nil {
		return x.TotalNumValidatorFailure
	}
	return 0
}

func (x *ValidatorApiResponse) GetTotalNumValidatorIgnoredSignatures() uint32 {
	if x != nil {
		return x.TotalNumValidatorIgnoredSignatures
	}
	return 0
}

func (x *ValidatorApiResponse) GetValidatorStatus() string {
	if x != nil {
		return x.ValidatorStatus
	}
	return ""
}

func (x *ValidatorApiResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

// SignRate is used to keep the number of success and failed signings
type SignRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumSuccess    uint32                 `protobuf:"varint,1,opt,name=NumSuccess,proto3" json:"NumSuccess,omitempty"`
	NumFailure    uint32                 `protobuf:"varint,2,opt,name=NumFailure,proto3" json:"NumFailure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRate) Reset() {
	*x = SignRate{}
	mi := &file_peerAccountData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRate) ProtoMessage() {}

func (x *SignRate) ProtoReflect() protoreflect.Message {
	mi := &file_peerAccountData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRate.ProtoReflect.Descriptor instead.
func (*SignRate) Descriptor() ([]byte, []int) {
	return file_peerAccountData_proto_rawDescGZIP(), []int{1}
}

func (x *SignRate) GetNumSuccess() uint32 {
	if x != nil {
		return x.NumSuccess
	}
	return 0
}

func (x *SignRate) GetNumFailure() uint32 {
	if x != nil {
		return x.NumFailure
	}
	return 0
}

// PeerAccountData represents the data that defines the PeerAccount
type PeerAccountData struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	BLSPublicKey                        []byte                 `protobuf:"bytes,1,opt,name=BLSPublicKey,json=blsPublicKey,proto3" json:"BLSPublicKey,omitempty"`
	RootHash                            []byte                 `protobuf:"bytes,2,opt,name=RootHash,json=rootHash,omitempty,proto3" json:"RootHash,omitempty"`
	OwnerAddress                        []byte                 `protobuf:"bytes,3,opt,name=OwnerAddress,json=ownerAddress,omitempty,proto3" json:"OwnerAddress,omitempty"`
	Revoked                             bool                   `protobuf:"varint,4,opt,name=Revoked,json=revoked,omitempty,proto3" json:"Revoked,omitempty"`
	ShardId                             uint32                 `protobuf:"varint,5,opt,name=ShardId,json=shardId,proto3" json:"ShardId,omitempty"`
	List                                List                   `protobuf:"varint,6,opt,name=List,json=list,proto3,enum=proto.List" json:"List,omitempty"`
	Index                               uint32                 `protobuf:"varint,7,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	AccumulatedFees                     int64                  `protobuf:"varint,8,opt,name=AccumulatedFees,json=accumulatedFees,proto3" json:"AccumulatedFees,omitempty"`
	ValidatorSuccessRate                *SignRate              `protobuf:"bytes,9,opt,name=ValidatorSuccessRate,json=validatorSuccessRate,proto3" json:"ValidatorSuccessRate,omitempty"`
	LeaderSuccessRate                   *SignRate              `protobuf:"bytes,10,opt,name=LeaderSuccessRate,json=leaderSuccessRate,proto3" json:"LeaderSuccessRate,omitempty"`
	ValidatorIgnoredSignaturesRate      uint32                 `protobuf:"varint,11,opt,name=ValidatorIgnoredSignaturesRate,json=validatorIgnoredSignaturesRate,proto3" json:"ValidatorIgnoredSignaturesRate,omitempty"`
	Rating                              uint32                 `protobuf:"varint,12,opt,name=Rating,json=rating,proto3" json:"Rating,omitempty"`
	TempRating                          uint32                 `protobuf:"varint,13,opt,name=TempRating,json=tempRating,proto3" json:"TempRating,omitempty"`
	NumSelectedInSuccessBlocks          uint32                 `protobuf:"varint,14,opt,name=NumSelectedInSuccessBlocks,json=numSelectedInSuccessBlocks,proto3" json:"NumSelectedInSuccessBlocks,omitempty"`
	ConsecutiveProposerMisses           uint32                 `protobuf:"varint,15,opt,name=ConsecutiveProposerMisses,json=consecutiveProposerMisses,proto3" json:"ConsecutiveProposerMisses,omitempty"`
	TotalValidatorSuccessRate           *SignRate              `protobuf:"bytes,16,opt,name=TotalValidatorSuccessRate,json=totalValidatorSuccessRate,proto3" json:"TotalValidatorSuccessRate,omitempty"`
	TotalLeaderSuccessRate              *SignRate              `protobuf:"bytes,17,opt,name=TotalLeaderSuccessRate,json=totalLeaderSuccessRate,proto3" json:"TotalLeaderSuccessRate,omitempty"`
	TotalValidatorIgnoredSignaturesRate uint32                 `protobuf:"varint,18,opt,name=TotalValidatorIgnoredSignaturesRate,json=totalValidatorIgnoredSignaturesRate,proto3" json:"TotalValidatorIgnoredSignaturesRate,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *PeerAccountData) Reset() {
	*x = PeerAccountData{}
	mi := &file_peerAccountData_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAccountData) ProtoMessage() {}

func (x *PeerAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_peerAccountData_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAccountData.ProtoReflect.Descriptor instead.
func (*PeerAccountData) Descriptor() ([]byte, []int) {
	return file_peerAccountData_proto_rawDescGZIP(), []int{2}
}

func (x *PeerAccountData) GetBLSPublicKey() []byte {
	if x != nil {
		return x.BLSPublicKey
	}
	return nil
}

func (x *PeerAccountData) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *PeerAccountData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *PeerAccountData) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *PeerAccountData) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *PeerAccountData) GetList() List {
	if x != nil {
		return x.List
	}
	return List_inactive
}

func (x *PeerAccountData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PeerAccountData) GetAccumulatedFees() int64 {
	if x != nil {
		return x.AccumulatedFees
	}
	return 0
}

func (x *PeerAccountData) GetValidatorSuccessRate() *SignRate {
	if x != nil {
		return x.ValidatorSuccessRate
	}
	return nil
}

func (x *PeerAccountData) GetLeaderSuccessRate() *SignRate {
	if x != nil {
		return x.LeaderSuccessRate
	}
	return nil
}

func (x *PeerAccountData) GetValidatorIgnoredSignaturesRate() uint32 {
	if x != nil {
		return x.ValidatorIgnoredSignaturesRate
	}
	return 0
}

func (x *PeerAccountData) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *PeerAccountData) GetTempRating() uint32 {
	if x != nil {
		return x.TempRating
	}
	return 0
}

func (x *PeerAccountData) GetNumSelectedInSuccessBlocks() uint32 {
	if x != nil {
		return x.NumSelectedInSuccessBlocks
	}
	return 0
}

func (x *PeerAccountData) GetConsecutiveProposerMisses() uint32 {
	if x != nil {
		return x.ConsecutiveProposerMisses
	}
	return 0
}

func (x *PeerAccountData) GetTotalValidatorSuccessRate() *SignRate {
	if x != nil {
		return x.TotalValidatorSuccessRate
	}
	return nil
}

func (x *PeerAccountData) GetTotalLeaderSuccessRate() *SignRate {
	if x != nil {
		return x.TotalLeaderSuccessRate
	}
	return nil
}

func (x *PeerAccountData) GetTotalValidatorIgnoredSignaturesRate() uint32 {
	if x != nil {
		return x.TotalValidatorIgnoredSignaturesRate
	}
	return 0
}

var File_peerAccountData_proto protoreflect.FileDescriptor

const file_peerAccountData_proto_rawDesc = "" +
	"\n" +
	"\x15peerAccountData.proto\x12\x05proto\"\x84\x06\n" +
	"\x14ValidatorApiResponse\x12\x1e\n" +
	"\n" +
	"TempRating\x18\x01 \x01(\x02R\n" +
	"tempRating\x12*\n" +
	"\x10NumLeaderSuccess\x18\x02 \x01(\rR\x10numLeaderSuccess\x12*\n" +
	"\x10NumLeaderFailure\x18\x03 \x01(\rR\x10numLeaderFailure\x120\n" +
	"\x13NumValidatorSuccess\x18\x04 \x01(\rR\x13numValidatorSuccess\x120\n" +
	"\x13NumValidatorFailure\x18\x05 \x01(\rR\x13numValidatorFailure\x12D\n" +
	"\x1dNumValidatorIgnoredSignatures\x18\x06 \x01(\rR\x1dnumValidatorIgnoredSignatures\x12\x16\n" +
	"\x06Rating\x18\a \x01(\x02R\x06rating\x12&\n" +
	"\x0eRatingModifier\x18\b \x01(\x02R\x0eratingModifier\x124\n" +
	"\x15TotalNumLeaderSuccess\x18\t \x01(\rR\x15totalNumLeaderSuccess\x124\n" +
	"\x15TotalNumLeaderFailure\x18\n" +
	" \x01(\rR\x15totalNumLeaderFailure\x12:\n" +
	"\x18TotalNumValidatorSuccess\x18\v \x01(\rR\x18totalNumValidatorSuccess\x12:\n" +
	"\x18TotalNumValidatorFailure\x18\f \x01(\rR\x18totalNumValidatorFailure\x12N\n" +
	"\"TotalNumValidatorIgnoredSignatures\x18\r \x01(\rR\"totalNumValidatorIgnoredSignatures\x122\n" +
	"\x0fValidatorStatus\x18\x0e \x01(\tR\x19validatorStatus,omitempty\x12\"\n" +
	"\aRevoked\x18\x0f \x01(\bR\x11revoked,omitempty\"J\n" +
	"\bSignRate\x12\x1e\n" +
	"\n" +
	"NumSuccess\x18\x01 \x01(\rR\n" +
	"NumSuccess\x12\x1e\n" +
	"\n" +
	"NumFailure\x18\x02 \x01(\rR\n" +
	"NumFailure\"\x94\a\n" +
	"\x0fPeerAccountData\x12\"\n" +
	"\fBLSPublicKey\x18\x01 \x01(\fR\fblsPublicKey\x12$\n" +
	"\bRootHash\x18\x02 \x01(\fR\x12rootHash,omitempty\x12,\n" +
	"\fOwnerAddress\x18\x03 \x01(\fR\x16ownerAddress,omitempty\x12\"\n" +
	"\aRevoked\x18\x04 \x01(\bR\x11revoked,omitempty\x12\x18\n" +
	"\aShardId\x18\x05 \x01(\rR\ashardId\x12\x1f\n" +
	"\x04List\x18\x06 \x01(\x0e2\v.proto.ListR\x04list\x12\x14\n" +
	"\x05Index\x18\a \x01(\rR\x05index\x12(\n" +
	"\x0fAccumulatedFees\x18\b \x01(\x03R\x0faccumulatedFees\x12C\n" +
	"\x14ValidatorSuccessRate\x18\t \x01(\v2\x0f.proto.SignRateR\x14validatorSuccessRate\x12=\n" +
	"\x11LeaderSuccessRate\x18\n" +
	" \x01(\v2\x0f.proto.SignRateR\x11leaderSuccessRate\x12F\n" +
	"\x1eValidatorIgnoredSignaturesRate\x18\v \x01(\rR\x1evalidatorIgnoredSignaturesRate\x12\x16\n" +
	"\x06Rating\x18\f \x01(\rR\x06rating\x12\x1e\n" +
	"\n" +
	"TempRating\x18\r \x01(\rR\n" +
	"tempRating\x12>\n" +
	"\x1aNumSelectedInSuccessBlocks\x18\x0e \x01(\rR\x1anumSelectedInSuccessBlocks\x12<\n" +
	"\x19ConsecutiveProposerMisses\x18\x0f \x01(\rR\x19consecutiveProposerMisses\x12M\n" +
	"\x19TotalValidatorSuccessRate\x18\x10 \x01(\v2\x0f.proto.SignRateR\x19totalValidatorSuccessRate\x12G\n" +
	"\x16TotalLeaderSuccessRate\x18\x11 \x01(\v2\x0f.proto.SignRateR\x16totalLeaderSuccessRate\x12P\n" +
	"#TotalValidatorIgnoredSignaturesRate\x18\x12 \x01(\rR#totalValidatorIgnoredSignaturesRate*c\n" +
	"\x04List\x12\f\n" +
	"\binactive\x10\x00\x12\f\n" +
	"\bobserver\x10\x01\x12\v\n" +
	"\awaiting\x10\x02\x12\f\n" +
	"\beligible\x10\x03\x12\v\n" +
	"\aelected\x10\x04\x12\v\n" +
	"\aleaving\x10\x05\x12\n" +
	"\n" +
	"\x06jailed\x10\x06B\n" +
	"Z\b./;stateb\x06proto3"

var (
	file_peerAccountData_proto_rawDescOnce sync.Once
	file_peerAccountData_proto_rawDescData []byte
)

func file_peerAccountData_proto_rawDescGZIP() []byte {
	file_peerAccountData_proto_rawDescOnce.Do(func() {
		file_peerAccountData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peerAccountData_proto_rawDesc), len(file_peerAccountData_proto_rawDesc)))
	})
	return file_peerAccountData_proto_rawDescData
}

var file_peerAccountData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peerAccountData_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_peerAccountData_proto_goTypes = []any{
	(List)(0),                    // 0: proto.List
	(*ValidatorApiResponse)(nil), // 1: proto.ValidatorApiResponse
	(*SignRate)(nil),             // 2: proto.SignRate
	(*PeerAccountData)(nil),      // 3: proto.PeerAccountData
}
var file_peerAccountData_proto_depIdxs = []int32{
	0, // 0: proto.PeerAccountData.List:type_name -> proto.List
	2, // 1: proto.PeerAccountData.ValidatorSuccessRate:type_name -> proto.SignRate
	2, // 2: proto.PeerAccountData.LeaderSuccessRate:type_name -> proto.SignRate
	2, // 3: proto.PeerAccountData.TotalValidatorSuccessRate:type_name -> proto.SignRate
	2, // 4: proto.PeerAccountData.TotalLeaderSuccessRate:type_name -> proto.SignRate
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_peerAccountData_proto_init() }
func file_peerAccountData_proto_init() {
	if File_peerAccountData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peerAccountData_proto_rawDesc), len(file_peerAccountData_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peerAccountData_proto_goTypes,
		DependencyIndexes: file_peerAccountData_proto_depIdxs,
		EnumInfos:         file_peerAccountData_proto_enumTypes,
		MessageInfos:      file_peerAccountData_proto_msgTypes,
	}.Build()
	File_peerAccountData_proto = out.File
	file_peerAccountData_proto_goTypes = nil
	file_peerAccountData_proto_depIdxs = nil
}
