// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: userAccountData.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission_PermissionType int32

const (
	Permission_Owner Permission_PermissionType = 0
	Permission_User  Permission_PermissionType = 1
)

// Enum value maps for Permission_PermissionType.
var (
	Permission_PermissionType_name = map[int32]string{
		0: "Owner",
		1: "User",
	}
	Permission_PermissionType_value = map[string]int32{
		"Owner": 0,
		"User":  1,
	}
)

func (x Permission_PermissionType) Enum() *Permission_PermissionType {
	p := new(Permission_PermissionType)
	*p = x
	return p
}

func (x Permission_PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission_PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_userAccountData_proto_enumTypes[0].Descriptor()
}

func (Permission_PermissionType) Type() protoreflect.EnumType {
	return &file_userAccountData_proto_enumTypes[0]
}

func (x Permission_PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission_PermissionType.Descriptor instead.
func (Permission_PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{1, 0}
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userAccountData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Key) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             int32                     `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Type           Permission_PermissionType `protobuf:"varint,2,opt,name=Type,json=type,proto3,enum=proto.Permission_PermissionType" json:"Type,omitempty"`
	PermissionName string                    `protobuf:"bytes,3,opt,name=PermissionName,json=permissionName,proto3" json:"PermissionName,omitempty"`
	Threshold      int64                     `protobuf:"varint,4,opt,name=Threshold,json=threshold,proto3" json:"Threshold,omitempty"`
	Operations     []byte                    `protobuf:"bytes,5,opt,name=Operations,json=operations,proto3" json:"Operations,omitempty"` //1 bit 1 contract
	Signers        []*Key                    `protobuf:"bytes,6,rep,name=Signers,json=signers,proto3" json:"Signers,omitempty"`
}

func (x *Permission) Reset() {
	*x = Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userAccountData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Permission) GetType() Permission_PermissionType {
	if x != nil {
		return x.Type
	}
	return Permission_Owner
}

func (x *Permission) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *Permission) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Permission) GetOperations() []byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Permission) GetSigners() []*Key {
	if x != nil {
		return x.Signers
	}
	return nil
}

type UserAccountData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address      []byte        `protobuf:"bytes,1,opt,name=Address,json=address,omitempty,proto3" json:"Address,omitempty"`
	Name         []byte        `protobuf:"bytes,2,opt,name=Name,json=name,omitempty,proto3" json:"Name,omitempty"`
	RootHash     []byte        `protobuf:"bytes,3,opt,name=RootHash,json=rootHash,omitempty,proto3" json:"RootHash,omitempty"`
	Balance      int64         `protobuf:"varint,5,opt,name=Balance,json=balance,proto3" json:"Balance,omitempty"`
	Allowance    int64         `protobuf:"varint,6,opt,name=Allowance,json=allowance,proto3" json:"Allowance,omitempty"`
	Nonce        uint64        `protobuf:"varint,7,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	Permissions  []*Permission `protobuf:"bytes,8,rep,name=Permissions,json=permissions,omitempty,proto3" json:"Permissions,omitempty"`
	OwnerAddress []byte        `protobuf:"bytes,9,opt,name=OwnerAddress,json=ownerAddress,omitempty,proto3" json:"OwnerAddress,omitempty"`
	CodeHash     []byte        `protobuf:"bytes,10,opt,name=CodeHash,json=codeHash,omitempty,proto3" json:"CodeHash,omitempty"`
	CodeMetadata []byte        `protobuf:"bytes,11,opt,name=CodeMetadata,json=codeMetadata,omitempty,proto3" json:"CodeMetadata,omitempty"`
}

func (x *UserAccountData) Reset() {
	*x = UserAccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userAccountData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountData) ProtoMessage() {}

func (x *UserAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountData.ProtoReflect.Descriptor instead.
func (*UserAccountData) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{2}
}

func (x *UserAccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserAccountData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserAccountData) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *UserAccountData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserAccountData) GetAllowance() int64 {
	if x != nil {
		return x.Allowance
	}
	return 0
}

func (x *UserAccountData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *UserAccountData) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserAccountData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UserAccountData) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *UserAccountData) GetCodeMetadata() []byte {
	if x != nil {
		return x.CodeMetadata
	}
	return nil
}

type CodeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code          []byte `protobuf:"bytes,1,opt,name=Code,json=code,omitempty,proto3" json:"Code,omitempty"`
	NumReferences uint32 `protobuf:"varint,2,opt,name=NumReferences,json=numReferences,proto3" json:"NumReferences,omitempty"`
}

func (x *CodeEntry) Reset() {
	*x = CodeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userAccountData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeEntry) ProtoMessage() {}

func (x *CodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeEntry.ProtoReflect.Descriptor instead.
func (*CodeEntry) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{3}
}

func (x *CodeEntry) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *CodeEntry) GetNumReferences() uint32 {
	if x != nil {
		return x.NumReferences
	}
	return 0
}

var File_userAccountData_proto protoreflect.FileDescriptor

var file_userAccountData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x85, 0x02, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x52,
	0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x25, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x22,
	0x88, 0x03, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2c, 0x6f, 0x6d,
	0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x2c, 0x6f, 0x6d, 0x69, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x15, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2c, 0x6f,
	0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x0c, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x16,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2c, 0x6f, 0x6d, 0x69,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x63, 0x6f, 0x64, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x0c,
	0x43, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x16, 0x63, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4f, 0x0a, 0x09, 0x43, 0x6f,
	0x64, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x63, 0x6f, 0x64, 0x65, 0x2c, 0x6f, 0x6d, 0x69, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6e, 0x75,
	0x6d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userAccountData_proto_rawDescOnce sync.Once
	file_userAccountData_proto_rawDescData = file_userAccountData_proto_rawDesc
)

func file_userAccountData_proto_rawDescGZIP() []byte {
	file_userAccountData_proto_rawDescOnce.Do(func() {
		file_userAccountData_proto_rawDescData = protoimpl.X.CompressGZIP(file_userAccountData_proto_rawDescData)
	})
	return file_userAccountData_proto_rawDescData
}

var file_userAccountData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userAccountData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userAccountData_proto_goTypes = []interface{}{
	(Permission_PermissionType)(0), // 0: proto.Permission.PermissionType
	(*Key)(nil),                    // 1: proto.Key
	(*Permission)(nil),             // 2: proto.Permission
	(*UserAccountData)(nil),        // 3: proto.UserAccountData
	(*CodeEntry)(nil),              // 4: proto.CodeEntry
}
var file_userAccountData_proto_depIdxs = []int32{
	0, // 0: proto.Permission.Type:type_name -> proto.Permission.PermissionType
	1, // 1: proto.Permission.Signers:type_name -> proto.Key
	2, // 2: proto.UserAccountData.Permissions:type_name -> proto.Permission
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userAccountData_proto_init() }
func file_userAccountData_proto_init() {
	if File_userAccountData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userAccountData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userAccountData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userAccountData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userAccountData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userAccountData_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userAccountData_proto_goTypes,
		DependencyIndexes: file_userAccountData_proto_depIdxs,
		EnumInfos:         file_userAccountData_proto_enumTypes,
		MessageInfos:      file_userAccountData_proto_msgTypes,
	}.Build()
	File_userAccountData_proto = out.File
	file_userAccountData_proto_rawDesc = nil
	file_userAccountData_proto_goTypes = nil
	file_userAccountData_proto_depIdxs = nil
}
