// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: userAccountData.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission_PermissionType int32

const (
	Permission_Owner Permission_PermissionType = 0
	Permission_User  Permission_PermissionType = 1
)

// Enum value maps for Permission_PermissionType.
var (
	Permission_PermissionType_name = map[int32]string{
		0: "Owner",
		1: "User",
	}
	Permission_PermissionType_value = map[string]int32{
		"Owner": 0,
		"User":  1,
	}
)

func (x Permission_PermissionType) Enum() *Permission_PermissionType {
	p := new(Permission_PermissionType)
	*p = x
	return p
}

func (x Permission_PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission_PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_userAccountData_proto_enumTypes[0].Descriptor()
}

func (Permission_PermissionType) Type() protoreflect.EnumType {
	return &file_userAccountData_proto_enumTypes[0]
}

func (x Permission_PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission_PermissionType.Descriptor instead.
func (Permission_PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{1, 0}
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight        int64                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_userAccountData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Key) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Permission struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ID             int32                     `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Type           Permission_PermissionType `protobuf:"varint,2,opt,name=Type,json=type,proto3,enum=proto.Permission_PermissionType" json:"Type,omitempty"`
	PermissionName string                    `protobuf:"bytes,3,opt,name=PermissionName,json=permissionName,proto3" json:"PermissionName,omitempty"`
	Threshold      int64                     `protobuf:"varint,4,opt,name=Threshold,json=threshold,proto3" json:"Threshold,omitempty"`
	Operations     []byte                    `protobuf:"bytes,5,opt,name=Operations,json=operations,proto3" json:"Operations,omitempty"` //1 bit 1 contract
	Signers        []*Key                    `protobuf:"bytes,6,rep,name=Signers,json=signers,proto3" json:"Signers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_userAccountData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Permission) GetType() Permission_PermissionType {
	if x != nil {
		return x.Type
	}
	return Permission_Owner
}

func (x *Permission) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *Permission) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Permission) GetOperations() []byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Permission) GetSigners() []*Key {
	if x != nil {
		return x.Signers
	}
	return nil
}

type UserAccountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,json=address,omitempty,proto3" json:"Address,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=Name,json=name,omitempty,proto3" json:"Name,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,3,opt,name=RootHash,json=rootHash,omitempty,proto3" json:"RootHash,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=Balance,json=balance,proto3" json:"Balance,omitempty"`
	Allowance     int64                  `protobuf:"varint,6,opt,name=Allowance,json=allowance,proto3" json:"Allowance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,7,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,8,rep,name=Permissions,json=permissions,omitempty,proto3" json:"Permissions,omitempty"`
	OwnerAddress  []byte                 `protobuf:"bytes,9,opt,name=OwnerAddress,json=ownerAddress,omitempty,proto3" json:"OwnerAddress,omitempty"`
	CodeHash      []byte                 `protobuf:"bytes,10,opt,name=CodeHash,json=codeHash,omitempty,proto3" json:"CodeHash,omitempty"`
	CodeMetadata  []byte                 `protobuf:"bytes,11,opt,name=CodeMetadata,json=codeMetadata,omitempty,proto3" json:"CodeMetadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccountData) Reset() {
	*x = UserAccountData{}
	mi := &file_userAccountData_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountData) ProtoMessage() {}

func (x *UserAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountData.ProtoReflect.Descriptor instead.
func (*UserAccountData) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{2}
}

func (x *UserAccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserAccountData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserAccountData) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *UserAccountData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserAccountData) GetAllowance() int64 {
	if x != nil {
		return x.Allowance
	}
	return 0
}

func (x *UserAccountData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *UserAccountData) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserAccountData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UserAccountData) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *UserAccountData) GetCodeMetadata() []byte {
	if x != nil {
		return x.CodeMetadata
	}
	return nil
}

type CodeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=Code,json=code,omitempty,proto3" json:"Code,omitempty"`
	NumReferences uint32                 `protobuf:"varint,2,opt,name=NumReferences,json=numReferences,proto3" json:"NumReferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeEntry) Reset() {
	*x = CodeEntry{}
	mi := &file_userAccountData_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeEntry) ProtoMessage() {}

func (x *CodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_userAccountData_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeEntry.ProtoReflect.Descriptor instead.
func (*CodeEntry) Descriptor() ([]byte, []int) {
	return file_userAccountData_proto_rawDescGZIP(), []int{3}
}

func (x *CodeEntry) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *CodeEntry) GetNumReferences() uint32 {
	if x != nil {
		return x.NumReferences
	}
	return 0
}

var File_userAccountData_proto protoreflect.FileDescriptor

const file_userAccountData_proto_rawDesc = "" +
	"\n" +
	"\x15userAccountData.proto\x12\x05proto\"7\n" +
	"\x03Key\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x03R\x06weight\"\x85\x02\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\x04Type\x18\x02 \x01(\x0e2 .proto.Permission.PermissionTypeR\x04type\x12&\n" +
	"\x0ePermissionName\x18\x03 \x01(\tR\x0epermissionName\x12\x1c\n" +
	"\tThreshold\x18\x04 \x01(\x03R\tthreshold\x12\x1e\n" +
	"\n" +
	"Operations\x18\x05 \x01(\fR\n" +
	"operations\x12$\n" +
	"\aSigners\x18\x06 \x03(\v2\n" +
	".proto.KeyR\asigners\"%\n" +
	"\x0ePermissionType\x12\t\n" +
	"\x05Owner\x10\x00\x12\b\n" +
	"\x04User\x10\x01\"\x88\x03\n" +
	"\x0fUserAccountData\x12\"\n" +
	"\aAddress\x18\x01 \x01(\fR\x11address,omitempty\x12\x1c\n" +
	"\x04Name\x18\x02 \x01(\fR\x0ename,omitempty\x12$\n" +
	"\bRootHash\x18\x03 \x01(\fR\x12rootHash,omitempty\x12\x18\n" +
	"\aBalance\x18\x05 \x01(\x03R\abalance\x12\x1c\n" +
	"\tAllowance\x18\x06 \x01(\x03R\tallowance\x12\x14\n" +
	"\x05Nonce\x18\a \x01(\x04R\x05nonce\x12=\n" +
	"\vPermissions\x18\b \x03(\v2\x11.proto.PermissionR\x15permissions,omitempty\x12,\n" +
	"\fOwnerAddress\x18\t \x01(\fR\x16ownerAddress,omitempty\x12$\n" +
	"\bCodeHash\x18\n" +
	" \x01(\fR\x12codeHash,omitempty\x12,\n" +
	"\fCodeMetadata\x18\v \x01(\fR\x16codeMetadata,omitempty\"O\n" +
	"\tCodeEntry\x12\x1c\n" +
	"\x04Code\x18\x01 \x01(\fR\x0ecode,omitempty\x12$\n" +
	"\rNumReferences\x18\x02 \x01(\rR\rnumReferencesB\n" +
	"Z\b./;stateb\x06proto3"

var (
	file_userAccountData_proto_rawDescOnce sync.Once
	file_userAccountData_proto_rawDescData []byte
)

func file_userAccountData_proto_rawDescGZIP() []byte {
	file_userAccountData_proto_rawDescOnce.Do(func() {
		file_userAccountData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userAccountData_proto_rawDesc), len(file_userAccountData_proto_rawDesc)))
	})
	return file_userAccountData_proto_rawDescData
}

var file_userAccountData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userAccountData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userAccountData_proto_goTypes = []any{
	(Permission_PermissionType)(0), // 0: proto.Permission.PermissionType
	(*Key)(nil),                    // 1: proto.Key
	(*Permission)(nil),             // 2: proto.Permission
	(*UserAccountData)(nil),        // 3: proto.UserAccountData
	(*CodeEntry)(nil),              // 4: proto.CodeEntry
}
var file_userAccountData_proto_depIdxs = []int32{
	0, // 0: proto.Permission.Type:type_name -> proto.Permission.PermissionType
	1, // 1: proto.Permission.Signers:type_name -> proto.Key
	2, // 2: proto.UserAccountData.Permissions:type_name -> proto.Permission
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userAccountData_proto_init() }
func file_userAccountData_proto_init() {
	if File_userAccountData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userAccountData_proto_rawDesc), len(file_userAccountData_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userAccountData_proto_goTypes,
		DependencyIndexes: file_userAccountData_proto_depIdxs,
		EnumInfos:         file_userAccountData_proto_enumTypes,
		MessageInfos:      file_userAccountData_proto_msgTypes,
	}.Build()
	File_userAccountData_proto = out.File
	file_userAccountData_proto_goTypes = nil
	file_userAccountData_proto_depIdxs = nil
}
