// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: validatorInfo.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidatorInfo represents the data regarding a validator that is verified by the metaNodes
type ValidatorInfo struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	PublicKey                       []byte                 `protobuf:"bytes,1,opt,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
	List                            string                 `protobuf:"bytes,2,opt,name=List,json=list,proto3" json:"List,omitempty"`
	Index                           uint32                 `protobuf:"varint,3,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	TempRating                      uint32                 `protobuf:"varint,4,opt,name=TempRating,json=tempRating,proto3" json:"TempRating,omitempty"`
	Rating                          uint32                 `protobuf:"varint,5,opt,name=Rating,json=rating,proto3" json:"Rating,omitempty"`
	RatingModifier                  float32                `protobuf:"fixed32,6,opt,name=RatingModifier,json=ratingModifier,proto3" json:"RatingModifier,omitempty"`
	OwnerAddress                    []byte                 `protobuf:"bytes,7,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	LeaderSuccess                   uint32                 `protobuf:"varint,9,opt,name=LeaderSuccess,json=leaderSuccess,proto3" json:"LeaderSuccess,omitempty"`
	LeaderFailure                   uint32                 `protobuf:"varint,10,opt,name=LeaderFailure,json=leaderFailure,proto3" json:"LeaderFailure,omitempty"`
	ValidatorSuccess                uint32                 `protobuf:"varint,11,opt,name=ValidatorSuccess,json=validatorSuccess,proto3" json:"ValidatorSuccess,omitempty"`
	ValidatorFailure                uint32                 `protobuf:"varint,12,opt,name=ValidatorFailure,json=validatorFailure,proto3" json:"ValidatorFailure,omitempty"`
	ValidatorIgnoredSignatures      uint32                 `protobuf:"varint,13,opt,name=ValidatorIgnoredSignatures,json=validatorIgnoredSignatures,proto3" json:"ValidatorIgnoredSignatures,omitempty"`
	NumSelectedInSuccessBlocks      uint32                 `protobuf:"varint,14,opt,name=NumSelectedInSuccessBlocks,json=numSelectedInSuccessBlocks,proto3" json:"NumSelectedInSuccessBlocks,omitempty"`
	TotalLeaderSuccess              uint32                 `protobuf:"varint,16,opt,name=TotalLeaderSuccess,json=totalLeaderSuccess,proto3" json:"TotalLeaderSuccess,omitempty"`
	TotalLeaderFailure              uint32                 `protobuf:"varint,17,opt,name=TotalLeaderFailure,json=totalLeaderFailure,proto3" json:"TotalLeaderFailure,omitempty"`
	TotalValidatorSuccess           uint32                 `protobuf:"varint,18,opt,name=TotalValidatorSuccess,json=totalValidatorSuccess,proto3" json:"TotalValidatorSuccess,omitempty"`
	TotalValidatorFailure           uint32                 `protobuf:"varint,19,opt,name=TotalValidatorFailure,json=totalValidatorFailure,proto3" json:"TotalValidatorFailure,omitempty"`
	TotalValidatorIgnoredSignatures uint32                 `protobuf:"varint,20,opt,name=TotalValidatorIgnoredSignatures,json=totalValidatorIgnoredSignatures,proto3" json:"TotalValidatorIgnoredSignatures,omitempty"`
	IsPubKeyRevoked                 bool                   `protobuf:"varint,21,opt,name=IsPubKeyRevoked,json=pubKeyRevoked,proto3" json:"IsPubKeyRevoked,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ValidatorInfo) Reset() {
	*x = ValidatorInfo{}
	mi := &file_validatorInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorInfo) ProtoMessage() {}

func (x *ValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_validatorInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorInfo.ProtoReflect.Descriptor instead.
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return file_validatorInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorInfo) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ValidatorInfo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ValidatorInfo) GetTempRating() uint32 {
	if x != nil {
		return x.TempRating
	}
	return 0
}

func (x *ValidatorInfo) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ValidatorInfo) GetRatingModifier() float32 {
	if x != nil {
		return x.RatingModifier
	}
	return 0
}

func (x *ValidatorInfo) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *ValidatorInfo) GetLeaderSuccess() uint32 {
	if x != nil {
		return x.LeaderSuccess
	}
	return 0
}

func (x *ValidatorInfo) GetLeaderFailure() uint32 {
	if x != nil {
		return x.LeaderFailure
	}
	return 0
}

func (x *ValidatorInfo) GetValidatorSuccess() uint32 {
	if x != nil {
		return x.ValidatorSuccess
	}
	return 0
}

func (x *ValidatorInfo) GetValidatorFailure() uint32 {
	if x != nil {
		return x.ValidatorFailure
	}
	return 0
}

func (x *ValidatorInfo) GetValidatorIgnoredSignatures() uint32 {
	if x != nil {
		return x.ValidatorIgnoredSignatures
	}
	return 0
}

func (x *ValidatorInfo) GetNumSelectedInSuccessBlocks() uint32 {
	if x != nil {
		return x.NumSelectedInSuccessBlocks
	}
	return 0
}

func (x *ValidatorInfo) GetTotalLeaderSuccess() uint32 {
	if x != nil {
		return x.TotalLeaderSuccess
	}
	return 0
}

func (x *ValidatorInfo) GetTotalLeaderFailure() uint32 {
	if x != nil {
		return x.TotalLeaderFailure
	}
	return 0
}

func (x *ValidatorInfo) GetTotalValidatorSuccess() uint32 {
	if x != nil {
		return x.TotalValidatorSuccess
	}
	return 0
}

func (x *ValidatorInfo) GetTotalValidatorFailure() uint32 {
	if x != nil {
		return x.TotalValidatorFailure
	}
	return 0
}

func (x *ValidatorInfo) GetTotalValidatorIgnoredSignatures() uint32 {
	if x != nil {
		return x.TotalValidatorIgnoredSignatures
	}
	return 0
}

func (x *ValidatorInfo) GetIsPubKeyRevoked() bool {
	if x != nil {
		return x.IsPubKeyRevoked
	}
	return false
}

var File_validatorInfo_proto protoreflect.FileDescriptor

const file_validatorInfo_proto_rawDesc = "" +
	"\n" +
	"\x13validatorInfo.proto\x12\x05proto\"\xbd\x06\n" +
	"\rValidatorInfo\x12\x1c\n" +
	"\tPublicKey\x18\x01 \x01(\fR\tpublicKey\x12\x12\n" +
	"\x04List\x18\x02 \x01(\tR\x04list\x12\x14\n" +
	"\x05Index\x18\x03 \x01(\rR\x05index\x12\x1e\n" +
	"\n" +
	"TempRating\x18\x04 \x01(\rR\n" +
	"tempRating\x12\x16\n" +
	"\x06Rating\x18\x05 \x01(\rR\x06rating\x12&\n" +
	"\x0eRatingModifier\x18\x06 \x01(\x02R\x0eratingModifier\x12\"\n" +
	"\fOwnerAddress\x18\a \x01(\fR\fownerAddress\x12$\n" +
	"\rLeaderSuccess\x18\t \x01(\rR\rleaderSuccess\x12$\n" +
	"\rLeaderFailure\x18\n" +
	" \x01(\rR\rleaderFailure\x12*\n" +
	"\x10ValidatorSuccess\x18\v \x01(\rR\x10validatorSuccess\x12*\n" +
	"\x10ValidatorFailure\x18\f \x01(\rR\x10validatorFailure\x12>\n" +
	"\x1aValidatorIgnoredSignatures\x18\r \x01(\rR\x1avalidatorIgnoredSignatures\x12>\n" +
	"\x1aNumSelectedInSuccessBlocks\x18\x0e \x01(\rR\x1anumSelectedInSuccessBlocks\x12.\n" +
	"\x12TotalLeaderSuccess\x18\x10 \x01(\rR\x12totalLeaderSuccess\x12.\n" +
	"\x12TotalLeaderFailure\x18\x11 \x01(\rR\x12totalLeaderFailure\x124\n" +
	"\x15TotalValidatorSuccess\x18\x12 \x01(\rR\x15totalValidatorSuccess\x124\n" +
	"\x15TotalValidatorFailure\x18\x13 \x01(\rR\x15totalValidatorFailure\x12H\n" +
	"\x1fTotalValidatorIgnoredSignatures\x18\x14 \x01(\rR\x1ftotalValidatorIgnoredSignatures\x12&\n" +
	"\x0fIsPubKeyRevoked\x18\x15 \x01(\bR\rpubKeyRevokedB\n" +
	"Z\b./;stateb\x06proto3"

var (
	file_validatorInfo_proto_rawDescOnce sync.Once
	file_validatorInfo_proto_rawDescData []byte
)

func file_validatorInfo_proto_rawDescGZIP() []byte {
	file_validatorInfo_proto_rawDescOnce.Do(func() {
		file_validatorInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validatorInfo_proto_rawDesc), len(file_validatorInfo_proto_rawDesc)))
	})
	return file_validatorInfo_proto_rawDescData
}

var file_validatorInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validatorInfo_proto_goTypes = []any{
	(*ValidatorInfo)(nil), // 0: proto.ValidatorInfo
}
var file_validatorInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validatorInfo_proto_init() }
func file_validatorInfo_proto_init() {
	if File_validatorInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validatorInfo_proto_rawDesc), len(file_validatorInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validatorInfo_proto_goTypes,
		DependencyIndexes: file_validatorInfo_proto_depIdxs,
		MessageInfos:      file_validatorInfo_proto_msgTypes,
	}.Build()
	File_validatorInfo_proto = out.File
	file_validatorInfo_proto_goTypes = nil
	file_validatorInfo_proto_depIdxs = nil
}
