// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: bootstrapData.proto

package bootstrapStorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//BootstrapHeaderInfo is used to store information about a header
type BootstrapHeaderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch uint32 `protobuf:"varint,1,opt,name=Epoch,json=epoch,omitempty,proto3" json:"Epoch,omitempty"`
	Nonce uint64 `protobuf:"varint,2,opt,name=Nonce,json=nonce,omitempty,proto3" json:"Nonce,omitempty"`
	Hash  []byte `protobuf:"bytes,3,opt,name=Hash,json=hash,omitempty,proto3" json:"Hash,omitempty"`
}

func (x *BootstrapHeaderInfo) Reset() {
	*x = BootstrapHeaderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrapData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapHeaderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapHeaderInfo) ProtoMessage() {}

func (x *BootstrapHeaderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrapData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapHeaderInfo.ProtoReflect.Descriptor instead.
func (*BootstrapHeaderInfo) Descriptor() ([]byte, []int) {
	return file_bootstrapData_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapHeaderInfo) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BootstrapHeaderInfo) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BootstrapHeaderInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// BootstrapData is used to store information that are needed for bootstrap
type BootstrapData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastHeader                 *BootstrapHeaderInfo `protobuf:"bytes,1,opt,name=LastHeader,json=lastHeader,omitempty,proto3" json:"LastHeader,omitempty"`
	LastSlot                   int64                `protobuf:"varint,2,opt,name=LastSlot,json=lastSlot,omitempty,proto3" json:"LastSlot,omitempty"`
	HighestFinalBlockNonce     uint64               `protobuf:"varint,3,opt,name=HighestFinalBlockNonce,json=highestFinalBlockNonce,omitempty,proto3" json:"HighestFinalBlockNonce,omitempty"`
	NodesCoordinatorConfigKey  []byte               `protobuf:"bytes,10,opt,name=NodesCoordinatorConfigKey,json=nodesCoordinatorConfigKey,omitempty,proto3" json:"NodesCoordinatorConfigKey,omitempty"`
	EpochStartTriggerConfigKey []byte               `protobuf:"bytes,11,opt,name=EpochStartTriggerConfigKey,json=epochStartTriggerConfigKey,omitempty,proto3" json:"EpochStartTriggerConfigKey,omitempty"`
}

func (x *BootstrapData) Reset() {
	*x = BootstrapData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrapData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapData) ProtoMessage() {}

func (x *BootstrapData) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrapData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapData.ProtoReflect.Descriptor instead.
func (*BootstrapData) Descriptor() ([]byte, []int) {
	return file_bootstrapData_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapData) GetLastHeader() *BootstrapHeaderInfo {
	if x != nil {
		return x.LastHeader
	}
	return nil
}

func (x *BootstrapData) GetLastSlot() int64 {
	if x != nil {
		return x.LastSlot
	}
	return 0
}

func (x *BootstrapData) GetHighestFinalBlockNonce() uint64 {
	if x != nil {
		return x.HighestFinalBlockNonce
	}
	return 0
}

func (x *BootstrapData) GetNodesCoordinatorConfigKey() []byte {
	if x != nil {
		return x.NodesCoordinatorConfigKey
	}
	return nil
}

func (x *BootstrapData) GetEpochStartTriggerConfigKey() []byte {
	if x != nil {
		return x.EpochStartTriggerConfigKey
	}
	return nil
}

type SlotNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *SlotNum) Reset() {
	*x = SlotNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrapData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotNum) ProtoMessage() {}

func (x *SlotNum) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrapData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotNum.ProtoReflect.Descriptor instead.
func (*SlotNum) Descriptor() ([]byte, []int) {
	return file_bootstrapData_proto_rawDescGZIP(), []int{2}
}

func (x *SlotNum) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_bootstrapData_proto protoreflect.FileDescriptor

var file_bootstrapData_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x13,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0xcf, 0x02, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x44, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2c,
	0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x08, 0x4c, 0x61, 0x73,
	0x74, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x61, 0x73,
	0x74, 0x53, 0x6c, 0x6f, 0x74, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x40, 0x0a, 0x16, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x20, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x46, 0x0a, 0x19, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x23, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x2c,
	0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x1a, 0x45, 0x70, 0x6f,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x24, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x2c, 0x6f, 0x6d, 0x69, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x53, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d,
	0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x3b, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bootstrapData_proto_rawDescOnce sync.Once
	file_bootstrapData_proto_rawDescData = file_bootstrapData_proto_rawDesc
)

func file_bootstrapData_proto_rawDescGZIP() []byte {
	file_bootstrapData_proto_rawDescOnce.Do(func() {
		file_bootstrapData_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootstrapData_proto_rawDescData)
	})
	return file_bootstrapData_proto_rawDescData
}

var file_bootstrapData_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bootstrapData_proto_goTypes = []interface{}{
	(*BootstrapHeaderInfo)(nil), // 0: proto.BootstrapHeaderInfo
	(*BootstrapData)(nil),       // 1: proto.BootstrapData
	(*SlotNum)(nil),             // 2: proto.SlotNum
}
var file_bootstrapData_proto_depIdxs = []int32{
	0, // 0: proto.BootstrapData.LastHeader:type_name -> proto.BootstrapHeaderInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bootstrapData_proto_init() }
func file_bootstrapData_proto_init() {
	if File_bootstrapData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bootstrapData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapHeaderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrapData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrapData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootstrapData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bootstrapData_proto_goTypes,
		DependencyIndexes: file_bootstrapData_proto_depIdxs,
		MessageInfos:      file_bootstrapData_proto_msgTypes,
	}.Build()
	File_bootstrapData_proto = out.File
	file_bootstrapData_proto_rawDesc = nil
	file_bootstrapData_proto_goTypes = nil
	file_bootstrapData_proto_depIdxs = nil
}
