// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TXContract_ContractType int32

const (
	TXContract_TransferContractType                TXContract_ContractType = 0
	TXContract_CreateAssetContractType             TXContract_ContractType = 1
	TXContract_CreateValidatorContractType         TXContract_ContractType = 2
	TXContract_ValidatorConfigContractType         TXContract_ContractType = 3
	TXContract_FreezeContractType                  TXContract_ContractType = 4
	TXContract_UnfreezeContractType                TXContract_ContractType = 5
	TXContract_DelegateContractType                TXContract_ContractType = 6
	TXContract_UndelegateContractType              TXContract_ContractType = 7
	TXContract_WithdrawContractType                TXContract_ContractType = 8
	TXContract_ClaimContractType                   TXContract_ContractType = 9
	TXContract_UnjailContractType                  TXContract_ContractType = 10
	TXContract_AssetTriggerContractType            TXContract_ContractType = 11
	TXContract_SetAccountNameContractType          TXContract_ContractType = 12
	TXContract_ProposalContractType                TXContract_ContractType = 13
	TXContract_VoteContractType                    TXContract_ContractType = 14
	TXContract_ConfigITOContractType               TXContract_ContractType = 15
	TXContract_SetITOPricesContractType            TXContract_ContractType = 16
	TXContract_BuyContractType                     TXContract_ContractType = 17
	TXContract_SellContractType                    TXContract_ContractType = 18
	TXContract_CancelMarketOrderContractType       TXContract_ContractType = 19
	TXContract_CreateMarketplaceContractType       TXContract_ContractType = 20
	TXContract_ConfigMarketplaceContractType       TXContract_ContractType = 21
	TXContract_UpdateAccountPermissionContractType TXContract_ContractType = 22
	TXContract_DepositContractType                 TXContract_ContractType = 23
	TXContract_ITOTriggerContractType              TXContract_ContractType = 24
	TXContract_SmartContractType                   TXContract_ContractType = 63
)

// Enum value maps for TXContract_ContractType.
var (
	TXContract_ContractType_name = map[int32]string{
		0:  "TransferContractType",
		1:  "CreateAssetContractType",
		2:  "CreateValidatorContractType",
		3:  "ValidatorConfigContractType",
		4:  "FreezeContractType",
		5:  "UnfreezeContractType",
		6:  "DelegateContractType",
		7:  "UndelegateContractType",
		8:  "WithdrawContractType",
		9:  "ClaimContractType",
		10: "UnjailContractType",
		11: "AssetTriggerContractType",
		12: "SetAccountNameContractType",
		13: "ProposalContractType",
		14: "VoteContractType",
		15: "ConfigITOContractType",
		16: "SetITOPricesContractType",
		17: "BuyContractType",
		18: "SellContractType",
		19: "CancelMarketOrderContractType",
		20: "CreateMarketplaceContractType",
		21: "ConfigMarketplaceContractType",
		22: "UpdateAccountPermissionContractType",
		23: "DepositContractType",
		24: "ITOTriggerContractType",
		63: "SmartContractType",
	}
	TXContract_ContractType_value = map[string]int32{
		"TransferContractType":                0,
		"CreateAssetContractType":             1,
		"CreateValidatorContractType":         2,
		"ValidatorConfigContractType":         3,
		"FreezeContractType":                  4,
		"UnfreezeContractType":                5,
		"DelegateContractType":                6,
		"UndelegateContractType":              7,
		"WithdrawContractType":                8,
		"ClaimContractType":                   9,
		"UnjailContractType":                  10,
		"AssetTriggerContractType":            11,
		"SetAccountNameContractType":          12,
		"ProposalContractType":                13,
		"VoteContractType":                    14,
		"ConfigITOContractType":               15,
		"SetITOPricesContractType":            16,
		"BuyContractType":                     17,
		"SellContractType":                    18,
		"CancelMarketOrderContractType":       19,
		"CreateMarketplaceContractType":       20,
		"ConfigMarketplaceContractType":       21,
		"UpdateAccountPermissionContractType": 22,
		"DepositContractType":                 23,
		"ITOTriggerContractType":              24,
		"SmartContractType":                   63,
	}
)

func (x TXContract_ContractType) Enum() *TXContract_ContractType {
	p := new(TXContract_ContractType)
	*p = x
	return p
}

func (x TXContract_ContractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TXContract_ContractType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (TXContract_ContractType) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x TXContract_ContractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TXContract_ContractType.Descriptor instead.
func (TXContract_ContractType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0}
}

type Transaction_TXResult int32

const (
	Transaction_SUCCESS Transaction_TXResult = 0
	Transaction_FAILED  Transaction_TXResult = 1
)

// Enum value maps for Transaction_TXResult.
var (
	Transaction_TXResult_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	Transaction_TXResult_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x Transaction_TXResult) Enum() *Transaction_TXResult {
	p := new(Transaction_TXResult)
	*p = x
	return p
}

func (x Transaction_TXResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_TXResult) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[1].Descriptor()
}

func (Transaction_TXResult) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[1]
}

func (x Transaction_TXResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_TXResult.Descriptor instead.
func (Transaction_TXResult) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1, 0}
}

type Transaction_TXResultCode int32

const (
	Transaction_Ok Transaction_TXResultCode = 0
	// OutOfFunds is returned when the caller (sender) runs out of funds.
	Transaction_OutOfFunds      Transaction_TXResultCode = 1
	Transaction_AccountError    Transaction_TXResultCode = 2
	Transaction_AssetError      Transaction_TXResultCode = 3
	Transaction_ContractInvalid Transaction_TXResultCode = 4
	// ContractNotFound is returned when the called contract does not exist.
	Transaction_ContractNotFound         Transaction_TXResultCode = 5
	Transaction_FeeInvalid               Transaction_TXResultCode = 6
	Transaction_ParameterInvalid         Transaction_TXResultCode = 7
	Transaction_APRInvalid               Transaction_TXResultCode = 8
	Transaction_AssetIDInvalid           Transaction_TXResultCode = 9
	Transaction_AssetTypeInvalid         Transaction_TXResultCode = 10
	Transaction_AssetCantBeMinted        Transaction_TXResultCode = 11
	Transaction_AssetCantBeBurned        Transaction_TXResultCode = 12
	Transaction_AssetCantBePaused        Transaction_TXResultCode = 13
	Transaction_AssetCantBeDelegated     Transaction_TXResultCode = 14
	Transaction_AssetOwnerCantBeChanged  Transaction_TXResultCode = 15
	Transaction_AccountNotOwner          Transaction_TXResultCode = 16
	Transaction_CommissionTooHigh        Transaction_TXResultCode = 17
	Transaction_DelegationAmountInvalid  Transaction_TXResultCode = 18
	Transaction_ProposalNotActive        Transaction_TXResultCode = 19
	Transaction_ValueInvalid             Transaction_TXResultCode = 20
	Transaction_AmountInvalid            Transaction_TXResultCode = 21
	Transaction_BucketIDInvalid          Transaction_TXResultCode = 22
	Transaction_KeyConflict              Transaction_TXResultCode = 23
	Transaction_MaxDelegationAmount      Transaction_TXResultCode = 24
	Transaction_InvalidPeerKey           Transaction_TXResultCode = 25
	Transaction_MinKFIStakedUnreached    Transaction_TXResultCode = 26
	Transaction_MaxSupplyExceeded        Transaction_TXResultCode = 27
	Transaction_SaveAccountError         Transaction_TXResultCode = 28
	Transaction_LoadAccountError         Transaction_TXResultCode = 29
	Transaction_SameAccountError         Transaction_TXResultCode = 30
	Transaction_AssetPaused              Transaction_TXResultCode = 31
	Transaction_DeletegateError          Transaction_TXResultCode = 32
	Transaction_WithdrawNotAvailable     Transaction_TXResultCode = 33
	Transaction_ErrOverflow              Transaction_TXResultCode = 34
	Transaction_SetStakingErr            Transaction_TXResultCode = 35
	Transaction_SetMarketOrderErr        Transaction_TXResultCode = 36
	Transaction_BalanceError             Transaction_TXResultCode = 37
	Transaction_KAPPError                Transaction_TXResultCode = 38
	Transaction_UnfreezeError            Transaction_TXResultCode = 39
	Transaction_UndelegateError          Transaction_TXResultCode = 40
	Transaction_WithdrawError            Transaction_TXResultCode = 41
	Transaction_ClaimError               Transaction_TXResultCode = 42
	Transaction_BucketsExceeded          Transaction_TXResultCode = 43
	Transaction_AssetCantBeWiped         Transaction_TXResultCode = 44
	Transaction_AssetCantAddRoles        Transaction_TXResultCode = 45
	Transaction_FreezeError              Transaction_TXResultCode = 46
	Transaction_ITONotActive             Transaction_TXResultCode = 47
	Transaction_NFTMintStopped           Transaction_TXResultCode = 48
	Transaction_RoyaltiesChangeStopped   Transaction_TXResultCode = 49
	Transaction_ITOKAPPError             Transaction_TXResultCode = 50
	Transaction_ITOWhiteListError        Transaction_TXResultCode = 51
	Transaction_NFTMetadataChangeStopped Transaction_TXResultCode = 52
	Transaction_AlreadyExists            Transaction_TXResultCode = 53
	Transaction_IteratorLimitReached     Transaction_TXResultCode = 54
	// FunctionNotFound is returned when the input specifies a function name that does not exist or is not public.
	Transaction_VMFunctionNotFound Transaction_TXResultCode = 55
	// FunctionWrongSignature is returned when the wrong number of arguments is provided.
	Transaction_VMFunctionWrongSignature Transaction_TXResultCode = 56
	// UserError is returned for various execution errors.
	Transaction_VMUserError Transaction_TXResultCode = 57
	// OutOfGas is returned when VM execution runs out of gas.
	Transaction_VMOutOfGas Transaction_TXResultCode = 58
	// AccountCollision is returned when created account already exists.
	Transaction_VMAccountCollision Transaction_TXResultCode = 59
	// CallStackOverFlow is returned when stack overflow occurs.
	Transaction_VMCallStackOverFlow Transaction_TXResultCode = 60
	// Execution Panicked
	Transaction_VMExecutionPanicked Transaction_TXResultCode = 61
	// ExecutionFailed is returned when the execution of the specified function has failed.
	Transaction_VMExecutionFailed Transaction_TXResultCode = 62
	// UpgradeFailed is returned when the upgrade of the contract has failed
	Transaction_VMUpgradeFailed Transaction_TXResultCode = 63
	// SimulateFailed is returned when tx simulation fails execution
	Transaction_VMSimulateFailed Transaction_TXResultCode = 64
	// KDA Transfer not allowed
	Transaction_KDATransferNotAllowed Transaction_TXResultCode = 65
	// TransferRestricted is returned when a KDA with a ControllerAddress is moved by a path that does not involve the controller.
	Transaction_TransferRestricted Transaction_TXResultCode = 66
	Transaction_Fail               Transaction_TXResultCode = 99
)

// Enum value maps for Transaction_TXResultCode.
var (
	Transaction_TXResultCode_name = map[int32]string{
		0:  "Ok",
		1:  "OutOfFunds",
		2:  "AccountError",
		3:  "AssetError",
		4:  "ContractInvalid",
		5:  "ContractNotFound",
		6:  "FeeInvalid",
		7:  "ParameterInvalid",
		8:  "APRInvalid",
		9:  "AssetIDInvalid",
		10: "AssetTypeInvalid",
		11: "AssetCantBeMinted",
		12: "AssetCantBeBurned",
		13: "AssetCantBePaused",
		14: "AssetCantBeDelegated",
		15: "AssetOwnerCantBeChanged",
		16: "AccountNotOwner",
		17: "CommissionTooHigh",
		18: "DelegationAmountInvalid",
		19: "ProposalNotActive",
		20: "ValueInvalid",
		21: "AmountInvalid",
		22: "BucketIDInvalid",
		23: "KeyConflict",
		24: "MaxDelegationAmount",
		25: "InvalidPeerKey",
		26: "MinKFIStakedUnreached",
		27: "MaxSupplyExceeded",
		28: "SaveAccountError",
		29: "LoadAccountError",
		30: "SameAccountError",
		31: "AssetPaused",
		32: "DeletegateError",
		33: "WithdrawNotAvailable",
		34: "ErrOverflow",
		35: "SetStakingErr",
		36: "SetMarketOrderErr",
		37: "BalanceError",
		38: "KAPPError",
		39: "UnfreezeError",
		40: "UndelegateError",
		41: "WithdrawError",
		42: "ClaimError",
		43: "BucketsExceeded",
		44: "AssetCantBeWiped",
		45: "AssetCantAddRoles",
		46: "FreezeError",
		47: "ITONotActive",
		48: "NFTMintStopped",
		49: "RoyaltiesChangeStopped",
		50: "ITOKAPPError",
		51: "ITOWhiteListError",
		52: "NFTMetadataChangeStopped",
		53: "AlreadyExists",
		54: "IteratorLimitReached",
		55: "VMFunctionNotFound",
		56: "VMFunctionWrongSignature",
		57: "VMUserError",
		58: "VMOutOfGas",
		59: "VMAccountCollision",
		60: "VMCallStackOverFlow",
		61: "VMExecutionPanicked",
		62: "VMExecutionFailed",
		63: "VMUpgradeFailed",
		64: "VMSimulateFailed",
		65: "KDATransferNotAllowed",
		66: "TransferRestricted",
		99: "Fail",
	}
	Transaction_TXResultCode_value = map[string]int32{
		"Ok":                       0,
		"OutOfFunds":               1,
		"AccountError":             2,
		"AssetError":               3,
		"ContractInvalid":          4,
		"ContractNotFound":         5,
		"FeeInvalid":               6,
		"ParameterInvalid":         7,
		"APRInvalid":               8,
		"AssetIDInvalid":           9,
		"AssetTypeInvalid":         10,
		"AssetCantBeMinted":        11,
		"AssetCantBeBurned":        12,
		"AssetCantBePaused":        13,
		"AssetCantBeDelegated":     14,
		"AssetOwnerCantBeChanged":  15,
		"AccountNotOwner":          16,
		"CommissionTooHigh":        17,
		"DelegationAmountInvalid":  18,
		"ProposalNotActive":        19,
		"ValueInvalid":             20,
		"AmountInvalid":            21,
		"BucketIDInvalid":          22,
		"KeyConflict":              23,
		"MaxDelegationAmount":      24,
		"InvalidPeerKey":           25,
		"MinKFIStakedUnreached":    26,
		"MaxSupplyExceeded":        27,
		"SaveAccountError":         28,
		"LoadAccountError":         29,
		"SameAccountError":         30,
		"AssetPaused":              31,
		"DeletegateError":          32,
		"WithdrawNotAvailable":     33,
		"ErrOverflow":              34,
		"SetStakingErr":            35,
		"SetMarketOrderErr":        36,
		"BalanceError":             37,
		"KAPPError":                38,
		"UnfreezeError":            39,
		"UndelegateError":          40,
		"WithdrawError":            41,
		"ClaimError":               42,
		"BucketsExceeded":          43,
		"AssetCantBeWiped":         44,
		"AssetCantAddRoles":        45,
		"FreezeError":              46,
		"ITONotActive":             47,
		"NFTMintStopped":           48,
		"RoyaltiesChangeStopped":   49,
		"ITOKAPPError":             50,
		"ITOWhiteListError":        51,
		"NFTMetadataChangeStopped": 52,
		"AlreadyExists":            53,
		"IteratorLimitReached":     54,
		"VMFunctionNotFound":       55,
		"VMFunctionWrongSignature": 56,
		"VMUserError":              57,
		"VMOutOfGas":               58,
		"VMAccountCollision":       59,
		"VMCallStackOverFlow":      60,
		"VMExecutionPanicked":      61,
		"VMExecutionFailed":        62,
		"VMUpgradeFailed":          63,
		"VMSimulateFailed":         64,
		"KDATransferNotAllowed":    65,
		"TransferRestricted":       66,
		"Fail":                     99,
	}
)

func (x Transaction_TXResultCode) Enum() *Transaction_TXResultCode {
	p := new(Transaction_TXResultCode)
	*p = x
	return p
}

func (x Transaction_TXResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_TXResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[2].Descriptor()
}

func (Transaction_TXResultCode) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[2]
}

func (x Transaction_TXResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_TXResultCode.Descriptor instead.
func (Transaction_TXResultCode) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1, 1}
}

// TXContract available
type TXContract struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          TXContract_ContractType `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=proto.TXContract_ContractType" json:"Type,omitempty"`
	Parameter     *anypb.Any              `protobuf:"bytes,2,opt,name=Parameter,json=parameter,proto3" json:"Parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TXContract) Reset() {
	*x = TXContract{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TXContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TXContract) ProtoMessage() {}

func (x *TXContract) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TXContract.ProtoReflect.Descriptor instead.
func (*TXContract) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TXContract) GetType() TXContract_ContractType {
	if x != nil {
		return x.Type
	}
	return TXContract_TransferContractType
}

func (x *TXContract) GetParameter() *anypb.Any {
	if x != nil {
		return x.Parameter
	}
	return nil
}

// Transaction holds all the data needed for a value transfer
type Transaction struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RawData       *Transaction_Raw         `protobuf:"bytes,1,opt,name=RawData,json=rawData,proto3" json:"RawData,omitempty"`
	Signature     [][]byte                 `protobuf:"bytes,2,rep,name=Signature,json=signature,omitempty,proto3" json:"Signature,omitempty"`
	Result        Transaction_TXResult     `protobuf:"varint,3,opt,name=Result,json=result,omitempty,proto3,enum=proto.Transaction_TXResult" json:"Result,omitempty"`
	ResultCode    Transaction_TXResultCode `protobuf:"varint,4,opt,name=ResultCode,json=resultCode,omitempty,proto3,enum=proto.Transaction_TXResultCode" json:"ResultCode,omitempty"`
	Receipts      []*Transaction_Receipt   `protobuf:"bytes,5,rep,name=Receipts,json=receipts,proto3" json:"Receipts,omitempty"`
	Block         uint64                   `protobuf:"varint,6,opt,name=Block,json=block,proto3" json:"Block,omitempty"`
	GasLimit      uint64                   `protobuf:"varint,7,opt,name=GasLimit,json=gasLimit,proto3" json:"GasLimit,omitempty"`
	GasMultiplier uint64                   `protobuf:"varint,8,opt,name=GasMultiplier,json=gasMultiplier,proto3" json:"GasMultiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetRawData() *Transaction_Raw {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *Transaction) GetSignature() [][]byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetResult() Transaction_TXResult {
	if x != nil {
		return x.Result
	}
	return Transaction_SUCCESS
}

func (x *Transaction) GetResultCode() Transaction_TXResultCode {
	if x != nil {
		return x.ResultCode
	}
	return Transaction_Ok
}

func (x *Transaction) GetReceipts() []*Transaction_Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *Transaction) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasMultiplier() uint64 {
	if x != nil {
		return x.GasMultiplier
	}
	return 0
}

type Transaction_KDAFee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KDA           []byte                 `protobuf:"bytes,1,opt,name=KDA,json=kda,proto3" json:"KDA,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"` // TODO: allow spread
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_KDAFee) Reset() {
	*x = Transaction_KDAFee{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_KDAFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_KDAFee) ProtoMessage() {}

func (x *Transaction_KDAFee) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_KDAFee.ProtoReflect.Descriptor instead.
func (*Transaction_KDAFee) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transaction_KDAFee) GetKDA() []byte {
	if x != nil {
		return x.KDA
	}
	return nil
}

func (x *Transaction_KDAFee) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Transaction_Raw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	Sender        []byte                 `protobuf:"bytes,2,opt,name=Sender,json=sender,proto3" json:"Sender,omitempty"`
	Contract      []*TXContract          `protobuf:"bytes,6,rep,name=Contract,json=contract,proto3" json:"Contract,omitempty"`
	PermissionID  int32                  `protobuf:"varint,7,opt,name=PermissionID,json=permissionID,omitempty,proto3" json:"PermissionID,omitempty"`
	Data          [][]byte               `protobuf:"bytes,10,rep,name=Data,json=data,omitempty,proto3" json:"Data,omitempty"`
	KAppFee       int64                  `protobuf:"varint,13,opt,name=KAppFee,json=kAppFee,proto3" json:"KAppFee,omitempty"`
	BandwidthFee  int64                  `protobuf:"varint,14,opt,name=BandwidthFee,json=bandwidthFee,proto3" json:"BandwidthFee,omitempty"`
	Version       uint32                 `protobuf:"varint,15,opt,name=Version,json=version,omitempty,proto3" json:"Version,omitempty"`
	ChainID       []byte                 `protobuf:"bytes,16,opt,name=ChainID,json=chainID,omitempty,proto3" json:"ChainID,omitempty"`
	KDAFee        *Transaction_KDAFee    `protobuf:"bytes,17,opt,name=KDAFee,json=kdaFee,proto3" json:"KDAFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Raw) Reset() {
	*x = Transaction_Raw{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Raw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Raw) ProtoMessage() {}

func (x *Transaction_Raw) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Raw.ProtoReflect.Descriptor instead.
func (*Transaction_Raw) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Transaction_Raw) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction_Raw) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transaction_Raw) GetContract() []*TXContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Transaction_Raw) GetPermissionID() int32 {
	if x != nil {
		return x.PermissionID
	}
	return 0
}

func (x *Transaction_Raw) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction_Raw) GetKAppFee() int64 {
	if x != nil {
		return x.KAppFee
	}
	return 0
}

func (x *Transaction_Raw) GetBandwidthFee() int64 {
	if x != nil {
		return x.BandwidthFee
	}
	return 0
}

func (x *Transaction_Raw) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Transaction_Raw) GetChainID() []byte {
	if x != nil {
		return x.ChainID
	}
	return nil
}

func (x *Transaction_Raw) GetKDAFee() *Transaction_KDAFee {
	if x != nil {
		return x.KDAFee
	}
	return nil
}

type Transaction_Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          [][]byte               `protobuf:"bytes,1,rep,name=Data,json=data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Receipt) Reset() {
	*x = Transaction_Receipt{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Receipt) ProtoMessage() {}

func (x *Transaction_Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Receipt.ProtoReflect.Descriptor instead.
func (*Transaction_Receipt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Transaction_Receipt) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x05proto\x1a\x19google/protobuf/any.proto\"\xdf\x06\n" +
	"\n" +
	"TXContract\x122\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1e.proto.TXContract.ContractTypeR\x04type\x122\n" +
	"\tParameter\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\tparameter\"\xe8\x05\n" +
	"\fContractType\x12\x18\n" +
	"\x14TransferContractType\x10\x00\x12\x1b\n" +
	"\x17CreateAssetContractType\x10\x01\x12\x1f\n" +
	"\x1bCreateValidatorContractType\x10\x02\x12\x1f\n" +
	"\x1bValidatorConfigContractType\x10\x03\x12\x16\n" +
	"\x12FreezeContractType\x10\x04\x12\x18\n" +
	"\x14UnfreezeContractType\x10\x05\x12\x18\n" +
	"\x14DelegateContractType\x10\x06\x12\x1a\n" +
	"\x16UndelegateContractType\x10\a\x12\x18\n" +
	"\x14WithdrawContractType\x10\b\x12\x15\n" +
	"\x11ClaimContractType\x10\t\x12\x16\n" +
	"\x12UnjailContractType\x10\n" +
	"\x12\x1c\n" +
	"\x18AssetTriggerContractType\x10\v\x12\x1e\n" +
	"\x1aSetAccountNameContractType\x10\f\x12\x18\n" +
	"\x14ProposalContractType\x10\r\x12\x14\n" +
	"\x10VoteContractType\x10\x0e\x12\x19\n" +
	"\x15ConfigITOContractType\x10\x0f\x12\x1c\n" +
	"\x18SetITOPricesContractType\x10\x10\x12\x13\n" +
	"\x0fBuyContractType\x10\x11\x12\x14\n" +
	"\x10SellContractType\x10\x12\x12!\n" +
	"\x1dCancelMarketOrderContractType\x10\x13\x12!\n" +
	"\x1dCreateMarketplaceContractType\x10\x14\x12!\n" +
	"\x1dConfigMarketplaceContractType\x10\x15\x12'\n" +
	"#UpdateAccountPermissionContractType\x10\x16\x12\x17\n" +
	"\x13DepositContractType\x10\x17\x12\x1a\n" +
	"\x16ITOTriggerContractType\x10\x18\x12\x15\n" +
	"\x11SmartContractType\x10?\"\x91\x12\n" +
	"\vTransaction\x120\n" +
	"\aRawData\x18\x01 \x01(\v2\x16.proto.Transaction.RawR\arawData\x12&\n" +
	"\tSignature\x18\x02 \x03(\fR\x13signature,omitempty\x12=\n" +
	"\x06Result\x18\x03 \x01(\x0e2\x1b.proto.Transaction.TXResultR\x10result,omitempty\x12I\n" +
	"\n" +
	"ResultCode\x18\x04 \x01(\x0e2\x1f.proto.Transaction.TXResultCodeR\x14resultCode,omitempty\x126\n" +
	"\bReceipts\x18\x05 \x03(\v2\x1a.proto.Transaction.ReceiptR\breceipts\x12\x14\n" +
	"\x05Block\x18\x06 \x01(\x04R\x05block\x12\x1a\n" +
	"\bGasLimit\x18\a \x01(\x04R\bgasLimit\x12$\n" +
	"\rGasMultiplier\x18\b \x01(\x04R\rgasMultiplier\x1a2\n" +
	"\x06KDAFee\x12\x10\n" +
	"\x03KDA\x18\x01 \x01(\fR\x03kda\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06amount\x1a\xe7\x02\n" +
	"\x03Raw\x12\x14\n" +
	"\x05Nonce\x18\x01 \x01(\x04R\x05nonce\x12\x16\n" +
	"\x06Sender\x18\x02 \x01(\fR\x06sender\x12-\n" +
	"\bContract\x18\x06 \x03(\v2\x11.proto.TXContractR\bcontract\x12,\n" +
	"\fPermissionID\x18\a \x01(\x05R\x16permissionID,omitempty\x12\x1c\n" +
	"\x04Data\x18\n" +
	" \x03(\fR\x0edata,omitempty\x12\x18\n" +
	"\aKAppFee\x18\r \x01(\x03R\akAppFee\x12\"\n" +
	"\fBandwidthFee\x18\x0e \x01(\x03R\fbandwidthFee\x12\"\n" +
	"\aVersion\x18\x0f \x01(\rR\x11version,omitempty\x12\"\n" +
	"\aChainID\x18\x10 \x01(\fR\x11chainID,omitempty\x121\n" +
	"\x06KDAFee\x18\x11 \x01(\v2\x19.proto.Transaction.KDAFeeR\x06kdaFee\x1a\x1d\n" +
	"\aReceipt\x12\x12\n" +
	"\x04Data\x18\x01 \x03(\fR\x04data\"#\n" +
	"\bTXResult\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"\xab\v\n" +
	"\fTXResultCode\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x0e\n" +
	"\n" +
	"OutOfFunds\x10\x01\x12\x10\n" +
	"\fAccountError\x10\x02\x12\x0e\n" +
	"\n" +
	"AssetError\x10\x03\x12\x13\n" +
	"\x0fContractInvalid\x10\x04\x12\x14\n" +
	"\x10ContractNotFound\x10\x05\x12\x0e\n" +
	"\n" +
	"FeeInvalid\x10\x06\x12\x14\n" +
	"\x10ParameterInvalid\x10\a\x12\x0e\n" +
	"\n" +
	"APRInvalid\x10\b\x12\x12\n" +
	"\x0eAssetIDInvalid\x10\t\x12\x14\n" +
	"\x10AssetTypeInvalid\x10\n" +
	"\x12\x15\n" +
	"\x11AssetCantBeMinted\x10\v\x12\x15\n" +
	"\x11AssetCantBeBurned\x10\f\x12\x15\n" +
	"\x11AssetCantBePaused\x10\r\x12\x18\n" +
	"\x14AssetCantBeDelegated\x10\x0e\x12\x1b\n" +
	"\x17AssetOwnerCantBeChanged\x10\x0f\x12\x13\n" +
	"\x0fAccountNotOwner\x10\x10\x12\x15\n" +
	"\x11CommissionTooHigh\x10\x11\x12\x1b\n" +
	"\x17DelegationAmountInvalid\x10\x12\x12\x15\n" +
	"\x11ProposalNotActive\x10\x13\x12\x10\n" +
	"\fValueInvalid\x10\x14\x12\x11\n" +
	"\rAmountInvalid\x10\x15\x12\x13\n" +
	"\x0fBucketIDInvalid\x10\x16\x12\x0f\n" +
	"\vKeyConflict\x10\x17\x12\x17\n" +
	"\x13MaxDelegationAmount\x10\x18\x12\x12\n" +
	"\x0eInvalidPeerKey\x10\x19\x12\x19\n" +
	"\x15MinKFIStakedUnreached\x10\x1a\x12\x15\n" +
	"\x11MaxSupplyExceeded\x10\x1b\x12\x14\n" +
	"\x10SaveAccountError\x10\x1c\x12\x14\n" +
	"\x10LoadAccountError\x10\x1d\x12\x14\n" +
	"\x10SameAccountError\x10\x1e\x12\x0f\n" +
	"\vAssetPaused\x10\x1f\x12\x13\n" +
	"\x0fDeletegateError\x10 \x12\x18\n" +
	"\x14WithdrawNotAvailable\x10!\x12\x0f\n" +
	"\vErrOverflow\x10\"\x12\x11\n" +
	"\rSetStakingErr\x10#\x12\x15\n" +
	"\x11SetMarketOrderErr\x10$\x12\x10\n" +
	"\fBalanceError\x10%\x12\r\n" +
	"\tKAPPError\x10&\x12\x11\n" +
	"\rUnfreezeError\x10'\x12\x13\n" +
	"\x0fUndelegateError\x10(\x12\x11\n" +
	"\rWithdrawError\x10)\x12\x0e\n" +
	"\n" +
	"ClaimError\x10*\x12\x13\n" +
	"\x0fBucketsExceeded\x10+\x12\x14\n" +
	"\x10AssetCantBeWiped\x10,\x12\x15\n" +
	"\x11AssetCantAddRoles\x10-\x12\x0f\n" +
	"\vFreezeError\x10.\x12\x10\n" +
	"\fITONotActive\x10/\x12\x12\n" +
	"\x0eNFTMintStopped\x100\x12\x1a\n" +
	"\x16RoyaltiesChangeStopped\x101\x12\x10\n" +
	"\fITOKAPPError\x102\x12\x15\n" +
	"\x11ITOWhiteListError\x103\x12\x1c\n" +
	"\x18NFTMetadataChangeStopped\x104\x12\x11\n" +
	"\rAlreadyExists\x105\x12\x18\n" +
	"\x14IteratorLimitReached\x106\x12\x16\n" +
	"\x12VMFunctionNotFound\x107\x12\x1c\n" +
	"\x18VMFunctionWrongSignature\x108\x12\x0f\n" +
	"\vVMUserError\x109\x12\x0e\n" +
	"\n" +
	"VMOutOfGas\x10:\x12\x16\n" +
	"\x12VMAccountCollision\x10;\x12\x17\n" +
	"\x13VMCallStackOverFlow\x10<\x12\x17\n" +
	"\x13VMExecutionPanicked\x10=\x12\x15\n" +
	"\x11VMExecutionFailed\x10>\x12\x13\n" +
	"\x0fVMUpgradeFailed\x10?\x12\x14\n" +
	"\x10VMSimulateFailed\x10@\x12\x19\n" +
	"\x15KDATransferNotAllowed\x10A\x12\x16\n" +
	"\x12TransferRestricted\x10B\x12\b\n" +
	"\x04Fail\x10cB\x10Z\x0e./;transactionb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transaction_proto_goTypes = []any{
	(TXContract_ContractType)(0),  // 0: proto.TXContract.ContractType
	(Transaction_TXResult)(0),     // 1: proto.Transaction.TXResult
	(Transaction_TXResultCode)(0), // 2: proto.Transaction.TXResultCode
	(*TXContract)(nil),            // 3: proto.TXContract
	(*Transaction)(nil),           // 4: proto.Transaction
	(*Transaction_KDAFee)(nil),    // 5: proto.Transaction.KDAFee
	(*Transaction_Raw)(nil),       // 6: proto.Transaction.Raw
	(*Transaction_Receipt)(nil),   // 7: proto.Transaction.Receipt
	(*anypb.Any)(nil),             // 8: google.protobuf.Any
}
var file_transaction_proto_depIdxs = []int32{
	0, // 0: proto.TXContract.Type:type_name -> proto.TXContract.ContractType
	8, // 1: proto.TXContract.Parameter:type_name -> google.protobuf.Any
	6, // 2: proto.Transaction.RawData:type_name -> proto.Transaction.Raw
	1, // 3: proto.Transaction.Result:type_name -> proto.Transaction.TXResult
	2, // 4: proto.Transaction.ResultCode:type_name -> proto.Transaction.TXResultCode
	7, // 5: proto.Transaction.Receipts:type_name -> proto.Transaction.Receipt
	3, // 6: proto.Transaction.Raw.Contract:type_name -> proto.TXContract
	5, // 7: proto.Transaction.Raw.KDAFee:type_name -> proto.Transaction.KDAFee
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
