---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: blockchain
  name: blockchain
  namespace: klever-go
spec:
  template:
    spec:
      containers:
        - name: validator
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        - name: seed-node
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
