// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authMessage.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMessagePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessagePb) Reset() {
	*x = AuthMessagePb{}
	mi := &file_authMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessagePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessagePb) ProtoMessage() {}

func (x *AuthMessagePb) ProtoReflect() protoreflect.Message {
	mi := &file_authMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessagePb.ProtoReflect.Descriptor instead.
func (*AuthMessagePb) Descriptor() ([]byte, []int) {
	return file_authMessage_proto_rawDescGZIP(), []int{0}
}

func (x *AuthMessagePb) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AuthMessagePb) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *AuthMessagePb) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *AuthMessagePb) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_authMessage_proto protoreflect.FileDescriptor

const file_authMessage_proto_rawDesc = "" +
	"\n" +
	"\x11authMessage.proto\x12\x05proto\"q\n" +
	"\rAuthMessagePb\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\fR\aMessage\x12\x10\n" +
	"\x03Sig\x18\x02 \x01(\fR\x03Sig\x12\x16\n" +
	"\x06Pubkey\x18\x03 \x01(\fR\x06Pubkey\x12\x1c\n" +
	"\tTimestamp\x18\x04 \x01(\x03R\tTimestampB\tZ\a./;datab\x06proto3"

var (
	file_authMessage_proto_rawDescOnce sync.Once
	file_authMessage_proto_rawDescData []byte
)

func file_authMessage_proto_rawDescGZIP() []byte {
	file_authMessage_proto_rawDescOnce.Do(func() {
		file_authMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authMessage_proto_rawDesc), len(file_authMessage_proto_rawDesc)))
	})
	return file_authMessage_proto_rawDescData
}

var file_authMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authMessage_proto_goTypes = []any{
	(*AuthMessagePb)(nil), // 0: proto.AuthMessagePb
}
var file_authMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authMessage_proto_init() }
func file_authMessage_proto_init() {
	if File_authMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authMessage_proto_rawDesc), len(file_authMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authMessage_proto_goTypes,
		DependencyIndexes: file_authMessage_proto_depIdxs,
		MessageInfos:      file_authMessage_proto_msgTypes,
	}.Build()
	File_authMessage_proto = out.File
	file_authMessage_proto_goTypes = nil
	file_authMessage_proto_depIdxs = nil
}
