// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.27.0
// source: authMessage.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMessagePb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   []byte `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Sig       []byte `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Pubkey    []byte `protobuf:"bytes,3,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *AuthMessagePb) Reset() {
	*x = AuthMessagePb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthMessagePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessagePb) ProtoMessage() {}

func (x *AuthMessagePb) ProtoReflect() protoreflect.Message {
	mi := &file_authMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessagePb.ProtoReflect.Descriptor instead.
func (*AuthMessagePb) Descriptor() ([]byte, []int) {
	return file_authMessage_proto_rawDescGZIP(), []int{0}
}

func (x *AuthMessagePb) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AuthMessagePb) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *AuthMessagePb) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *AuthMessagePb) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_authMessage_proto protoreflect.FileDescriptor

var file_authMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0d, 0x41, 0x75,
	0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authMessage_proto_rawDescOnce sync.Once
	file_authMessage_proto_rawDescData = file_authMessage_proto_rawDesc
)

func file_authMessage_proto_rawDescGZIP() []byte {
	file_authMessage_proto_rawDescOnce.Do(func() {
		file_authMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_authMessage_proto_rawDescData)
	})
	return file_authMessage_proto_rawDescData
}

var file_authMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authMessage_proto_goTypes = []interface{}{
	(*AuthMessagePb)(nil), // 0: proto.AuthMessagePb
}
var file_authMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authMessage_proto_init() }
func file_authMessage_proto_init() {
	if File_authMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthMessagePb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authMessage_proto_goTypes,
		DependencyIndexes: file_authMessage_proto_depIdxs,
		MessageInfos:      file_authMessage_proto_msgTypes,
	}.Build()
	File_authMessage_proto = out.File
	file_authMessage_proto_rawDesc = nil
	file_authMessage_proto_goTypes = nil
	file_authMessage_proto_depIdxs = nil
}
