// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: topicMessage.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        uint32                 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Pk             []byte                 `protobuf:"bytes,4,opt,name=Pk,proto3" json:"Pk,omitempty"`
	SignatureOnPid []byte                 `protobuf:"bytes,5,opt,name=SignatureOnPid,proto3" json:"SignatureOnPid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	mi := &file_topicMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_topicMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_topicMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TopicMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TopicMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TopicMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TopicMessage) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *TopicMessage) GetSignatureOnPid() []byte {
	if x != nil {
		return x.SignatureOnPid
	}
	return nil
}

var File_topicMessage_proto protoreflect.FileDescriptor

const file_topicMessage_proto_rawDesc = "" +
	"\n" +
	"\x12topicMessage.proto\x12\x05proto\"\x98\x01\n" +
	"\fTopicMessage\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\rR\aVersion\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\aPayload\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x03R\tTimestamp\x12\x0e\n" +
	"\x02Pk\x18\x04 \x01(\fR\x02Pk\x12&\n" +
	"\x0eSignatureOnPid\x18\x05 \x01(\fR\x0eSignatureOnPidB\tZ\a./;datab\x06proto3"

var (
	file_topicMessage_proto_rawDescOnce sync.Once
	file_topicMessage_proto_rawDescData []byte
)

func file_topicMessage_proto_rawDescGZIP() []byte {
	file_topicMessage_proto_rawDescOnce.Do(func() {
		file_topicMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topicMessage_proto_rawDesc), len(file_topicMessage_proto_rawDesc)))
	})
	return file_topicMessage_proto_rawDescData
}

var file_topicMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topicMessage_proto_goTypes = []any{
	(*TopicMessage)(nil), // 0: proto.TopicMessage
}
var file_topicMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_topicMessage_proto_init() }
func file_topicMessage_proto_init() {
	if File_topicMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topicMessage_proto_rawDesc), len(file_topicMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topicMessage_proto_goTypes,
		DependencyIndexes: file_topicMessage_proto_depIdxs,
		MessageInfos:      file_topicMessage_proto_msgTypes,
	}.Build()
	File_topicMessage_proto = out.File
	file_topicMessage_proto_goTypes = nil
	file_topicMessage_proto_depIdxs = nil
}
