// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: requestData.proto

package retriever

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestDataType represents the data type for the requested data
type RequestDataType int32

const (
	// Invalid
	RequestDataType_InvalidType RequestDataType = 0
	// HashType indicates that the request data object is of type hash
	RequestDataType_HashType RequestDataType = 1
	// HashArrayType that the request data object contains a serialised array of hashes
	RequestDataType_HashArrayType RequestDataType = 2
	// NonceType indicates that the request data object is of type nonce (uint64)
	RequestDataType_NonceType RequestDataType = 3
	// EpochType indicates that the request data object is of type epoch
	RequestDataType_EpochType RequestDataType = 4
)

// Enum value maps for RequestDataType.
var (
	RequestDataType_name = map[int32]string{
		0: "InvalidType",
		1: "HashType",
		2: "HashArrayType",
		3: "NonceType",
		4: "EpochType",
	}
	RequestDataType_value = map[string]int32{
		"InvalidType":   0,
		"HashType":      1,
		"HashArrayType": 2,
		"NonceType":     3,
		"EpochType":     4,
	}
)

func (x RequestDataType) Enum() *RequestDataType {
	p := new(RequestDataType)
	*p = x
	return p
}

func (x RequestDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_requestData_proto_enumTypes[0].Descriptor()
}

func (RequestDataType) Type() protoreflect.EnumType {
	return &file_requestData_proto_enumTypes[0]
}

func (x RequestDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestDataType.Descriptor instead.
func (RequestDataType) EnumDescriptor() ([]byte, []int) {
	return file_requestData_proto_rawDescGZIP(), []int{0}
}

// RequestData holds the requested data
// This struct will be serialized and sent to the other peers
type RequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Type          RequestDataType        `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=proto.RequestDataType" json:"Type,omitempty"`
	Epoch         uint32                 `protobuf:"varint,3,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_requestData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_requestData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_requestData_proto_rawDescGZIP(), []int{0}
}

func (x *RequestData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RequestData) GetType() RequestDataType {
	if x != nil {
		return x.Type
	}
	return RequestDataType_InvalidType
}

func (x *RequestData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_requestData_proto protoreflect.FileDescriptor

const file_requestData_proto_rawDesc = "" +
	"\n" +
	"\x11requestData.proto\x12\x05proto\"e\n" +
	"\vRequestData\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\fR\x05value\x12*\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x16.proto.RequestDataTypeR\x04type\x12\x14\n" +
	"\x05Epoch\x18\x03 \x01(\rR\x05epoch*a\n" +
	"\x0fRequestDataType\x12\x0f\n" +
	"\vInvalidType\x10\x00\x12\f\n" +
	"\bHashType\x10\x01\x12\x11\n" +
	"\rHashArrayType\x10\x02\x12\r\n" +
	"\tNonceType\x10\x03\x12\r\n" +
	"\tEpochType\x10\x04B\x0eZ\f./;retrieverb\x06proto3"

var (
	file_requestData_proto_rawDescOnce sync.Once
	file_requestData_proto_rawDescData []byte
)

func file_requestData_proto_rawDescGZIP() []byte {
	file_requestData_proto_rawDescOnce.Do(func() {
		file_requestData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requestData_proto_rawDesc), len(file_requestData_proto_rawDesc)))
	})
	return file_requestData_proto_rawDescData
}

var file_requestData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_requestData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_requestData_proto_goTypes = []any{
	(RequestDataType)(0), // 0: proto.RequestDataType
	(*RequestData)(nil),  // 1: proto.RequestData
}
var file_requestData_proto_depIdxs = []int32{
	0, // 0: proto.RequestData.Type:type_name -> proto.RequestDataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_requestData_proto_init() }
func file_requestData_proto_init() {
	if File_requestData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requestData_proto_rawDesc), len(file_requestData_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_requestData_proto_goTypes,
		DependencyIndexes: file_requestData_proto_depIdxs,
		EnumInfos:         file_requestData_proto_enumTypes,
		MessageInfos:      file_requestData_proto_msgTypes,
	}.Build()
	File_requestData_proto = out.File
	file_requestData_proto_goTypes = nil
	file_requestData_proto_depIdxs = nil
}
