// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: block.proto

package block

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TxBlock   Type = 0
	Type_PeerBlock Type = 10
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TxBlock",
		10: "PeerBlock",
	}
	Type_value = map[string]int32{
		"TxBlock":   0,
		"PeerBlock": 10,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_block_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_block_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

// Epoch hold the last finalized headers hash and state root hash
type Epoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	ParentHash    []byte                 `protobuf:"bytes,2,opt,name=ParentHash,json=parentHash,proto3" json:"ParentHash,omitempty"`
	TrieRoot      []byte                 `protobuf:"bytes,3,opt,name=TrieRoot,json=trieRoot,proto3" json:"TrieRoot,omitempty"`
	Block         uint64                 `protobuf:"varint,4,opt,name=Block,json=block,proto3" json:"Block,omitempty"`
	Reserved      []byte                 `protobuf:"bytes,10,opt,name=Reserved,json=-,proto3" json:"Reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Epoch) Reset() {
	*x = Epoch{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epoch) ProtoMessage() {}

func (x *Epoch) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epoch.ProtoReflect.Descriptor instead.
func (*Epoch) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *Epoch) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Epoch) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Epoch) GetTrieRoot() []byte {
	if x != nil {
		return x.TrieRoot
	}
	return nil
}

func (x *Epoch) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *Epoch) GetReserved() []byte {
	if x != nil {
		return x.Reserved
	}
	return nil
}

// BlockHeader holds the metadata of a block. This is the part that is being hashed and run through consensus.
// The header holds the hash of the body and also the link to the previous block header hash
type BlockHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nonce              uint64                 `protobuf:"varint,1,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	ParentHash         []byte                 `protobuf:"bytes,2,opt,name=ParentHash,json=parentHash,proto3" json:"ParentHash,omitempty"`
	Timestamp          int64                  `protobuf:"varint,3,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Slot               uint64                 `protobuf:"varint,4,opt,name=Slot,json=slot,proto3" json:"Slot,omitempty"`
	Epoch              uint32                 `protobuf:"varint,5,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	IsEpochStart       bool                   `protobuf:"varint,6,opt,name=IsEpochStart,json=isEpochStart,proto3" json:"IsEpochStart,omitempty"`
	PrevEpochStartSlot uint64                 `protobuf:"varint,7,opt,name=PrevEpochStartSlot,json=prevEpochStartSlot,proto3" json:"PrevEpochStartSlot,omitempty"`
	TxRootHash         []byte                 `protobuf:"bytes,8,opt,name=TxRootHash,json=txRootHash,proto3" json:"TxRootHash,omitempty"`
	TrieRoot           []byte                 `protobuf:"bytes,9,opt,name=TrieRoot,json=trieRoot,proto3" json:"TrieRoot,omitempty"`
	ValidatorsTrieRoot []byte                 `protobuf:"bytes,10,opt,name=ValidatorsTrieRoot,json=validatorsTrieRoot,proto3" json:"ValidatorsTrieRoot,omitempty"`
	KAppsTrieRoot      []byte                 `protobuf:"bytes,11,opt,name=KAppsTrieRoot,json=kappsTrieRoot,proto3" json:"KAppsTrieRoot,omitempty"`
	PrevRandSeed       []byte                 `protobuf:"bytes,13,opt,name=PrevRandSeed,json=prevRandSeed,omitempty,proto3" json:"PrevRandSeed,omitempty"`
	RandSeed           []byte                 `protobuf:"bytes,14,opt,name=RandSeed,json=randSeed,omitempty,proto3" json:"RandSeed,omitempty"`
	TxCount            uint32                 `protobuf:"varint,15,opt,name=TxCount,json=txCount,omitempty,proto3" json:"TxCount,omitempty"`
	TxFees             int64                  `protobuf:"varint,16,opt,name=TxFees,json=txFees,omitempty,proto3" json:"TxFees,omitempty"`
	TxBurnedFees       int64                  `protobuf:"varint,17,opt,name=TxBurnedFees,json=txBurnedFees,omitempty,proto3" json:"TxBurnedFees,omitempty"`
	KAppFees           int64                  `protobuf:"varint,18,opt,name=KAppFees,json=kAppFees,omitempty,proto3" json:"KAppFees,omitempty"`
	BlockRewards       int64                  `protobuf:"varint,19,opt,name=BlockRewards,json=blockRewards,omitempty,proto3" json:"BlockRewards,omitempty"`
	StakingRewards     int64                  `protobuf:"varint,20,opt,name=StakingRewards,json=stakingRewards,omitempty,proto3" json:"StakingRewards,omitempty"`
	SoftwareVersion    []byte                 `protobuf:"bytes,21,opt,name=SoftwareVersion,json=softwareVersion,omitempty,proto3" json:"SoftwareVersion,omitempty"`
	ChainID            []byte                 `protobuf:"bytes,22,opt,name=ChainID,json=chainID,omitempty,proto3" json:"ChainID,omitempty"`
	BurnedUnclaimed    int64                  `protobuf:"varint,23,opt,name=BurnedUnclaimed,json=burnedUnclaimed,omitempty,proto3" json:"BurnedUnclaimed,omitempty"`
	Reserved           []byte                 `protobuf:"bytes,30,opt,name=Reserved,json=-,proto3" json:"Reserved,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockHeader) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BlockHeader) GetIsEpochStart() bool {
	if x != nil {
		return x.IsEpochStart
	}
	return false
}

func (x *BlockHeader) GetPrevEpochStartSlot() uint64 {
	if x != nil {
		return x.PrevEpochStartSlot
	}
	return 0
}

func (x *BlockHeader) GetTxRootHash() []byte {
	if x != nil {
		return x.TxRootHash
	}
	return nil
}

func (x *BlockHeader) GetTrieRoot() []byte {
	if x != nil {
		return x.TrieRoot
	}
	return nil
}

func (x *BlockHeader) GetValidatorsTrieRoot() []byte {
	if x != nil {
		return x.ValidatorsTrieRoot
	}
	return nil
}

func (x *BlockHeader) GetKAppsTrieRoot() []byte {
	if x != nil {
		return x.KAppsTrieRoot
	}
	return nil
}

func (x *BlockHeader) GetPrevRandSeed() []byte {
	if x != nil {
		return x.PrevRandSeed
	}
	return nil
}

func (x *BlockHeader) GetRandSeed() []byte {
	if x != nil {
		return x.RandSeed
	}
	return nil
}

func (x *BlockHeader) GetTxCount() uint32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockHeader) GetTxFees() int64 {
	if x != nil {
		return x.TxFees
	}
	return 0
}

func (x *BlockHeader) GetTxBurnedFees() int64 {
	if x != nil {
		return x.TxBurnedFees
	}
	return 0
}

func (x *BlockHeader) GetKAppFees() int64 {
	if x != nil {
		return x.KAppFees
	}
	return 0
}

func (x *BlockHeader) GetBlockRewards() int64 {
	if x != nil {
		return x.BlockRewards
	}
	return 0
}

func (x *BlockHeader) GetStakingRewards() int64 {
	if x != nil {
		return x.StakingRewards
	}
	return 0
}

func (x *BlockHeader) GetSoftwareVersion() []byte {
	if x != nil {
		return x.SoftwareVersion
	}
	return nil
}

func (x *BlockHeader) GetChainID() []byte {
	if x != nil {
		return x.ChainID
	}
	return nil
}

func (x *BlockHeader) GetBurnedUnclaimed() int64 {
	if x != nil {
		return x.BurnedUnclaimed
	}
	return 0
}

func (x *BlockHeader) GetReserved() []byte {
	if x != nil {
		return x.Reserved
	}
	return nil
}

// Block holds all block info
type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *BlockHeader           `protobuf:"bytes,1,opt,name=Header,json=blockHeader,proto3" json:"Header,omitempty"`
	TxHashes          [][]byte               `protobuf:"bytes,2,rep,name=TxHashes,json=txHashes,proto3" json:"TxHashes,omitempty"`
	ProducerSignature []byte                 `protobuf:"bytes,3,opt,name=ProducerSignature,json=producerSignature,proto3" json:"ProducerSignature,omitempty"`
	PubKeysBitmap     []byte                 `protobuf:"bytes,4,opt,name=PubKeysBitmap,json=pubKeysBitmap,proto3" json:"PubKeysBitmap,omitempty"`
	Signature         []byte                 `protobuf:"bytes,5,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	TxResults         []uint32               `protobuf:"varint,6,rep,packed,name=TxResults,json=txResults,omitempty,proto3" json:"TxResults,omitempty"` // Transaction execution result codes for timeout validation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTxHashes() [][]byte {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

func (x *Block) GetProducerSignature() []byte {
	if x != nil {
		return x.ProducerSignature
	}
	return nil
}

func (x *Block) GetPubKeysBitmap() []byte {
	if x != nil {
		return x.PubKeysBitmap
	}
	return nil
}

func (x *Block) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Block) GetTxResults() []uint32 {
	if x != nil {
		return x.TxResults
	}
	return nil
}

type EValidatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=List,json=list,proto3" json:"List,omitempty"`
	Index         uint32                 `protobuf:"varint,4,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	TempRating    uint32                 `protobuf:"varint,5,opt,name=TempRating,json=tempRating,proto3" json:"TempRating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EValidatorInfo) Reset() {
	*x = EValidatorInfo{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EValidatorInfo) ProtoMessage() {}

func (x *EValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EValidatorInfo.ProtoReflect.Descriptor instead.
func (*EValidatorInfo) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *EValidatorInfo) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *EValidatorInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EValidatorInfo) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *EValidatorInfo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EValidatorInfo) GetTempRating() uint32 {
	if x != nil {
		return x.TempRating
	}
	return 0
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x05proto\"\x84\x01\n" +
	"\x05Epoch\x12\x14\n" +
	"\x05Epoch\x18\x01 \x01(\rR\x05epoch\x12\x1e\n" +
	"\n" +
	"ParentHash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1a\n" +
	"\bTrieRoot\x18\x03 \x01(\fR\btrieRoot\x12\x14\n" +
	"\x05Block\x18\x04 \x01(\x04R\x05block\x12\x13\n" +
	"\bReserved\x18\n" +
	" \x01(\fR\x01-\"\xe0\x06\n" +
	"\vBlockHeader\x12\x14\n" +
	"\x05Nonce\x18\x01 \x01(\x04R\x05nonce\x12\x1e\n" +
	"\n" +
	"ParentHash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04Slot\x18\x04 \x01(\x04R\x04slot\x12\x14\n" +
	"\x05Epoch\x18\x05 \x01(\rR\x05epoch\x12\"\n" +
	"\fIsEpochStart\x18\x06 \x01(\bR\fisEpochStart\x12.\n" +
	"\x12PrevEpochStartSlot\x18\a \x01(\x04R\x12prevEpochStartSlot\x12\x1e\n" +
	"\n" +
	"TxRootHash\x18\b \x01(\fR\n" +
	"txRootHash\x12\x1a\n" +
	"\bTrieRoot\x18\t \x01(\fR\btrieRoot\x12.\n" +
	"\x12ValidatorsTrieRoot\x18\n" +
	" \x01(\fR\x12validatorsTrieRoot\x12$\n" +
	"\rKAppsTrieRoot\x18\v \x01(\fR\rkappsTrieRoot\x12,\n" +
	"\fPrevRandSeed\x18\r \x01(\fR\x16prevRandSeed,omitempty\x12$\n" +
	"\bRandSeed\x18\x0e \x01(\fR\x12randSeed,omitempty\x12\"\n" +
	"\aTxCount\x18\x0f \x01(\rR\x11txCount,omitempty\x12 \n" +
	"\x06TxFees\x18\x10 \x01(\x03R\x10txFees,omitempty\x12,\n" +
	"\fTxBurnedFees\x18\x11 \x01(\x03R\x16txBurnedFees,omitempty\x12$\n" +
	"\bKAppFees\x18\x12 \x01(\x03R\x12kAppFees,omitempty\x12,\n" +
	"\fBlockRewards\x18\x13 \x01(\x03R\x16blockRewards,omitempty\x120\n" +
	"\x0eStakingRewards\x18\x14 \x01(\x03R\x18stakingRewards,omitempty\x122\n" +
	"\x0fSoftwareVersion\x18\x15 \x01(\fR\x19softwareVersion,omitempty\x12\"\n" +
	"\aChainID\x18\x16 \x01(\fR\x11chainID,omitempty\x122\n" +
	"\x0fBurnedUnclaimed\x18\x17 \x01(\x03R\x19burnedUnclaimed,omitempty\x12\x13\n" +
	"\bReserved\x18\x1e \x01(\fR\x01-\"\xee\x01\n" +
	"\x05Block\x12/\n" +
	"\x06Header\x18\x01 \x01(\v2\x12.proto.BlockHeaderR\vblockHeader\x12\x1a\n" +
	"\bTxHashes\x18\x02 \x03(\fR\btxHashes\x12,\n" +
	"\x11ProducerSignature\x18\x03 \x01(\fR\x11producerSignature\x12$\n" +
	"\rPubKeysBitmap\x18\x04 \x01(\fR\rpubKeysBitmap\x12\x1c\n" +
	"\tSignature\x18\x05 \x01(\fR\tsignature\x12&\n" +
	"\tTxResults\x18\x06 \x03(\rR\x13txResults,omitempty\"\x9c\x01\n" +
	"\x0eEValidatorInfo\x12\"\n" +
	"\fOwnerAddress\x18\x01 \x01(\fR\fownerAddress\x12\x1c\n" +
	"\tPublicKey\x18\x02 \x01(\fR\tpublicKey\x12\x12\n" +
	"\x04List\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05Index\x18\x04 \x01(\rR\x05index\x12\x1e\n" +
	"\n" +
	"TempRating\x18\x05 \x01(\rR\n" +
	"tempRating*\"\n" +
	"\x04Type\x12\v\n" +
	"\aTxBlock\x10\x00\x12\r\n" +
	"\tPeerBlock\x10\n" +
	"B\n" +
	"Z\b./;blockb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_block_proto_goTypes = []any{
	(Type)(0),              // 0: proto.Type
	(*Epoch)(nil),          // 1: proto.Epoch
	(*BlockHeader)(nil),    // 2: proto.BlockHeader
	(*Block)(nil),          // 3: proto.Block
	(*EValidatorInfo)(nil), // 4: proto.EValidatorInfo
}
var file_block_proto_depIdxs = []int32{
	2, // 0: proto.Block.Header:type_name -> proto.BlockHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		EnumInfos:         file_block_proto_enumTypes,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
