// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: node.proto

package trie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollapsedBn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EncodedChildren [][]byte               `protobuf:"bytes,1,rep,name=EncodedChildren,proto3" json:"EncodedChildren,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollapsedBn) Reset() {
	*x = CollapsedBn{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollapsedBn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollapsedBn) ProtoMessage() {}

func (x *CollapsedBn) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollapsedBn.ProtoReflect.Descriptor instead.
func (*CollapsedBn) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *CollapsedBn) GetEncodedChildren() [][]byte {
	if x != nil {
		return x.EncodedChildren
	}
	return nil
}

type CollapsedEn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	EncodedChild  []byte                 `protobuf:"bytes,2,opt,name=EncodedChild,proto3" json:"EncodedChild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollapsedEn) Reset() {
	*x = CollapsedEn{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollapsedEn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollapsedEn) ProtoMessage() {}

func (x *CollapsedEn) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollapsedEn.ProtoReflect.Descriptor instead.
func (*CollapsedEn) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *CollapsedEn) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CollapsedEn) GetEncodedChild() []byte {
	if x != nil {
		return x.EncodedChild
	}
	return nil
}

type CollapsedLn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollapsedLn) Reset() {
	*x = CollapsedLn{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollapsedLn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollapsedLn) ProtoMessage() {}

func (x *CollapsedLn) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollapsedLn.ProtoReflect.Descriptor instead.
func (*CollapsedLn) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *CollapsedLn) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CollapsedLn) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x05proto\"7\n" +
	"\vCollapsedBn\x12(\n" +
	"\x0fEncodedChildren\x18\x01 \x03(\fR\x0fEncodedChildren\"C\n" +
	"\vCollapsedEn\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\fR\x03Key\x12\"\n" +
	"\fEncodedChild\x18\x02 \x01(\fR\fEncodedChild\"5\n" +
	"\vCollapsedLn\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\fR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\fR\x05ValueB\tZ\a./;trieb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_proto_goTypes = []any{
	(*CollapsedBn)(nil), // 0: proto.CollapsedBn
	(*CollapsedEn)(nil), // 1: proto.CollapsedEn
	(*CollapsedLn)(nil), // 2: proto.CollapsedLn
}
var file_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
