// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: kdaFeesPoolData.proto

package kdafeespool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KDAFeesPoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress  []byte `protobuf:"bytes,1,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	KDA           []byte `protobuf:"bytes,2,opt,name=KDA,json=kda,proto3" json:"KDA,omitempty"`
	Active        bool   `protobuf:"varint,3,opt,name=Active,json=active,proto3" json:"Active,omitempty"`
	KLVBalance    int64  `protobuf:"varint,4,opt,name=KLVBalance,json=klvBalance,proto3" json:"KLVBalance,omitempty"`
	KDABalance    int64  `protobuf:"varint,5,opt,name=KDABalance,json=kdaBalance,proto3" json:"KDABalance,omitempty"`
	ConvertedFees int64  `protobuf:"varint,6,opt,name=ConvertedFees,json=convertedFees,proto3" json:"ConvertedFees,omitempty"`
	AdminAddress  []byte `protobuf:"bytes,7,opt,name=AdminAddress,json=adminAddress,proto3" json:"AdminAddress,omitempty"`
	FRatioKDA     int64  `protobuf:"varint,8,opt,name=FRatioKDA,json=fRatioKDA,proto3" json:"FRatioKDA,omitempty"`
	FRatioKLV     int64  `protobuf:"varint,9,opt,name=FRatioKLV,json=fRatioKLV,proto3" json:"FRatioKLV,omitempty"`
}

func (x *KDAFeesPoolData) Reset() {
	*x = KDAFeesPoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdaFeesPoolData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KDAFeesPoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDAFeesPoolData) ProtoMessage() {}

func (x *KDAFeesPoolData) ProtoReflect() protoreflect.Message {
	mi := &file_kdaFeesPoolData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDAFeesPoolData.ProtoReflect.Descriptor instead.
func (*KDAFeesPoolData) Descriptor() ([]byte, []int) {
	return file_kdaFeesPoolData_proto_rawDescGZIP(), []int{0}
}

func (x *KDAFeesPoolData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *KDAFeesPoolData) GetKDA() []byte {
	if x != nil {
		return x.KDA
	}
	return nil
}

func (x *KDAFeesPoolData) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *KDAFeesPoolData) GetKLVBalance() int64 {
	if x != nil {
		return x.KLVBalance
	}
	return 0
}

func (x *KDAFeesPoolData) GetKDABalance() int64 {
	if x != nil {
		return x.KDABalance
	}
	return 0
}

func (x *KDAFeesPoolData) GetConvertedFees() int64 {
	if x != nil {
		return x.ConvertedFees
	}
	return 0
}

func (x *KDAFeesPoolData) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *KDAFeesPoolData) GetFRatioKDA() int64 {
	if x != nil {
		return x.FRatioKDA
	}
	return 0
}

func (x *KDAFeesPoolData) GetFRatioKLV() int64 {
	if x != nil {
		return x.FRatioKLV
	}
	return 0
}

var File_kdaFeesPoolData_proto protoreflect.FileDescriptor

var file_kdaFeesPoolData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6b, 0x64, 0x61, 0x46, 0x65, 0x65, 0x73, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5,
	0x02, 0x0a, 0x0f, 0x4b, 0x44, 0x41, 0x46, 0x65, 0x65, 0x73, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x44, 0x41, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x4b, 0x4c, 0x56, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6b, 0x6c, 0x76, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x4b, 0x44, 0x41, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6b, 0x64, 0x61, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x46, 0x65, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x65, 0x64, 0x46, 0x65, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x52,
	0x61, 0x74, 0x69, 0x6f, 0x4b, 0x44, 0x41, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x4b, 0x44, 0x41, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x52, 0x61, 0x74,
	0x69, 0x6f, 0x4b, 0x4c, 0x56, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x52, 0x61,
	0x74, 0x69, 0x6f, 0x4b, 0x4c, 0x56, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x6b, 0x64, 0x61,
	0x66, 0x65, 0x65, 0x73, 0x70, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kdaFeesPoolData_proto_rawDescOnce sync.Once
	file_kdaFeesPoolData_proto_rawDescData = file_kdaFeesPoolData_proto_rawDesc
)

func file_kdaFeesPoolData_proto_rawDescGZIP() []byte {
	file_kdaFeesPoolData_proto_rawDescOnce.Do(func() {
		file_kdaFeesPoolData_proto_rawDescData = protoimpl.X.CompressGZIP(file_kdaFeesPoolData_proto_rawDescData)
	})
	return file_kdaFeesPoolData_proto_rawDescData
}

var file_kdaFeesPoolData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kdaFeesPoolData_proto_goTypes = []interface{}{
	(*KDAFeesPoolData)(nil), // 0: proto.KDAFeesPoolData
}
var file_kdaFeesPoolData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kdaFeesPoolData_proto_init() }
func file_kdaFeesPoolData_proto_init() {
	if File_kdaFeesPoolData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kdaFeesPoolData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KDAFeesPoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kdaFeesPoolData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kdaFeesPoolData_proto_goTypes,
		DependencyIndexes: file_kdaFeesPoolData_proto_depIdxs,
		MessageInfos:      file_kdaFeesPoolData_proto_msgTypes,
	}.Build()
	File_kdaFeesPoolData_proto = out.File
	file_kdaFeesPoolData_proto_rawDesc = nil
	file_kdaFeesPoolData_proto_goTypes = nil
	file_kdaFeesPoolData_proto_depIdxs = nil
}
