// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kdaFeesPoolData.proto

package kdafeespool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KDAFeesPoolData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	KDA           []byte                 `protobuf:"bytes,2,opt,name=KDA,json=kda,proto3" json:"KDA,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=Active,json=active,proto3" json:"Active,omitempty"`
	KLVBalance    int64                  `protobuf:"varint,4,opt,name=KLVBalance,json=klvBalance,proto3" json:"KLVBalance,omitempty"`
	KDABalance    int64                  `protobuf:"varint,5,opt,name=KDABalance,json=kdaBalance,proto3" json:"KDABalance,omitempty"`
	ConvertedFees int64                  `protobuf:"varint,6,opt,name=ConvertedFees,json=convertedFees,proto3" json:"ConvertedFees,omitempty"`
	AdminAddress  []byte                 `protobuf:"bytes,7,opt,name=AdminAddress,json=adminAddress,proto3" json:"AdminAddress,omitempty"`
	FRatioKDA     int64                  `protobuf:"varint,8,opt,name=FRatioKDA,json=fRatioKDA,proto3" json:"FRatioKDA,omitempty"`
	FRatioKLV     int64                  `protobuf:"varint,9,opt,name=FRatioKLV,json=fRatioKLV,proto3" json:"FRatioKLV,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KDAFeesPoolData) Reset() {
	*x = KDAFeesPoolData{}
	mi := &file_kdaFeesPoolData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KDAFeesPoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDAFeesPoolData) ProtoMessage() {}

func (x *KDAFeesPoolData) ProtoReflect() protoreflect.Message {
	mi := &file_kdaFeesPoolData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDAFeesPoolData.ProtoReflect.Descriptor instead.
func (*KDAFeesPoolData) Descriptor() ([]byte, []int) {
	return file_kdaFeesPoolData_proto_rawDescGZIP(), []int{0}
}

func (x *KDAFeesPoolData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *KDAFeesPoolData) GetKDA() []byte {
	if x != nil {
		return x.KDA
	}
	return nil
}

func (x *KDAFeesPoolData) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *KDAFeesPoolData) GetKLVBalance() int64 {
	if x != nil {
		return x.KLVBalance
	}
	return 0
}

func (x *KDAFeesPoolData) GetKDABalance() int64 {
	if x != nil {
		return x.KDABalance
	}
	return 0
}

func (x *KDAFeesPoolData) GetConvertedFees() int64 {
	if x != nil {
		return x.ConvertedFees
	}
	return 0
}

func (x *KDAFeesPoolData) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *KDAFeesPoolData) GetFRatioKDA() int64 {
	if x != nil {
		return x.FRatioKDA
	}
	return 0
}

func (x *KDAFeesPoolData) GetFRatioKLV() int64 {
	if x != nil {
		return x.FRatioKLV
	}
	return 0
}

var File_kdaFeesPoolData_proto protoreflect.FileDescriptor

const file_kdaFeesPoolData_proto_rawDesc = "" +
	"\n" +
	"\x15kdaFeesPoolData.proto\x12\x05proto\"\xa5\x02\n" +
	"\x0fKDAFeesPoolData\x12\"\n" +
	"\fOwnerAddress\x18\x01 \x01(\fR\fownerAddress\x12\x10\n" +
	"\x03KDA\x18\x02 \x01(\fR\x03kda\x12\x16\n" +
	"\x06Active\x18\x03 \x01(\bR\x06active\x12\x1e\n" +
	"\n" +
	"KLVBalance\x18\x04 \x01(\x03R\n" +
	"klvBalance\x12\x1e\n" +
	"\n" +
	"KDABalance\x18\x05 \x01(\x03R\n" +
	"kdaBalance\x12$\n" +
	"\rConvertedFees\x18\x06 \x01(\x03R\rconvertedFees\x12\"\n" +
	"\fAdminAddress\x18\a \x01(\fR\fadminAddress\x12\x1c\n" +
	"\tFRatioKDA\x18\b \x01(\x03R\tfRatioKDA\x12\x1c\n" +
	"\tFRatioKLV\x18\t \x01(\x03R\tfRatioKLVB\x10Z\x0e./;kdafeespoolb\x06proto3"

var (
	file_kdaFeesPoolData_proto_rawDescOnce sync.Once
	file_kdaFeesPoolData_proto_rawDescData []byte
)

func file_kdaFeesPoolData_proto_rawDescGZIP() []byte {
	file_kdaFeesPoolData_proto_rawDescOnce.Do(func() {
		file_kdaFeesPoolData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kdaFeesPoolData_proto_rawDesc), len(file_kdaFeesPoolData_proto_rawDesc)))
	})
	return file_kdaFeesPoolData_proto_rawDescData
}

var file_kdaFeesPoolData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kdaFeesPoolData_proto_goTypes = []any{
	(*KDAFeesPoolData)(nil), // 0: proto.KDAFeesPoolData
}
var file_kdaFeesPoolData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kdaFeesPoolData_proto_init() }
func file_kdaFeesPoolData_proto_init() {
	if File_kdaFeesPoolData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kdaFeesPoolData_proto_rawDesc), len(file_kdaFeesPoolData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kdaFeesPoolData_proto_goTypes,
		DependencyIndexes: file_kdaFeesPoolData_proto_depIdxs,
		MessageInfos:      file_kdaFeesPoolData_proto_msgTypes,
	}.Build()
	File_kdaFeesPoolData_proto = out.File
	file_kdaFeesPoolData_proto_goTypes = nil
	file_kdaFeesPoolData_proto_depIdxs = nil
}
