// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.27.0
// source: ito.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ITOData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsActive               bool                 `protobuf:"varint,1,opt,name=IsActive,json=isActive,proto3" json:"IsActive,omitempty"`
	MaxAmount              int64                `protobuf:"varint,2,opt,name=MaxAmount,json=maxAmount,proto3" json:"MaxAmount,omitempty"`
	MintedAmount           int64                `protobuf:"varint,3,opt,name=MintedAmount,json=mintedAmount,proto3" json:"MintedAmount,omitempty"`
	ReceiverAddress        []byte               `protobuf:"bytes,4,opt,name=ReceiverAddress,json=receiverAddress,proto3" json:"ReceiverAddress,omitempty"`
	PackData               map[string]*PackData `protobuf:"bytes,5,rep,name=PackData,json=packData,proto3" json:"PackData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DefaultLimitPerAddress int64                `protobuf:"varint,6,opt,name=DefaultLimitPerAddress,json=defaultLimitPerAddress,proto3" json:"DefaultLimitPerAddress,omitempty"`
	IsWhitelistActive      bool                 `protobuf:"varint,7,opt,name=IsWhitelistActive,json=isWhitelistActive,proto3" json:"IsWhitelistActive,omitempty"`
	WhitelistStartTime     int64                `protobuf:"varint,9,opt,name=WhitelistStartTime,json=whitelistStartTime,proto3" json:"WhitelistStartTime,omitempty"`
	WhitelistEndTime       int64                `protobuf:"varint,10,opt,name=WhitelistEndTime,json=whitelistEndTime,proto3" json:"WhitelistEndTime,omitempty"`
	WhitelistLen           int32                `protobuf:"varint,11,opt,name=WhitelistLen,json=whitelistLen,proto3" json:"WhitelistLen,omitempty"`
	StartTime              int64                `protobuf:"varint,12,opt,name=StartTime,json=startTime,proto3" json:"StartTime,omitempty"`
	EndTime                int64                `protobuf:"varint,13,opt,name=EndTime,json=endTime,proto3" json:"EndTime,omitempty"`
}

func (x *ITOData) Reset() {
	*x = ITOData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ito_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ITOData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ITOData) ProtoMessage() {}

func (x *ITOData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ITOData.ProtoReflect.Descriptor instead.
func (*ITOData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{0}
}

func (x *ITOData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ITOData) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *ITOData) GetMintedAmount() int64 {
	if x != nil {
		return x.MintedAmount
	}
	return 0
}

func (x *ITOData) GetReceiverAddress() []byte {
	if x != nil {
		return x.ReceiverAddress
	}
	return nil
}

func (x *ITOData) GetPackData() map[string]*PackData {
	if x != nil {
		return x.PackData
	}
	return nil
}

func (x *ITOData) GetDefaultLimitPerAddress() int64 {
	if x != nil {
		return x.DefaultLimitPerAddress
	}
	return 0
}

func (x *ITOData) GetIsWhitelistActive() bool {
	if x != nil {
		return x.IsWhitelistActive
	}
	return false
}

func (x *ITOData) GetWhitelistStartTime() int64 {
	if x != nil {
		return x.WhitelistStartTime
	}
	return 0
}

func (x *ITOData) GetWhitelistEndTime() int64 {
	if x != nil {
		return x.WhitelistEndTime
	}
	return 0
}

func (x *ITOData) GetWhitelistLen() int32 {
	if x != nil {
		return x.WhitelistLen
	}
	return 0
}

func (x *ITOData) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ITOData) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type PackData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packs []*Pack `protobuf:"bytes,1,rep,name=Packs,json=packs,proto3" json:"Packs,omitempty"`
}

func (x *PackData) Reset() {
	*x = PackData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ito_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackData) ProtoMessage() {}

func (x *PackData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackData.ProtoReflect.Descriptor instead.
func (*PackData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{1}
}

func (x *PackData) GetPacks() []*Pack {
	if x != nil {
		return x.Packs
	}
	return nil
}

type Pack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64 `protobuf:"varint,1,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price  int64 `protobuf:"varint,2,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
}

func (x *Pack) Reset() {
	*x = Pack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ito_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{2}
}

func (x *Pack) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pack) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type WhitelistData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=Limit,json=limit,proto3" json:"Limit,omitempty"`
}

func (x *WhitelistData) Reset() {
	*x = WhitelistData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ito_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistData) ProtoMessage() {}

func (x *WhitelistData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistData.ProtoReflect.Descriptor instead.
func (*WhitelistData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{3}
}

func (x *WhitelistData) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_ito_proto protoreflect.FileDescriptor

var file_ito_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb7, 0x04, 0x0a, 0x07, 0x49, 0x54, 0x4f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61,
	0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d,
	0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x74,
	0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x6d, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x54, 0x4f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x36, 0x0a, 0x16, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x50, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x16, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x50, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x49, 0x73, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x10, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x4c,
	0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x4c, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x4c,
	0x0a, 0x0d, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2d, 0x0a, 0x08,
	0x50, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x05, 0x50, 0x61, 0x63, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x22, 0x34, 0x0a, 0x04, 0x50,
	0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x22, 0x25, 0x0a, 0x0d, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x6b,
	0x61, 0x70, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ito_proto_rawDescOnce sync.Once
	file_ito_proto_rawDescData = file_ito_proto_rawDesc
)

func file_ito_proto_rawDescGZIP() []byte {
	file_ito_proto_rawDescOnce.Do(func() {
		file_ito_proto_rawDescData = protoimpl.X.CompressGZIP(file_ito_proto_rawDescData)
	})
	return file_ito_proto_rawDescData
}

var file_ito_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ito_proto_goTypes = []interface{}{
	(*ITOData)(nil),       // 0: proto.ITOData
	(*PackData)(nil),      // 1: proto.PackData
	(*Pack)(nil),          // 2: proto.Pack
	(*WhitelistData)(nil), // 3: proto.WhitelistData
	nil,                   // 4: proto.ITOData.PackDataEntry
}
var file_ito_proto_depIdxs = []int32{
	4, // 0: proto.ITOData.PackData:type_name -> proto.ITOData.PackDataEntry
	2, // 1: proto.PackData.Packs:type_name -> proto.Pack
	1, // 2: proto.ITOData.PackDataEntry.value:type_name -> proto.PackData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ito_proto_init() }
func file_ito_proto_init() {
	if File_ito_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ito_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ITOData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ito_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ito_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ito_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ito_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ito_proto_goTypes,
		DependencyIndexes: file_ito_proto_depIdxs,
		MessageInfos:      file_ito_proto_msgTypes,
	}.Build()
	File_ito_proto = out.File
	file_ito_proto_rawDesc = nil
	file_ito_proto_goTypes = nil
	file_ito_proto_depIdxs = nil
}
