// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ito.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ITOData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsActive               bool                   `protobuf:"varint,1,opt,name=IsActive,json=isActive,proto3" json:"IsActive,omitempty"`
	MaxAmount              int64                  `protobuf:"varint,2,opt,name=MaxAmount,json=maxAmount,proto3" json:"MaxAmount,omitempty"`
	MintedAmount           int64                  `protobuf:"varint,3,opt,name=MintedAmount,json=mintedAmount,proto3" json:"MintedAmount,omitempty"`
	ReceiverAddress        []byte                 `protobuf:"bytes,4,opt,name=ReceiverAddress,json=receiverAddress,proto3" json:"ReceiverAddress,omitempty"`
	PackData               map[string]*PackData   `protobuf:"bytes,5,rep,name=PackData,json=packData,proto3" json:"PackData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultLimitPerAddress int64                  `protobuf:"varint,6,opt,name=DefaultLimitPerAddress,json=defaultLimitPerAddress,proto3" json:"DefaultLimitPerAddress,omitempty"`
	IsWhitelistActive      bool                   `protobuf:"varint,7,opt,name=IsWhitelistActive,json=isWhitelistActive,proto3" json:"IsWhitelistActive,omitempty"`
	WhitelistStartTime     int64                  `protobuf:"varint,9,opt,name=WhitelistStartTime,json=whitelistStartTime,proto3" json:"WhitelistStartTime,omitempty"`
	WhitelistEndTime       int64                  `protobuf:"varint,10,opt,name=WhitelistEndTime,json=whitelistEndTime,proto3" json:"WhitelistEndTime,omitempty"`
	WhitelistLen           int32                  `protobuf:"varint,11,opt,name=WhitelistLen,json=whitelistLen,proto3" json:"WhitelistLen,omitempty"`
	StartTime              int64                  `protobuf:"varint,12,opt,name=StartTime,json=startTime,proto3" json:"StartTime,omitempty"`
	EndTime                int64                  `protobuf:"varint,13,opt,name=EndTime,json=endTime,proto3" json:"EndTime,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ITOData) Reset() {
	*x = ITOData{}
	mi := &file_ito_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ITOData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ITOData) ProtoMessage() {}

func (x *ITOData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ITOData.ProtoReflect.Descriptor instead.
func (*ITOData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{0}
}

func (x *ITOData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ITOData) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *ITOData) GetMintedAmount() int64 {
	if x != nil {
		return x.MintedAmount
	}
	return 0
}

func (x *ITOData) GetReceiverAddress() []byte {
	if x != nil {
		return x.ReceiverAddress
	}
	return nil
}

func (x *ITOData) GetPackData() map[string]*PackData {
	if x != nil {
		return x.PackData
	}
	return nil
}

func (x *ITOData) GetDefaultLimitPerAddress() int64 {
	if x != nil {
		return x.DefaultLimitPerAddress
	}
	return 0
}

func (x *ITOData) GetIsWhitelistActive() bool {
	if x != nil {
		return x.IsWhitelistActive
	}
	return false
}

func (x *ITOData) GetWhitelistStartTime() int64 {
	if x != nil {
		return x.WhitelistStartTime
	}
	return 0
}

func (x *ITOData) GetWhitelistEndTime() int64 {
	if x != nil {
		return x.WhitelistEndTime
	}
	return 0
}

func (x *ITOData) GetWhitelistLen() int32 {
	if x != nil {
		return x.WhitelistLen
	}
	return 0
}

func (x *ITOData) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ITOData) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type PackData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packs         []*Pack                `protobuf:"bytes,1,rep,name=Packs,json=packs,proto3" json:"Packs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackData) Reset() {
	*x = PackData{}
	mi := &file_ito_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackData) ProtoMessage() {}

func (x *PackData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackData.ProtoReflect.Descriptor instead.
func (*PackData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{1}
}

func (x *PackData) GetPacks() []*Pack {
	if x != nil {
		return x.Packs
	}
	return nil
}

type Pack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pack) Reset() {
	*x = Pack{}
	mi := &file_ito_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{2}
}

func (x *Pack) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pack) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type WhitelistData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=Limit,json=limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistData) Reset() {
	*x = WhitelistData{}
	mi := &file_ito_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistData) ProtoMessage() {}

func (x *WhitelistData) ProtoReflect() protoreflect.Message {
	mi := &file_ito_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistData.ProtoReflect.Descriptor instead.
func (*WhitelistData) Descriptor() ([]byte, []int) {
	return file_ito_proto_rawDescGZIP(), []int{3}
}

func (x *WhitelistData) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_ito_proto protoreflect.FileDescriptor

const file_ito_proto_rawDesc = "" +
	"\n" +
	"\tito.proto\x12\x05proto\"\xb7\x04\n" +
	"\aITOData\x12\x1a\n" +
	"\bIsActive\x18\x01 \x01(\bR\bisActive\x12\x1c\n" +
	"\tMaxAmount\x18\x02 \x01(\x03R\tmaxAmount\x12\"\n" +
	"\fMintedAmount\x18\x03 \x01(\x03R\fmintedAmount\x12(\n" +
	"\x0fReceiverAddress\x18\x04 \x01(\fR\x0freceiverAddress\x128\n" +
	"\bPackData\x18\x05 \x03(\v2\x1c.proto.ITOData.PackDataEntryR\bpackData\x126\n" +
	"\x16DefaultLimitPerAddress\x18\x06 \x01(\x03R\x16defaultLimitPerAddress\x12,\n" +
	"\x11IsWhitelistActive\x18\a \x01(\bR\x11isWhitelistActive\x12.\n" +
	"\x12WhitelistStartTime\x18\t \x01(\x03R\x12whitelistStartTime\x12*\n" +
	"\x10WhitelistEndTime\x18\n" +
	" \x01(\x03R\x10whitelistEndTime\x12\"\n" +
	"\fWhitelistLen\x18\v \x01(\x05R\fwhitelistLen\x12\x1c\n" +
	"\tStartTime\x18\f \x01(\x03R\tstartTime\x12\x18\n" +
	"\aEndTime\x18\r \x01(\x03R\aendTime\x1aL\n" +
	"\rPackDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.proto.PackDataR\x05value:\x028\x01\"-\n" +
	"\bPackData\x12!\n" +
	"\x05Packs\x18\x01 \x03(\v2\v.proto.PackR\x05packs\"4\n" +
	"\x04Pack\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x03R\x05price\"%\n" +
	"\rWhitelistData\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x03R\x05limitB\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_ito_proto_rawDescOnce sync.Once
	file_ito_proto_rawDescData []byte
)

func file_ito_proto_rawDescGZIP() []byte {
	file_ito_proto_rawDescOnce.Do(func() {
		file_ito_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ito_proto_rawDesc), len(file_ito_proto_rawDesc)))
	})
	return file_ito_proto_rawDescData
}

var file_ito_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ito_proto_goTypes = []any{
	(*ITOData)(nil),       // 0: proto.ITOData
	(*PackData)(nil),      // 1: proto.PackData
	(*Pack)(nil),          // 2: proto.Pack
	(*WhitelistData)(nil), // 3: proto.WhitelistData
	nil,                   // 4: proto.ITOData.PackDataEntry
}
var file_ito_proto_depIdxs = []int32{
	4, // 0: proto.ITOData.PackData:type_name -> proto.ITOData.PackDataEntry
	2, // 1: proto.PackData.Packs:type_name -> proto.Pack
	1, // 2: proto.ITOData.PackDataEntry.value:type_name -> proto.PackData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ito_proto_init() }
func file_ito_proto_init() {
	if File_ito_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ito_proto_rawDesc), len(file_ito_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ito_proto_goTypes,
		DependencyIndexes: file_ito_proto_depIdxs,
		MessageInfos:      file_ito_proto_msgTypes,
	}.Build()
	File_ito_proto = out.File
	file_ito_proto_goTypes = nil
	file_ito_proto_depIdxs = nil
}
