// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: kda.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KDAData_EnumAssetType int32

const (
	KDAData_Fungible     KDAData_EnumAssetType = 0
	KDAData_NonFungible  KDAData_EnumAssetType = 1
	KDAData_SemiFungible KDAData_EnumAssetType = 2
)

// Enum value maps for KDAData_EnumAssetType.
var (
	KDAData_EnumAssetType_name = map[int32]string{
		0: "Fungible",
		1: "NonFungible",
		2: "SemiFungible",
	}
	KDAData_EnumAssetType_value = map[string]int32{
		"Fungible":     0,
		"NonFungible":  1,
		"SemiFungible": 2,
	}
)

func (x KDAData_EnumAssetType) Enum() *KDAData_EnumAssetType {
	p := new(KDAData_EnumAssetType)
	*p = x
	return p
}

func (x KDAData_EnumAssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KDAData_EnumAssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_kda_proto_enumTypes[0].Descriptor()
}

func (KDAData_EnumAssetType) Type() protoreflect.EnumType {
	return &file_kda_proto_enumTypes[0]
}

func (x KDAData_EnumAssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KDAData_EnumAssetType.Descriptor instead.
func (KDAData_EnumAssetType) EnumDescriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{0, 0}
}

// KDAData holds the data for a Klever digital asset
type KDAData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssetType         KDAData_EnumAssetType  `protobuf:"varint,1,opt,name=AssetType,json=assetType,proto3,enum=proto.KDAData_EnumAssetType" json:"AssetType,omitempty"`
	ID                []byte                 `protobuf:"bytes,2,opt,name=ID,json=id,omitempty,proto3" json:"ID,omitempty"`
	Name              []byte                 `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Ticker            []byte                 `protobuf:"bytes,4,opt,name=Ticker,json=ticker,proto3" json:"Ticker,omitempty"`
	OwnerAddress      []byte                 `protobuf:"bytes,5,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	Logo              string                 `protobuf:"bytes,6,opt,name=Logo,json=logo,proto3" json:"Logo,omitempty"`
	URIs              map[string]string      `protobuf:"bytes,7,rep,name=URIs,json=uris,proto3" json:"URIs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Precision         uint32                 `protobuf:"varint,8,opt,name=Precision,json=precision,proto3" json:"Precision,omitempty"`
	InitialSupply     int64                  `protobuf:"varint,9,opt,name=InitialSupply,json=initialSupply,proto3" json:"InitialSupply,omitempty"`
	CirculatingSupply int64                  `protobuf:"varint,10,opt,name=CirculatingSupply,json=circulatingSupply,proto3" json:"CirculatingSupply,omitempty"`
	MaxSupply         int64                  `protobuf:"varint,11,opt,name=MaxSupply,json=maxSupply,proto3" json:"MaxSupply,omitempty"`
	MintedValue       int64                  `protobuf:"varint,12,opt,name=MintedValue,json=mintedValue,proto3" json:"MintedValue,omitempty"`
	BurnedValue       int64                  `protobuf:"varint,13,opt,name=BurnedValue,json=burnedValue,proto3" json:"BurnedValue,omitempty"`
	IssueDate         int64                  `protobuf:"varint,14,opt,name=IssueDate,json=issueDate,proto3" json:"IssueDate,omitempty"`
	Royalties         *RoyaltiesData         `protobuf:"bytes,15,opt,name=Royalties,json=royalties,proto3" json:"Royalties,omitempty"`
	Properties        *PropertiesData        `protobuf:"bytes,16,opt,name=Properties,json=properties,proto3" json:"Properties,omitempty"`
	Attributes        *AttributesData        `protobuf:"bytes,17,opt,name=Attributes,json=attributes,proto3" json:"Attributes,omitempty"`
	Roles             []*RolesData           `protobuf:"bytes,18,rep,name=Roles,json=roles,proto3" json:"Roles,omitempty"`
	AdminAddress      []byte                 `protobuf:"bytes,19,opt,name=AdminAddress,json=adminAddress,proto3" json:"AdminAddress,omitempty"`
	ControllerAddress []byte                 `protobuf:"bytes,20,opt,name=ControllerAddress,json=controllerAddress,proto3" json:"ControllerAddress,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KDAData) Reset() {
	*x = KDAData{}
	mi := &file_kda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KDAData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDAData) ProtoMessage() {}

func (x *KDAData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDAData.ProtoReflect.Descriptor instead.
func (*KDAData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{0}
}

func (x *KDAData) GetAssetType() KDAData_EnumAssetType {
	if x != nil {
		return x.AssetType
	}
	return KDAData_Fungible
}

func (x *KDAData) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *KDAData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *KDAData) GetTicker() []byte {
	if x != nil {
		return x.Ticker
	}
	return nil
}

func (x *KDAData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *KDAData) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *KDAData) GetURIs() map[string]string {
	if x != nil {
		return x.URIs
	}
	return nil
}

func (x *KDAData) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *KDAData) GetInitialSupply() int64 {
	if x != nil {
		return x.InitialSupply
	}
	return 0
}

func (x *KDAData) GetCirculatingSupply() int64 {
	if x != nil {
		return x.CirculatingSupply
	}
	return 0
}

func (x *KDAData) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *KDAData) GetMintedValue() int64 {
	if x != nil {
		return x.MintedValue
	}
	return 0
}

func (x *KDAData) GetBurnedValue() int64 {
	if x != nil {
		return x.BurnedValue
	}
	return 0
}

func (x *KDAData) GetIssueDate() int64 {
	if x != nil {
		return x.IssueDate
	}
	return 0
}

func (x *KDAData) GetRoyalties() *RoyaltiesData {
	if x != nil {
		return x.Royalties
	}
	return nil
}

func (x *KDAData) GetProperties() *PropertiesData {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *KDAData) GetAttributes() *AttributesData {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *KDAData) GetRoles() []*RolesData {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *KDAData) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *KDAData) GetControllerAddress() []byte {
	if x != nil {
		return x.ControllerAddress
	}
	return nil
}

// PropertiesData hold the properties structure for the KDA asset
type PropertiesData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CanFreeze      bool                   `protobuf:"varint,1,opt,name=CanFreeze,json=canFreeze,proto3" json:"CanFreeze,omitempty"`
	CanWipe        bool                   `protobuf:"varint,2,opt,name=CanWipe,json=canWipe,proto3" json:"CanWipe,omitempty"`
	CanPause       bool                   `protobuf:"varint,3,opt,name=CanPause,json=canPause,proto3" json:"CanPause,omitempty"`
	CanMint        bool                   `protobuf:"varint,4,opt,name=CanMint,json=canMint,proto3" json:"CanMint,omitempty"`
	CanBurn        bool                   `protobuf:"varint,5,opt,name=CanBurn,json=canBurn,proto3" json:"CanBurn,omitempty"`
	CanChangeOwner bool                   `protobuf:"varint,6,opt,name=CanChangeOwner,json=canChangeOwner,proto3" json:"CanChangeOwner,omitempty"`
	CanAddRoles    bool                   `protobuf:"varint,7,opt,name=CanAddRoles,json=canAddRoles,proto3" json:"CanAddRoles,omitempty"`
	LimitTransfer  bool                   `protobuf:"varint,8,opt,name=LimitTransfer,json=limitTransfer,proto3" json:"LimitTransfer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PropertiesData) Reset() {
	*x = PropertiesData{}
	mi := &file_kda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertiesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertiesData) ProtoMessage() {}

func (x *PropertiesData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertiesData.ProtoReflect.Descriptor instead.
func (*PropertiesData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{1}
}

func (x *PropertiesData) GetCanFreeze() bool {
	if x != nil {
		return x.CanFreeze
	}
	return false
}

func (x *PropertiesData) GetCanWipe() bool {
	if x != nil {
		return x.CanWipe
	}
	return false
}

func (x *PropertiesData) GetCanPause() bool {
	if x != nil {
		return x.CanPause
	}
	return false
}

func (x *PropertiesData) GetCanMint() bool {
	if x != nil {
		return x.CanMint
	}
	return false
}

func (x *PropertiesData) GetCanBurn() bool {
	if x != nil {
		return x.CanBurn
	}
	return false
}

func (x *PropertiesData) GetCanChangeOwner() bool {
	if x != nil {
		return x.CanChangeOwner
	}
	return false
}

func (x *PropertiesData) GetCanAddRoles() bool {
	if x != nil {
		return x.CanAddRoles
	}
	return false
}

func (x *PropertiesData) GetLimitTransfer() bool {
	if x != nil {
		return x.LimitTransfer
	}
	return false
}

// AttributesData hold the attributes structure for the KDA asset
type AttributesData struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	IsPaused                   bool                   `protobuf:"varint,1,opt,name=IsPaused,json=isPaused,proto3" json:"IsPaused,omitempty"`
	IsNFTMintStopped           bool                   `protobuf:"varint,2,opt,name=IsNFTMintStopped,json=isNFTMintStopped,proto3" json:"IsNFTMintStopped,omitempty"`
	IsRoyaltiesChangeStopped   bool                   `protobuf:"varint,3,opt,name=IsRoyaltiesChangeStopped,json=isRoyaltiesChangeStopped,proto3" json:"IsRoyaltiesChangeStopped,omitempty"`
	IsNFTMetadataChangeStopped bool                   `protobuf:"varint,4,opt,name=IsNFTMetadataChangeStopped,json=isNFTMetadataChangeStopped,proto3" json:"IsNFTMetadataChangeStopped,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AttributesData) Reset() {
	*x = AttributesData{}
	mi := &file_kda_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesData) ProtoMessage() {}

func (x *AttributesData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesData.ProtoReflect.Descriptor instead.
func (*AttributesData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{2}
}

func (x *AttributesData) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

func (x *AttributesData) GetIsNFTMintStopped() bool {
	if x != nil {
		return x.IsNFTMintStopped
	}
	return false
}

func (x *AttributesData) GetIsRoyaltiesChangeStopped() bool {
	if x != nil {
		return x.IsRoyaltiesChangeStopped
	}
	return false
}

func (x *AttributesData) GetIsNFTMetadataChangeStopped() bool {
	if x != nil {
		return x.IsNFTMetadataChangeStopped
	}
	return false
}

// RolesData holds the roles for a given asset and the given address
type RolesData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Address             []byte                 `protobuf:"bytes,1,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	HasRoleMint         bool                   `protobuf:"varint,2,opt,name=HasRoleMint,json=hasRoleMint,proto3" json:"HasRoleMint,omitempty"`
	HasRoleSetITOPrices bool                   `protobuf:"varint,3,opt,name=HasRoleSetITOPrices,json=hasRoleSetITOPrices,proto3" json:"HasRoleSetITOPrices,omitempty"`
	HasRoleDeposit      bool                   `protobuf:"varint,4,opt,name=HasRoleDeposit,json=hasRoleDeposit,proto3" json:"HasRoleDeposit,omitempty"`
	HasRoleTransfer     bool                   `protobuf:"varint,5,opt,name=HasRoleTransfer,json=hasRoleTransfer,proto3" json:"HasRoleTransfer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RolesData) Reset() {
	*x = RolesData{}
	mi := &file_kda_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesData) ProtoMessage() {}

func (x *RolesData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesData.ProtoReflect.Descriptor instead.
func (*RolesData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{3}
}

func (x *RolesData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RolesData) GetHasRoleMint() bool {
	if x != nil {
		return x.HasRoleMint
	}
	return false
}

func (x *RolesData) GetHasRoleSetITOPrices() bool {
	if x != nil {
		return x.HasRoleSetITOPrices
	}
	return false
}

func (x *RolesData) GetHasRoleDeposit() bool {
	if x != nil {
		return x.HasRoleDeposit
	}
	return false
}

func (x *RolesData) GetHasRoleTransfer() bool {
	if x != nil {
		return x.HasRoleTransfer
	}
	return false
}

// RoyaltiesData holds the royalties for a given asset
type RoyaltiesData struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	Address            []byte                       `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	TransferPercentage []*RoyaltyData               `protobuf:"bytes,2,rep,name=TransferPercentage,json=transferPercentage,proto3" json:"TransferPercentage,omitempty"`
	TransferFixed      int64                        `protobuf:"varint,3,opt,name=TransferFixed,json=transferFixed,proto3" json:"TransferFixed,omitempty"`
	MarketPercentage   uint32                       `protobuf:"varint,4,opt,name=MarketPercentage,json=marketPercentage,proto3" json:"MarketPercentage,omitempty"`
	MarketFixed        int64                        `protobuf:"varint,5,opt,name=MarketFixed,json=marketFixed,proto3" json:"MarketFixed,omitempty"`
	SplitRoyalties     map[string]*RoyaltySplitData `protobuf:"bytes,6,rep,name=SplitRoyalties,json=splitRoyalties,proto3" json:"SplitRoyalties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ITOPercentage      uint32                       `protobuf:"varint,7,opt,name=ITOPercentage,json=itoPercentage,proto3" json:"ITOPercentage,omitempty"`
	ITOFixed           int64                        `protobuf:"varint,8,opt,name=ITOFixed,json=itoFixed,proto3" json:"ITOFixed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoyaltiesData) Reset() {
	*x = RoyaltiesData{}
	mi := &file_kda_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoyaltiesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoyaltiesData) ProtoMessage() {}

func (x *RoyaltiesData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoyaltiesData.ProtoReflect.Descriptor instead.
func (*RoyaltiesData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{4}
}

func (x *RoyaltiesData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RoyaltiesData) GetTransferPercentage() []*RoyaltyData {
	if x != nil {
		return x.TransferPercentage
	}
	return nil
}

func (x *RoyaltiesData) GetTransferFixed() int64 {
	if x != nil {
		return x.TransferFixed
	}
	return 0
}

func (x *RoyaltiesData) GetMarketPercentage() uint32 {
	if x != nil {
		return x.MarketPercentage
	}
	return 0
}

func (x *RoyaltiesData) GetMarketFixed() int64 {
	if x != nil {
		return x.MarketFixed
	}
	return 0
}

func (x *RoyaltiesData) GetSplitRoyalties() map[string]*RoyaltySplitData {
	if x != nil {
		return x.SplitRoyalties
	}
	return nil
}

func (x *RoyaltiesData) GetITOPercentage() uint32 {
	if x != nil {
		return x.ITOPercentage
	}
	return 0
}

func (x *RoyaltiesData) GetITOFixed() int64 {
	if x != nil {
		return x.ITOFixed
	}
	return 0
}

// Royalty holds the royalty threshold
type RoyaltyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Percentage    uint32                 `protobuf:"varint,2,opt,name=Percentage,json=percentage,proto3" json:"Percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoyaltyData) Reset() {
	*x = RoyaltyData{}
	mi := &file_kda_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoyaltyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoyaltyData) ProtoMessage() {}

func (x *RoyaltyData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoyaltyData.ProtoReflect.Descriptor instead.
func (*RoyaltyData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{5}
}

func (x *RoyaltyData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RoyaltyData) GetPercentage() uint32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// RoyaltySplitData holds the royalty split
type RoyaltySplitData struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PercentTransferPercentage uint32                 `protobuf:"varint,1,opt,name=PercentTransferPercentage,json=percentTransferPercentage,proto3" json:"PercentTransferPercentage,omitempty"`
	PercentTransferFixed      uint32                 `protobuf:"varint,2,opt,name=PercentTransferFixed,json=percentTransferFixed,proto3" json:"PercentTransferFixed,omitempty"`
	PercentMarketPercentage   uint32                 `protobuf:"varint,3,opt,name=PercentMarketPercentage,json=percentMarketPercentage,proto3" json:"PercentMarketPercentage,omitempty"`
	PercentMarketFixed        uint32                 `protobuf:"varint,4,opt,name=PercentMarketFixed,json=percentMarketFixed,proto3" json:"PercentMarketFixed,omitempty"`
	PercentITOPercentage      uint32                 `protobuf:"varint,5,opt,name=PercentITOPercentage,json=percentITOPercentage,proto3" json:"PercentITOPercentage,omitempty"`
	PercentITOFixed           uint32                 `protobuf:"varint,6,opt,name=PercentITOFixed,json=percentITOFixed,proto3" json:"PercentITOFixed,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RoyaltySplitData) Reset() {
	*x = RoyaltySplitData{}
	mi := &file_kda_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoyaltySplitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoyaltySplitData) ProtoMessage() {}

func (x *RoyaltySplitData) ProtoReflect() protoreflect.Message {
	mi := &file_kda_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoyaltySplitData.ProtoReflect.Descriptor instead.
func (*RoyaltySplitData) Descriptor() ([]byte, []int) {
	return file_kda_proto_rawDescGZIP(), []int{6}
}

func (x *RoyaltySplitData) GetPercentTransferPercentage() uint32 {
	if x != nil {
		return x.PercentTransferPercentage
	}
	return 0
}

func (x *RoyaltySplitData) GetPercentTransferFixed() uint32 {
	if x != nil {
		return x.PercentTransferFixed
	}
	return 0
}

func (x *RoyaltySplitData) GetPercentMarketPercentage() uint32 {
	if x != nil {
		return x.PercentMarketPercentage
	}
	return 0
}

func (x *RoyaltySplitData) GetPercentMarketFixed() uint32 {
	if x != nil {
		return x.PercentMarketFixed
	}
	return 0
}

func (x *RoyaltySplitData) GetPercentITOPercentage() uint32 {
	if x != nil {
		return x.PercentITOPercentage
	}
	return 0
}

func (x *RoyaltySplitData) GetPercentITOFixed() uint32 {
	if x != nil {
		return x.PercentITOFixed
	}
	return 0
}

var File_kda_proto protoreflect.FileDescriptor

const file_kda_proto_rawDesc = "" +
	"\n" +
	"\tkda.proto\x12\x05proto\"\xfa\x06\n" +
	"\aKDAData\x12:\n" +
	"\tAssetType\x18\x01 \x01(\x0e2\x1c.proto.KDAData.EnumAssetTypeR\tassetType\x12\x18\n" +
	"\x02ID\x18\x02 \x01(\fR\fid,omitempty\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\fR\x04name\x12\x16\n" +
	"\x06Ticker\x18\x04 \x01(\fR\x06ticker\x12\"\n" +
	"\fOwnerAddress\x18\x05 \x01(\fR\fownerAddress\x12\x12\n" +
	"\x04Logo\x18\x06 \x01(\tR\x04logo\x12,\n" +
	"\x04URIs\x18\a \x03(\v2\x18.proto.KDAData.URIsEntryR\x04uris\x12\x1c\n" +
	"\tPrecision\x18\b \x01(\rR\tprecision\x12$\n" +
	"\rInitialSupply\x18\t \x01(\x03R\rinitialSupply\x12,\n" +
	"\x11CirculatingSupply\x18\n" +
	" \x01(\x03R\x11circulatingSupply\x12\x1c\n" +
	"\tMaxSupply\x18\v \x01(\x03R\tmaxSupply\x12 \n" +
	"\vMintedValue\x18\f \x01(\x03R\vmintedValue\x12 \n" +
	"\vBurnedValue\x18\r \x01(\x03R\vburnedValue\x12\x1c\n" +
	"\tIssueDate\x18\x0e \x01(\x03R\tissueDate\x122\n" +
	"\tRoyalties\x18\x0f \x01(\v2\x14.proto.RoyaltiesDataR\troyalties\x125\n" +
	"\n" +
	"Properties\x18\x10 \x01(\v2\x15.proto.PropertiesDataR\n" +
	"properties\x125\n" +
	"\n" +
	"Attributes\x18\x11 \x01(\v2\x15.proto.AttributesDataR\n" +
	"attributes\x12&\n" +
	"\x05Roles\x18\x12 \x03(\v2\x10.proto.RolesDataR\x05roles\x12\"\n" +
	"\fAdminAddress\x18\x13 \x01(\fR\fadminAddress\x12,\n" +
	"\x11ControllerAddress\x18\x14 \x01(\fR\x11controllerAddress\x1a7\n" +
	"\tURIsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\rEnumAssetType\x12\f\n" +
	"\bFungible\x10\x00\x12\x0f\n" +
	"\vNonFungible\x10\x01\x12\x10\n" +
	"\fSemiFungible\x10\x02\"\x88\x02\n" +
	"\x0ePropertiesData\x12\x1c\n" +
	"\tCanFreeze\x18\x01 \x01(\bR\tcanFreeze\x12\x18\n" +
	"\aCanWipe\x18\x02 \x01(\bR\acanWipe\x12\x1a\n" +
	"\bCanPause\x18\x03 \x01(\bR\bcanPause\x12\x18\n" +
	"\aCanMint\x18\x04 \x01(\bR\acanMint\x12\x18\n" +
	"\aCanBurn\x18\x05 \x01(\bR\acanBurn\x12&\n" +
	"\x0eCanChangeOwner\x18\x06 \x01(\bR\x0ecanChangeOwner\x12 \n" +
	"\vCanAddRoles\x18\a \x01(\bR\vcanAddRoles\x12$\n" +
	"\rLimitTransfer\x18\b \x01(\bR\rlimitTransfer\"\xd4\x01\n" +
	"\x0eAttributesData\x12\x1a\n" +
	"\bIsPaused\x18\x01 \x01(\bR\bisPaused\x12*\n" +
	"\x10IsNFTMintStopped\x18\x02 \x01(\bR\x10isNFTMintStopped\x12:\n" +
	"\x18IsRoyaltiesChangeStopped\x18\x03 \x01(\bR\x18isRoyaltiesChangeStopped\x12>\n" +
	"\x1aIsNFTMetadataChangeStopped\x18\x04 \x01(\bR\x1aisNFTMetadataChangeStopped\"\xcb\x01\n" +
	"\tRolesData\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aaddress\x12 \n" +
	"\vHasRoleMint\x18\x02 \x01(\bR\vhasRoleMint\x120\n" +
	"\x13HasRoleSetITOPrices\x18\x03 \x01(\bR\x13hasRoleSetITOPrices\x12&\n" +
	"\x0eHasRoleDeposit\x18\x04 \x01(\bR\x0ehasRoleDeposit\x12(\n" +
	"\x0fHasRoleTransfer\x18\x05 \x01(\bR\x0fhasRoleTransfer\"\xd1\x03\n" +
	"\rRoyaltiesData\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12B\n" +
	"\x12TransferPercentage\x18\x02 \x03(\v2\x12.proto.RoyaltyDataR\x12transferPercentage\x12$\n" +
	"\rTransferFixed\x18\x03 \x01(\x03R\rtransferFixed\x12*\n" +
	"\x10MarketPercentage\x18\x04 \x01(\rR\x10marketPercentage\x12 \n" +
	"\vMarketFixed\x18\x05 \x01(\x03R\vmarketFixed\x12P\n" +
	"\x0eSplitRoyalties\x18\x06 \x03(\v2(.proto.RoyaltiesData.SplitRoyaltiesEntryR\x0esplitRoyalties\x12$\n" +
	"\rITOPercentage\x18\a \x01(\rR\ritoPercentage\x12\x1a\n" +
	"\bITOFixed\x18\b \x01(\x03R\bitoFixed\x1aZ\n" +
	"\x13SplitRoyaltiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.proto.RoyaltySplitDataR\x05value:\x028\x01\"E\n" +
	"\vRoyaltyData\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"Percentage\x18\x02 \x01(\rR\n" +
	"percentage\"\xcc\x02\n" +
	"\x10RoyaltySplitData\x12<\n" +
	"\x19PercentTransferPercentage\x18\x01 \x01(\rR\x19percentTransferPercentage\x122\n" +
	"\x14PercentTransferFixed\x18\x02 \x01(\rR\x14percentTransferFixed\x128\n" +
	"\x17PercentMarketPercentage\x18\x03 \x01(\rR\x17percentMarketPercentage\x12.\n" +
	"\x12PercentMarketFixed\x18\x04 \x01(\rR\x12percentMarketFixed\x122\n" +
	"\x14PercentITOPercentage\x18\x05 \x01(\rR\x14percentITOPercentage\x12(\n" +
	"\x0fPercentITOFixed\x18\x06 \x01(\rR\x0fpercentITOFixedB\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_kda_proto_rawDescOnce sync.Once
	file_kda_proto_rawDescData []byte
)

func file_kda_proto_rawDescGZIP() []byte {
	file_kda_proto_rawDescOnce.Do(func() {
		file_kda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kda_proto_rawDesc), len(file_kda_proto_rawDesc)))
	})
	return file_kda_proto_rawDescData
}

var file_kda_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kda_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kda_proto_goTypes = []any{
	(KDAData_EnumAssetType)(0), // 0: proto.KDAData.EnumAssetType
	(*KDAData)(nil),            // 1: proto.KDAData
	(*PropertiesData)(nil),     // 2: proto.PropertiesData
	(*AttributesData)(nil),     // 3: proto.AttributesData
	(*RolesData)(nil),          // 4: proto.RolesData
	(*RoyaltiesData)(nil),      // 5: proto.RoyaltiesData
	(*RoyaltyData)(nil),        // 6: proto.RoyaltyData
	(*RoyaltySplitData)(nil),   // 7: proto.RoyaltySplitData
	nil,                        // 8: proto.KDAData.URIsEntry
	nil,                        // 9: proto.RoyaltiesData.SplitRoyaltiesEntry
}
var file_kda_proto_depIdxs = []int32{
	0, // 0: proto.KDAData.AssetType:type_name -> proto.KDAData.EnumAssetType
	8, // 1: proto.KDAData.URIs:type_name -> proto.KDAData.URIsEntry
	5, // 2: proto.KDAData.Royalties:type_name -> proto.RoyaltiesData
	2, // 3: proto.KDAData.Properties:type_name -> proto.PropertiesData
	3, // 4: proto.KDAData.Attributes:type_name -> proto.AttributesData
	4, // 5: proto.KDAData.Roles:type_name -> proto.RolesData
	6, // 6: proto.RoyaltiesData.TransferPercentage:type_name -> proto.RoyaltyData
	9, // 7: proto.RoyaltiesData.SplitRoyalties:type_name -> proto.RoyaltiesData.SplitRoyaltiesEntry
	7, // 8: proto.RoyaltiesData.SplitRoyaltiesEntry.value:type_name -> proto.RoyaltySplitData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_kda_proto_init() }
func file_kda_proto_init() {
	if File_kda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kda_proto_rawDesc), len(file_kda_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kda_proto_goTypes,
		DependencyIndexes: file_kda_proto_depIdxs,
		EnumInfos:         file_kda_proto_enumTypes,
		MessageInfos:      file_kda_proto_msgTypes,
	}.Build()
	File_kda_proto = out.File
	file_kda_proto_goTypes = nil
	file_kda_proto_depIdxs = nil
}
