// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: market.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketOrderData_EnumMarketType int32

const (
	MarketOrderData_BuyItNow MarketOrderData_EnumMarketType = 0
	MarketOrderData_Auction  MarketOrderData_EnumMarketType = 1
)

// Enum value maps for MarketOrderData_EnumMarketType.
var (
	MarketOrderData_EnumMarketType_name = map[int32]string{
		0: "BuyItNow",
		1: "Auction",
	}
	MarketOrderData_EnumMarketType_value = map[string]int32{
		"BuyItNow": 0,
		"Auction":  1,
	}
)

func (x MarketOrderData_EnumMarketType) Enum() *MarketOrderData_EnumMarketType {
	p := new(MarketOrderData_EnumMarketType)
	*p = x
	return p
}

func (x MarketOrderData_EnumMarketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketOrderData_EnumMarketType) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[0].Descriptor()
}

func (MarketOrderData_EnumMarketType) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[0]
}

func (x MarketOrderData_EnumMarketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketOrderData_EnumMarketType.Descriptor instead.
func (MarketOrderData_EnumMarketType) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1, 0}
}

type Marketplace struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ID                 []byte                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Name               []byte                 `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	OwnerAddress       []byte                 `protobuf:"bytes,3,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	ReferralAddress    []byte                 `protobuf:"bytes,4,opt,name=ReferralAddress,json=referralAddress,omitempty,proto3" json:"ReferralAddress,omitempty"`
	ReferralPercentage uint32                 `protobuf:"varint,5,opt,name=ReferralPercentage,json=referralPercentage,omitempty,proto3" json:"ReferralPercentage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Marketplace) Reset() {
	*x = Marketplace{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Marketplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Marketplace) ProtoMessage() {}

func (x *Marketplace) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Marketplace.ProtoReflect.Descriptor instead.
func (*Marketplace) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Marketplace) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Marketplace) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Marketplace) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *Marketplace) GetReferralAddress() []byte {
	if x != nil {
		return x.ReferralAddress
	}
	return nil
}

func (x *Marketplace) GetReferralPercentage() uint32 {
	if x != nil {
		return x.ReferralPercentage
	}
	return 0
}

type MarketOrderData struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	ID                    []byte                         `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	MarketplaceID         []byte                         `protobuf:"bytes,2,opt,name=MarketplaceID,json=marketplaceId,proto3" json:"MarketplaceID,omitempty"`
	MarketType            MarketOrderData_EnumMarketType `protobuf:"varint,3,opt,name=MarketType,json=marketType,proto3,enum=proto.MarketOrderData_EnumMarketType" json:"MarketType,omitempty"`
	OwnerAddress          []byte                         `protobuf:"bytes,4,opt,name=OwnerAddress,json=ownerAddress,proto3" json:"OwnerAddress,omitempty"`
	AssetID               []byte                         `protobuf:"bytes,5,opt,name=AssetID,json=assetId,proto3" json:"AssetID,omitempty"`
	CollectionID          []byte                         `protobuf:"bytes,6,opt,name=CollectionID,json=collectionId,proto3" json:"CollectionID,omitempty"`
	CurrencyID            []byte                         `protobuf:"bytes,7,opt,name=CurrencyID,json=currencyId,proto3" json:"CurrencyID,omitempty"`
	Price                 int64                          `protobuf:"varint,8,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	ReservePrice          int64                          `protobuf:"varint,9,opt,name=ReservePrice,json=reservePrice,omitempty,proto3" json:"ReservePrice,omitempty"`
	CurrentBidder         []byte                         `protobuf:"bytes,10,opt,name=CurrentBidder,json=currentBidder,omitempty,proto3" json:"CurrentBidder,omitempty"`
	CurrentBid            int64                          `protobuf:"varint,11,opt,name=CurrentBid,json=currentBid,omitempty,proto3" json:"CurrentBid,omitempty"`
	RoyaltiesFixedDeposit int64                          `protobuf:"varint,12,opt,name=RoyaltiesFixedDeposit,json=royaltiesFixedDeposit,omitempty,proto3" json:"RoyaltiesFixedDeposit,omitempty"`
	ReferralPercentage    uint32                         `protobuf:"varint,13,opt,name=ReferralPercentage,json=referralPercentage,omitempty,proto3" json:"ReferralPercentage,omitempty"`
	StartTime             int64                          `protobuf:"varint,14,opt,name=StartTime,json=startTime,proto3" json:"StartTime,omitempty"`
	EndTime               int64                          `protobuf:"varint,15,opt,name=EndTime,json=endTime,proto3" json:"EndTime,omitempty"`
	IsClaimed             bool                           `protobuf:"varint,16,opt,name=IsClaimed,json=isClaimed,proto3" json:"IsClaimed,omitempty"`
	RoyaltyPercentage     uint32                         `protobuf:"varint,17,opt,name=RoyaltyPercentage,json=royaltyPercentage,omitempty,proto3" json:"RoyaltyPercentage,omitempty"`
	RoyaltySnapshotted    bool                           `protobuf:"varint,18,opt,name=RoyaltySnapshotted,json=royaltySnapshotted,omitempty,proto3" json:"RoyaltySnapshotted,omitempty"`
	ReferralAddress       []byte                         `protobuf:"bytes,19,opt,name=ReferralAddress,json=referralAddress,omitempty,proto3" json:"ReferralAddress,omitempty"`
	ReferralSnapshotted   bool                           `protobuf:"varint,20,opt,name=ReferralSnapshotted,json=referralSnapshotted,omitempty,proto3" json:"ReferralSnapshotted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MarketOrderData) Reset() {
	*x = MarketOrderData{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketOrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketOrderData) ProtoMessage() {}

func (x *MarketOrderData) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketOrderData.ProtoReflect.Descriptor instead.
func (*MarketOrderData) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *MarketOrderData) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *MarketOrderData) GetMarketplaceID() []byte {
	if x != nil {
		return x.MarketplaceID
	}
	return nil
}

func (x *MarketOrderData) GetMarketType() MarketOrderData_EnumMarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketOrderData_BuyItNow
}

func (x *MarketOrderData) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *MarketOrderData) GetAssetID() []byte {
	if x != nil {
		return x.AssetID
	}
	return nil
}

func (x *MarketOrderData) GetCollectionID() []byte {
	if x != nil {
		return x.CollectionID
	}
	return nil
}

func (x *MarketOrderData) GetCurrencyID() []byte {
	if x != nil {
		return x.CurrencyID
	}
	return nil
}

func (x *MarketOrderData) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketOrderData) GetReservePrice() int64 {
	if x != nil {
		return x.ReservePrice
	}
	return 0
}

func (x *MarketOrderData) GetCurrentBidder() []byte {
	if x != nil {
		return x.CurrentBidder
	}
	return nil
}

func (x *MarketOrderData) GetCurrentBid() int64 {
	if x != nil {
		return x.CurrentBid
	}
	return 0
}

func (x *MarketOrderData) GetRoyaltiesFixedDeposit() int64 {
	if x != nil {
		return x.RoyaltiesFixedDeposit
	}
	return 0
}

func (x *MarketOrderData) GetReferralPercentage() uint32 {
	if x != nil {
		return x.ReferralPercentage
	}
	return 0
}

func (x *MarketOrderData) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MarketOrderData) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MarketOrderData) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

func (x *MarketOrderData) GetRoyaltyPercentage() uint32 {
	if x != nil {
		return x.RoyaltyPercentage
	}
	return 0
}

func (x *MarketOrderData) GetRoyaltySnapshotted() bool {
	if x != nil {
		return x.RoyaltySnapshotted
	}
	return false
}

func (x *MarketOrderData) GetReferralAddress() []byte {
	if x != nil {
		return x.ReferralAddress
	}
	return nil
}

func (x *MarketOrderData) GetReferralSnapshotted() bool {
	if x != nil {
		return x.ReferralSnapshotted
	}
	return false
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x05proto\"\xc3\x01\n" +
	"\vMarketplace\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\fR\x04name\x12\"\n" +
	"\fOwnerAddress\x18\x03 \x01(\fR\fownerAddress\x122\n" +
	"\x0fReferralAddress\x18\x04 \x01(\fR\x19referralAddress,omitempty\x128\n" +
	"\x12ReferralPercentage\x18\x05 \x01(\rR\x1creferralPercentage,omitempty\"\x8d\a\n" +
	"\x0fMarketOrderData\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02id\x12$\n" +
	"\rMarketplaceID\x18\x02 \x01(\fR\rmarketplaceId\x12E\n" +
	"\n" +
	"MarketType\x18\x03 \x01(\x0e2%.proto.MarketOrderData.EnumMarketTypeR\n" +
	"marketType\x12\"\n" +
	"\fOwnerAddress\x18\x04 \x01(\fR\fownerAddress\x12\x18\n" +
	"\aAssetID\x18\x05 \x01(\fR\aassetId\x12\"\n" +
	"\fCollectionID\x18\x06 \x01(\fR\fcollectionId\x12\x1e\n" +
	"\n" +
	"CurrencyID\x18\a \x01(\fR\n" +
	"currencyId\x12\x14\n" +
	"\x05Price\x18\b \x01(\x03R\x05price\x12,\n" +
	"\fReservePrice\x18\t \x01(\x03R\x16reservePrice,omitempty\x12.\n" +
	"\rCurrentBidder\x18\n" +
	" \x01(\fR\x17currentBidder,omitempty\x12(\n" +
	"\n" +
	"CurrentBid\x18\v \x01(\x03R\x14currentBid,omitempty\x12>\n" +
	"\x15RoyaltiesFixedDeposit\x18\f \x01(\x03R\x1froyaltiesFixedDeposit,omitempty\x128\n" +
	"\x12ReferralPercentage\x18\r \x01(\rR\x1creferralPercentage,omitempty\x12\x1c\n" +
	"\tStartTime\x18\x0e \x01(\x03R\tstartTime\x12\x18\n" +
	"\aEndTime\x18\x0f \x01(\x03R\aendTime\x12\x1c\n" +
	"\tIsClaimed\x18\x10 \x01(\bR\tisClaimed\x126\n" +
	"\x11RoyaltyPercentage\x18\x11 \x01(\rR\x1broyaltyPercentage,omitempty\x128\n" +
	"\x12RoyaltySnapshotted\x18\x12 \x01(\bR\x1croyaltySnapshotted,omitempty\x122\n" +
	"\x0fReferralAddress\x18\x13 \x01(\fR\x19referralAddress,omitempty\x12:\n" +
	"\x13ReferralSnapshotted\x18\x14 \x01(\bR\x1dreferralSnapshotted,omitempty\"+\n" +
	"\x0eEnumMarketType\x12\f\n" +
	"\bBuyItNow\x10\x00\x12\v\n" +
	"\aAuction\x10\x01B\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_proto_goTypes = []any{
	(MarketOrderData_EnumMarketType)(0), // 0: proto.MarketOrderData.EnumMarketType
	(*Marketplace)(nil),                 // 1: proto.Marketplace
	(*MarketOrderData)(nil),             // 2: proto.MarketOrderData
}
var file_market_proto_depIdxs = []int32{
	0, // 0: proto.MarketOrderData.MarketType:type_name -> proto.MarketOrderData.EnumMarketType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		EnumInfos:         file_market_proto_enumTypes,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
