// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proposal.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumType int32

const (
	EnumType_Bool       EnumType = 0
	EnumType_Int8       EnumType = 1
	EnumType_Int16      EnumType = 2
	EnumType_Int32      EnumType = 3
	EnumType_Int64      EnumType = 4
	EnumType_Uint8      EnumType = 5
	EnumType_Uint16     EnumType = 6
	EnumType_Uint32     EnumType = 7
	EnumType_Uint64     EnumType = 8
	EnumType_Float32    EnumType = 9
	EnumType_Float64    EnumType = 10
	EnumType_Complex64  EnumType = 11
	EnumType_Complex128 EnumType = 12
	EnumType_String     EnumType = 13
	EnumType_Bytes      EnumType = 14
)

// Enum value maps for EnumType.
var (
	EnumType_name = map[int32]string{
		0:  "Bool",
		1:  "Int8",
		2:  "Int16",
		3:  "Int32",
		4:  "Int64",
		5:  "Uint8",
		6:  "Uint16",
		7:  "Uint32",
		8:  "Uint64",
		9:  "Float32",
		10: "Float64",
		11: "Complex64",
		12: "Complex128",
		13: "String",
		14: "Bytes",
	}
	EnumType_value = map[string]int32{
		"Bool":       0,
		"Int8":       1,
		"Int16":      2,
		"Int32":      3,
		"Int64":      4,
		"Uint8":      5,
		"Uint16":     6,
		"Uint32":     7,
		"Uint64":     8,
		"Float32":    9,
		"Float64":    10,
		"Complex64":  11,
		"Complex128": 12,
		"String":     13,
		"Bytes":      14,
	}
)

func (x EnumType) Enum() *EnumType {
	p := new(EnumType)
	*p = x
	return p
}

func (x EnumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumType) Descriptor() protoreflect.EnumDescriptor {
	return file_proposal_proto_enumTypes[0].Descriptor()
}

func (EnumType) Type() protoreflect.EnumType {
	return &file_proposal_proto_enumTypes[0]
}

func (x EnumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumType.Descriptor instead.
func (EnumType) EnumDescriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{0}
}

type EnumParameter int32

const (
	EnumParameter_FeePerDataByte                   EnumParameter = 0
	EnumParameter_KAppFeeCreateValidator           EnumParameter = 1
	EnumParameter_KAppFeeCreateAsset               EnumParameter = 2
	EnumParameter_MaxEpochsUnclaimed               EnumParameter = 3
	EnumParameter_MinSelfDelegatedAmount           EnumParameter = 4
	EnumParameter_MinTotalDelegatedAmount          EnumParameter = 5
	EnumParameter_BlockRewards                     EnumParameter = 6
	EnumParameter_StakingRewards                   EnumParameter = 7
	EnumParameter_KAppFeeTransfer                  EnumParameter = 8
	EnumParameter_KAppFeeAssetTrigger              EnumParameter = 9
	EnumParameter_KAppFeeValidatorConfig           EnumParameter = 10
	EnumParameter_KAppFeeFreeze                    EnumParameter = 11
	EnumParameter_KAppFeeUnfreeze                  EnumParameter = 12
	EnumParameter_KAppFeeDelegate                  EnumParameter = 13
	EnumParameter_KAppFeeUndelegate                EnumParameter = 14
	EnumParameter_KAppFeeWithdraw                  EnumParameter = 15
	EnumParameter_KAppFeeClaim                     EnumParameter = 16
	EnumParameter_KAppFeeUnjail                    EnumParameter = 17
	EnumParameter_KAppFeeSetAccountName            EnumParameter = 18
	EnumParameter_KAppFeeProposal                  EnumParameter = 19
	EnumParameter_KAppFeeVote                      EnumParameter = 20
	EnumParameter_KAppFeeConfigITO                 EnumParameter = 21
	EnumParameter_KAppFeeSetITOPrices              EnumParameter = 22
	EnumParameter_KAppFeeBuy                       EnumParameter = 23
	EnumParameter_KAppFeeSell                      EnumParameter = 24
	EnumParameter_KAppFeeCancelMarketOrder         EnumParameter = 25
	EnumParameter_KAppFeeCreateMarketplace         EnumParameter = 26
	EnumParameter_KAppFeeConfigMarketplace         EnumParameter = 27
	EnumParameter_KAppFeeUpdateAccountPermission   EnumParameter = 28
	EnumParameter_MaxNFTMintBatch                  EnumParameter = 29
	EnumParameter_MinKFIStakedToEnableProposals    EnumParameter = 30
	EnumParameter_MinKLVBucketAmount               EnumParameter = 31
	EnumParameter_MaxBucketSize                    EnumParameter = 32
	EnumParameter_LeaderValidatorRewardsPercentage EnumParameter = 33
	EnumParameter_ProposalMaxEpochsDuration        EnumParameter = 34
	EnumParameter_KAppFeeITOTrigger                EnumParameter = 35
	EnumParameter_KAppFeeDeposit                   EnumParameter = 36
	EnumParameter_KAppFeeSmartContract             EnumParameter = 37
	EnumParameter_GasMultiplier                    EnumParameter = 38
	EnumParameter_MaxGasPerBlock                   EnumParameter = 39
	EnumParameter_MaxGasPerTX                      EnumParameter = 40
)

// Enum value maps for EnumParameter.
var (
	EnumParameter_name = map[int32]string{
		0:  "FeePerDataByte",
		1:  "KAppFeeCreateValidator",
		2:  "KAppFeeCreateAsset",
		3:  "MaxEpochsUnclaimed",
		4:  "MinSelfDelegatedAmount",
		5:  "MinTotalDelegatedAmount",
		6:  "BlockRewards",
		7:  "StakingRewards",
		8:  "KAppFeeTransfer",
		9:  "KAppFeeAssetTrigger",
		10: "KAppFeeValidatorConfig",
		11: "KAppFeeFreeze",
		12: "KAppFeeUnfreeze",
		13: "KAppFeeDelegate",
		14: "KAppFeeUndelegate",
		15: "KAppFeeWithdraw",
		16: "KAppFeeClaim",
		17: "KAppFeeUnjail",
		18: "KAppFeeSetAccountName",
		19: "KAppFeeProposal",
		20: "KAppFeeVote",
		21: "KAppFeeConfigITO",
		22: "KAppFeeSetITOPrices",
		23: "KAppFeeBuy",
		24: "KAppFeeSell",
		25: "KAppFeeCancelMarketOrder",
		26: "KAppFeeCreateMarketplace",
		27: "KAppFeeConfigMarketplace",
		28: "KAppFeeUpdateAccountPermission",
		29: "MaxNFTMintBatch",
		30: "MinKFIStakedToEnableProposals",
		31: "MinKLVBucketAmount",
		32: "MaxBucketSize",
		33: "LeaderValidatorRewardsPercentage",
		34: "ProposalMaxEpochsDuration",
		35: "KAppFeeITOTrigger",
		36: "KAppFeeDeposit",
		37: "KAppFeeSmartContract",
		38: "GasMultiplier",
		39: "MaxGasPerBlock",
		40: "MaxGasPerTX",
	}
	EnumParameter_value = map[string]int32{
		"FeePerDataByte":                   0,
		"KAppFeeCreateValidator":           1,
		"KAppFeeCreateAsset":               2,
		"MaxEpochsUnclaimed":               3,
		"MinSelfDelegatedAmount":           4,
		"MinTotalDelegatedAmount":          5,
		"BlockRewards":                     6,
		"StakingRewards":                   7,
		"KAppFeeTransfer":                  8,
		"KAppFeeAssetTrigger":              9,
		"KAppFeeValidatorConfig":           10,
		"KAppFeeFreeze":                    11,
		"KAppFeeUnfreeze":                  12,
		"KAppFeeDelegate":                  13,
		"KAppFeeUndelegate":                14,
		"KAppFeeWithdraw":                  15,
		"KAppFeeClaim":                     16,
		"KAppFeeUnjail":                    17,
		"KAppFeeSetAccountName":            18,
		"KAppFeeProposal":                  19,
		"KAppFeeVote":                      20,
		"KAppFeeConfigITO":                 21,
		"KAppFeeSetITOPrices":              22,
		"KAppFeeBuy":                       23,
		"KAppFeeSell":                      24,
		"KAppFeeCancelMarketOrder":         25,
		"KAppFeeCreateMarketplace":         26,
		"KAppFeeConfigMarketplace":         27,
		"KAppFeeUpdateAccountPermission":   28,
		"MaxNFTMintBatch":                  29,
		"MinKFIStakedToEnableProposals":    30,
		"MinKLVBucketAmount":               31,
		"MaxBucketSize":                    32,
		"LeaderValidatorRewardsPercentage": 33,
		"ProposalMaxEpochsDuration":        34,
		"KAppFeeITOTrigger":                35,
		"KAppFeeDeposit":                   36,
		"KAppFeeSmartContract":             37,
		"GasMultiplier":                    38,
		"MaxGasPerBlock":                   39,
		"MaxGasPerTX":                      40,
	}
)

func (x EnumParameter) Enum() *EnumParameter {
	p := new(EnumParameter)
	*p = x
	return p
}

func (x EnumParameter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumParameter) Descriptor() protoreflect.EnumDescriptor {
	return file_proposal_proto_enumTypes[1].Descriptor()
}

func (EnumParameter) Type() protoreflect.EnumType {
	return &file_proposal_proto_enumTypes[1]
}

func (x EnumParameter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumParameter.Descriptor instead.
func (EnumParameter) EnumDescriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{1}
}

type ProposalData_EnumProposalStatus int32

const (
	ProposalData_ActiveProposal   ProposalData_EnumProposalStatus = 0
	ProposalData_ApprovedProposal ProposalData_EnumProposalStatus = 1
	ProposalData_DeniedProposal   ProposalData_EnumProposalStatus = 2
)

// Enum value maps for ProposalData_EnumProposalStatus.
var (
	ProposalData_EnumProposalStatus_name = map[int32]string{
		0: "ActiveProposal",
		1: "ApprovedProposal",
		2: "DeniedProposal",
	}
	ProposalData_EnumProposalStatus_value = map[string]int32{
		"ActiveProposal":   0,
		"ApprovedProposal": 1,
		"DeniedProposal":   2,
	}
)

func (x ProposalData_EnumProposalStatus) Enum() *ProposalData_EnumProposalStatus {
	p := new(ProposalData_EnumProposalStatus)
	*p = x
	return p
}

func (x ProposalData_EnumProposalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProposalData_EnumProposalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proposal_proto_enumTypes[2].Descriptor()
}

func (ProposalData_EnumProposalStatus) Type() protoreflect.EnumType {
	return &file_proposal_proto_enumTypes[2]
}

func (x ProposalData_EnumProposalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProposalData_EnumProposalStatus.Descriptor instead.
func (ProposalData_EnumProposalStatus) EnumDescriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{3, 0}
}

type ProposalData_VoteDetail_EnumVoteType int32

const (
	ProposalData_VoteDetail_Yes ProposalData_VoteDetail_EnumVoteType = 0
	ProposalData_VoteDetail_No  ProposalData_VoteDetail_EnumVoteType = 1
)

// Enum value maps for ProposalData_VoteDetail_EnumVoteType.
var (
	ProposalData_VoteDetail_EnumVoteType_name = map[int32]string{
		0: "Yes",
		1: "No",
	}
	ProposalData_VoteDetail_EnumVoteType_value = map[string]int32{
		"Yes": 0,
		"No":  1,
	}
)

func (x ProposalData_VoteDetail_EnumVoteType) Enum() *ProposalData_VoteDetail_EnumVoteType {
	p := new(ProposalData_VoteDetail_EnumVoteType)
	*p = x
	return p
}

func (x ProposalData_VoteDetail_EnumVoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProposalData_VoteDetail_EnumVoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_proposal_proto_enumTypes[3].Descriptor()
}

func (ProposalData_VoteDetail_EnumVoteType) Type() protoreflect.EnumType {
	return &file_proposal_proto_enumTypes[3]
}

func (x ProposalData_VoteDetail_EnumVoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProposalData_VoteDetail_EnumVoteType.Descriptor instead.
func (ProposalData_VoteDetail_EnumVoteType) EnumDescriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{3, 0, 0}
}

type ProposalController struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ProposalCount    uint64                      `protobuf:"varint,1,opt,name=ProposalCount,json=proposalCount,proto3" json:"ProposalCount,omitempty"`
	ActiveParameters map[int32]*Parameter        `protobuf:"bytes,2,rep,name=ActiveParameters,json=activeParameters,proto3" json:"ActiveParameters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveProposals  map[uint32]*ActiveProposals `protobuf:"bytes,3,rep,name=ActiveProposals,json=activeProposals,proto3" json:"ActiveProposals,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProposalController) Reset() {
	*x = ProposalController{}
	mi := &file_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalController) ProtoMessage() {}

func (x *ProposalController) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalController.ProtoReflect.Descriptor instead.
func (*ProposalController) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalController) GetProposalCount() uint64 {
	if x != nil {
		return x.ProposalCount
	}
	return 0
}

func (x *ProposalController) GetActiveParameters() map[int32]*Parameter {
	if x != nil {
		return x.ActiveParameters
	}
	return nil
}

func (x *ProposalController) GetActiveProposals() map[uint32]*ActiveProposals {
	if x != nil {
		return x.ActiveProposals
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EnumType               `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=proto.EnumType" json:"Type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_proposal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *Parameter) GetType() EnumType {
	if x != nil {
		return x.Type
	}
	return EnumType_Bool
}

func (x *Parameter) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ActiveProposals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalIDs   []uint64               `protobuf:"varint,1,rep,packed,name=ProposalIDs,json=proposalIds,proto3" json:"ProposalIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveProposals) Reset() {
	*x = ActiveProposals{}
	mi := &file_proposal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveProposals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveProposals) ProtoMessage() {}

func (x *ActiveProposals) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveProposals.ProtoReflect.Descriptor instead.
func (*ActiveProposals) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveProposals) GetProposalIDs() []uint64 {
	if x != nil {
		return x.ProposalIDs
	}
	return nil
}

type ProposalData struct {
	state          protoimpl.MessageState              `protogen:"open.v1"`
	Proposer       []byte                              `protobuf:"bytes,1,opt,name=Proposer,json=proposer,proto3" json:"Proposer,omitempty"`
	TXHash         []byte                              `protobuf:"bytes,2,opt,name=TXHash,json=txHash,proto3" json:"TXHash,omitempty"`
	ProposalStatus ProposalData_EnumProposalStatus     `protobuf:"varint,3,opt,name=ProposalStatus,json=proposalStatus,proto3,enum=proto.ProposalData_EnumProposalStatus" json:"ProposalStatus,omitempty"`
	Parameters     map[int32][]byte                    `protobuf:"bytes,4,rep,name=Parameters,json=parameters,proto3" json:"Parameters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description    []byte                              `protobuf:"bytes,5,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	EpochStart     uint32                              `protobuf:"varint,6,opt,name=EpochStart,json=epochStart,proto3" json:"EpochStart,omitempty"`
	EpochEnd       uint32                              `protobuf:"varint,7,opt,name=EpochEnd,json=epochEnd,proto3" json:"EpochEnd,omitempty"`
	Votes          map[int32]int64                     `protobuf:"bytes,8,rep,name=Votes,json=votes,proto3" json:"Votes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Timestamp      int64                               `protobuf:"varint,9,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Voters         map[string]*ProposalData_VoteDetail `protobuf:"bytes,10,rep,name=Voters,json=voters,proto3" json:"Voters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalStaked    int64                               `protobuf:"varint,11,opt,name=TotalStaked,json=totalStaked,proto3" json:"TotalStaked,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProposalData) Reset() {
	*x = ProposalData{}
	mi := &file_proposal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalData) ProtoMessage() {}

func (x *ProposalData) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalData.ProtoReflect.Descriptor instead.
func (*ProposalData) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *ProposalData) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *ProposalData) GetTXHash() []byte {
	if x != nil {
		return x.TXHash
	}
	return nil
}

func (x *ProposalData) GetProposalStatus() ProposalData_EnumProposalStatus {
	if x != nil {
		return x.ProposalStatus
	}
	return ProposalData_ActiveProposal
}

func (x *ProposalData) GetParameters() map[int32][]byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProposalData) GetDescription() []byte {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *ProposalData) GetEpochStart() uint32 {
	if x != nil {
		return x.EpochStart
	}
	return 0
}

func (x *ProposalData) GetEpochEnd() uint32 {
	if x != nil {
		return x.EpochEnd
	}
	return 0
}

func (x *ProposalData) GetVotes() map[int32]int64 {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *ProposalData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposalData) GetVoters() map[string]*ProposalData_VoteDetail {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *ProposalData) GetTotalStaked() int64 {
	if x != nil {
		return x.TotalStaked
	}
	return 0
}

type ProposalData_VoteDetail struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          ProposalData_VoteDetail_EnumVoteType `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=proto.ProposalData_VoteDetail_EnumVoteType" json:"Type,omitempty"`
	Amount        int64                                `protobuf:"varint,2,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Timestamp     int64                                `protobuf:"varint,3,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalData_VoteDetail) Reset() {
	*x = ProposalData_VoteDetail{}
	mi := &file_proposal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalData_VoteDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalData_VoteDetail) ProtoMessage() {}

func (x *ProposalData_VoteDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalData_VoteDetail.ProtoReflect.Descriptor instead.
func (*ProposalData_VoteDetail) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ProposalData_VoteDetail) GetType() ProposalData_VoteDetail_EnumVoteType {
	if x != nil {
		return x.Type
	}
	return ProposalData_VoteDetail_Yes
}

func (x *ProposalData_VoteDetail) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProposalData_VoteDetail) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proposal_proto protoreflect.FileDescriptor

const file_proposal_proto_rawDesc = "" +
	"\n" +
	"\x0eproposal.proto\x12\x05proto\"\xa4\x03\n" +
	"\x12ProposalController\x12$\n" +
	"\rProposalCount\x18\x01 \x01(\x04R\rproposalCount\x12[\n" +
	"\x10ActiveParameters\x18\x02 \x03(\v2/.proto.ProposalController.ActiveParametersEntryR\x10activeParameters\x12X\n" +
	"\x0fActiveProposals\x18\x03 \x03(\v2..proto.ProposalController.ActiveProposalsEntryR\x0factiveProposals\x1aU\n" +
	"\x15ActiveParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.ParameterR\x05value:\x028\x01\x1aZ\n" +
	"\x14ActiveProposalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.ActiveProposalsR\x05value:\x028\x01\"F\n" +
	"\tParameter\x12#\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x0f.proto.EnumTypeR\x04type\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\fR\x05value\"3\n" +
	"\x0fActiveProposals\x12 \n" +
	"\vProposalIDs\x18\x01 \x03(\x04R\vproposalIds\"\xb3\a\n" +
	"\fProposalData\x12\x1a\n" +
	"\bProposer\x18\x01 \x01(\fR\bproposer\x12\x16\n" +
	"\x06TXHash\x18\x02 \x01(\fR\x06txHash\x12N\n" +
	"\x0eProposalStatus\x18\x03 \x01(\x0e2&.proto.ProposalData.EnumProposalStatusR\x0eproposalStatus\x12C\n" +
	"\n" +
	"Parameters\x18\x04 \x03(\v2#.proto.ProposalData.ParametersEntryR\n" +
	"parameters\x12 \n" +
	"\vDescription\x18\x05 \x01(\fR\vdescription\x12\x1e\n" +
	"\n" +
	"EpochStart\x18\x06 \x01(\rR\n" +
	"epochStart\x12\x1a\n" +
	"\bEpochEnd\x18\a \x01(\rR\bepochEnd\x124\n" +
	"\x05Votes\x18\b \x03(\v2\x1e.proto.ProposalData.VotesEntryR\x05votes\x12\x1c\n" +
	"\tTimestamp\x18\t \x01(\x03R\ttimestamp\x127\n" +
	"\x06Voters\x18\n" +
	" \x03(\v2\x1f.proto.ProposalData.VotersEntryR\x06voters\x12 \n" +
	"\vTotalStaked\x18\v \x01(\x03R\vtotalStaked\x1a\xa4\x01\n" +
	"\n" +
	"VoteDetail\x12?\n" +
	"\x04Type\x18\x01 \x01(\x0e2+.proto.ProposalData.VoteDetail.EnumVoteTypeR\x04type\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06amount\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x1f\n" +
	"\fEnumVoteType\x12\a\n" +
	"\x03Yes\x10\x00\x12\x06\n" +
	"\x02No\x10\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"VotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aY\n" +
	"\vVotersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.proto.ProposalData.VoteDetailR\x05value:\x028\x01\"R\n" +
	"\x12EnumProposalStatus\x12\x12\n" +
	"\x0eActiveProposal\x10\x00\x12\x14\n" +
	"\x10ApprovedProposal\x10\x01\x12\x12\n" +
	"\x0eDeniedProposal\x10\x02*\xbe\x01\n" +
	"\bEnumType\x12\b\n" +
	"\x04Bool\x10\x00\x12\b\n" +
	"\x04Int8\x10\x01\x12\t\n" +
	"\x05Int16\x10\x02\x12\t\n" +
	"\x05Int32\x10\x03\x12\t\n" +
	"\x05Int64\x10\x04\x12\t\n" +
	"\x05Uint8\x10\x05\x12\n" +
	"\n" +
	"\x06Uint16\x10\x06\x12\n" +
	"\n" +
	"\x06Uint32\x10\a\x12\n" +
	"\n" +
	"\x06Uint64\x10\b\x12\v\n" +
	"\aFloat32\x10\t\x12\v\n" +
	"\aFloat64\x10\n" +
	"\x12\r\n" +
	"\tComplex64\x10\v\x12\x0e\n" +
	"\n" +
	"Complex128\x10\f\x12\n" +
	"\n" +
	"\x06String\x10\r\x12\t\n" +
	"\x05Bytes\x10\x0e*\xda\a\n" +
	"\rEnumParameter\x12\x12\n" +
	"\x0eFeePerDataByte\x10\x00\x12\x1a\n" +
	"\x16KAppFeeCreateValidator\x10\x01\x12\x16\n" +
	"\x12KAppFeeCreateAsset\x10\x02\x12\x16\n" +
	"\x12MaxEpochsUnclaimed\x10\x03\x12\x1a\n" +
	"\x16MinSelfDelegatedAmount\x10\x04\x12\x1b\n" +
	"\x17MinTotalDelegatedAmount\x10\x05\x12\x10\n" +
	"\fBlockRewards\x10\x06\x12\x12\n" +
	"\x0eStakingRewards\x10\a\x12\x13\n" +
	"\x0fKAppFeeTransfer\x10\b\x12\x17\n" +
	"\x13KAppFeeAssetTrigger\x10\t\x12\x1a\n" +
	"\x16KAppFeeValidatorConfig\x10\n" +
	"\x12\x11\n" +
	"\rKAppFeeFreeze\x10\v\x12\x13\n" +
	"\x0fKAppFeeUnfreeze\x10\f\x12\x13\n" +
	"\x0fKAppFeeDelegate\x10\r\x12\x15\n" +
	"\x11KAppFeeUndelegate\x10\x0e\x12\x13\n" +
	"\x0fKAppFeeWithdraw\x10\x0f\x12\x10\n" +
	"\fKAppFeeClaim\x10\x10\x12\x11\n" +
	"\rKAppFeeUnjail\x10\x11\x12\x19\n" +
	"\x15KAppFeeSetAccountName\x10\x12\x12\x13\n" +
	"\x0fKAppFeeProposal\x10\x13\x12\x0f\n" +
	"\vKAppFeeVote\x10\x14\x12\x14\n" +
	"\x10KAppFeeConfigITO\x10\x15\x12\x17\n" +
	"\x13KAppFeeSetITOPrices\x10\x16\x12\x0e\n" +
	"\n" +
	"KAppFeeBuy\x10\x17\x12\x0f\n" +
	"\vKAppFeeSell\x10\x18\x12\x1c\n" +
	"\x18KAppFeeCancelMarketOrder\x10\x19\x12\x1c\n" +
	"\x18KAppFeeCreateMarketplace\x10\x1a\x12\x1c\n" +
	"\x18KAppFeeConfigMarketplace\x10\x1b\x12\"\n" +
	"\x1eKAppFeeUpdateAccountPermission\x10\x1c\x12\x13\n" +
	"\x0fMaxNFTMintBatch\x10\x1d\x12!\n" +
	"\x1dMinKFIStakedToEnableProposals\x10\x1e\x12\x16\n" +
	"\x12MinKLVBucketAmount\x10\x1f\x12\x11\n" +
	"\rMaxBucketSize\x10 \x12$\n" +
	" LeaderValidatorRewardsPercentage\x10!\x12\x1d\n" +
	"\x19ProposalMaxEpochsDuration\x10\"\x12\x15\n" +
	"\x11KAppFeeITOTrigger\x10#\x12\x12\n" +
	"\x0eKAppFeeDeposit\x10$\x12\x18\n" +
	"\x14KAppFeeSmartContract\x10%\x12\x11\n" +
	"\rGasMultiplier\x10&\x12\x12\n" +
	"\x0eMaxGasPerBlock\x10'\x12\x0f\n" +
	"\vMaxGasPerTX\x10(B\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_proposal_proto_rawDescOnce sync.Once
	file_proposal_proto_rawDescData []byte
)

func file_proposal_proto_rawDescGZIP() []byte {
	file_proposal_proto_rawDescOnce.Do(func() {
		file_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proposal_proto_rawDesc), len(file_proposal_proto_rawDesc)))
	})
	return file_proposal_proto_rawDescData
}

var file_proposal_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proposal_proto_goTypes = []any{
	(EnumType)(0),                             // 0: proto.EnumType
	(EnumParameter)(0),                        // 1: proto.EnumParameter
	(ProposalData_EnumProposalStatus)(0),      // 2: proto.ProposalData.EnumProposalStatus
	(ProposalData_VoteDetail_EnumVoteType)(0), // 3: proto.ProposalData.VoteDetail.EnumVoteType
	(*ProposalController)(nil),                // 4: proto.ProposalController
	(*Parameter)(nil),                         // 5: proto.Parameter
	(*ActiveProposals)(nil),                   // 6: proto.ActiveProposals
	(*ProposalData)(nil),                      // 7: proto.ProposalData
	nil,                                       // 8: proto.ProposalController.ActiveParametersEntry
	nil,                                       // 9: proto.ProposalController.ActiveProposalsEntry
	(*ProposalData_VoteDetail)(nil),           // 10: proto.ProposalData.VoteDetail
	nil,                                       // 11: proto.ProposalData.ParametersEntry
	nil,                                       // 12: proto.ProposalData.VotesEntry
	nil,                                       // 13: proto.ProposalData.VotersEntry
}
var file_proposal_proto_depIdxs = []int32{
	8,  // 0: proto.ProposalController.ActiveParameters:type_name -> proto.ProposalController.ActiveParametersEntry
	9,  // 1: proto.ProposalController.ActiveProposals:type_name -> proto.ProposalController.ActiveProposalsEntry
	0,  // 2: proto.Parameter.Type:type_name -> proto.EnumType
	2,  // 3: proto.ProposalData.ProposalStatus:type_name -> proto.ProposalData.EnumProposalStatus
	11, // 4: proto.ProposalData.Parameters:type_name -> proto.ProposalData.ParametersEntry
	12, // 5: proto.ProposalData.Votes:type_name -> proto.ProposalData.VotesEntry
	13, // 6: proto.ProposalData.Voters:type_name -> proto.ProposalData.VotersEntry
	5,  // 7: proto.ProposalController.ActiveParametersEntry.value:type_name -> proto.Parameter
	6,  // 8: proto.ProposalController.ActiveProposalsEntry.value:type_name -> proto.ActiveProposals
	3,  // 9: proto.ProposalData.VoteDetail.Type:type_name -> proto.ProposalData.VoteDetail.EnumVoteType
	10, // 10: proto.ProposalData.VotersEntry.value:type_name -> proto.ProposalData.VoteDetail
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proposal_proto_init() }
func file_proposal_proto_init() {
	if File_proposal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proposal_proto_rawDesc), len(file_proposal_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proposal_proto_goTypes,
		DependencyIndexes: file_proposal_proto_depIdxs,
		EnumInfos:         file_proposal_proto_enumTypes,
		MessageInfos:      file_proposal_proto_msgTypes,
	}.Build()
	File_proposal_proto = out.File
	file_proposal_proto_goTypes = nil
	file_proposal_proto_depIdxs = nil
}
