// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: staking.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StakingData_EnumInterestType int32

const (
	StakingData_APRI StakingData_EnumInterestType = 0
	StakingData_FPRI StakingData_EnumInterestType = 1
)

// Enum value maps for StakingData_EnumInterestType.
var (
	StakingData_EnumInterestType_name = map[int32]string{
		0: "APRI",
		1: "FPRI",
	}
	StakingData_EnumInterestType_value = map[string]int32{
		"APRI": 0,
		"FPRI": 1,
	}
)

func (x StakingData_EnumInterestType) Enum() *StakingData_EnumInterestType {
	p := new(StakingData_EnumInterestType)
	*p = x
	return p
}

func (x StakingData_EnumInterestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StakingData_EnumInterestType) Descriptor() protoreflect.EnumDescriptor {
	return file_staking_proto_enumTypes[0].Descriptor()
}

func (StakingData_EnumInterestType) Type() protoreflect.EnumType {
	return &file_staking_proto_enumTypes[0]
}

func (x StakingData_EnumInterestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StakingData_EnumInterestType.Descriptor instead.
func (StakingData_EnumInterestType) EnumDescriptor() ([]byte, []int) {
	return file_staking_proto_rawDescGZIP(), []int{0, 0}
}

type StakingData struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	InterestType        StakingData_EnumInterestType `protobuf:"varint,1,opt,name=InterestType,json=interestType,proto3,enum=proto.StakingData_EnumInterestType" json:"InterestType,omitempty"`
	APR                 []*APRData                   `protobuf:"bytes,2,rep,name=APR,json=apr,proto3" json:"APR,omitempty"`
	FPR                 []*FPRData                   `protobuf:"bytes,3,rep,name=FPR,json=fpr,proto3" json:"FPR,omitempty"`
	CurrentFPRAmount    int64                        `protobuf:"varint,4,opt,name=CurrentFPRAmount,json=currentFPRAmount,proto3" json:"CurrentFPRAmount,omitempty"`
	TotalStaked         int64                        `protobuf:"varint,5,opt,name=TotalStaked,json=totalStaked,proto3" json:"TotalStaked,omitempty"`
	MinEpochsToClaim    uint32                       `protobuf:"varint,6,opt,name=MinEpochsToClaim,json=minEpochsToClaim,proto3" json:"MinEpochsToClaim,omitempty"`
	MinEpochsToUnstake  uint32                       `protobuf:"varint,7,opt,name=MinEpochsToUnstake,json=minEpochsToUnstake,proto3" json:"MinEpochsToUnstake,omitempty"`
	MinEpochsToWithdraw uint32                       `protobuf:"varint,8,opt,name=MinEpochsToWithdraw,json=minEpochsToWithdraw,proto3" json:"MinEpochsToWithdraw,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StakingData) Reset() {
	*x = StakingData{}
	mi := &file_staking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingData) ProtoMessage() {}

func (x *StakingData) ProtoReflect() protoreflect.Message {
	mi := &file_staking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingData.ProtoReflect.Descriptor instead.
func (*StakingData) Descriptor() ([]byte, []int) {
	return file_staking_proto_rawDescGZIP(), []int{0}
}

func (x *StakingData) GetInterestType() StakingData_EnumInterestType {
	if x != nil {
		return x.InterestType
	}
	return StakingData_APRI
}

func (x *StakingData) GetAPR() []*APRData {
	if x != nil {
		return x.APR
	}
	return nil
}

func (x *StakingData) GetFPR() []*FPRData {
	if x != nil {
		return x.FPR
	}
	return nil
}

func (x *StakingData) GetCurrentFPRAmount() int64 {
	if x != nil {
		return x.CurrentFPRAmount
	}
	return 0
}

func (x *StakingData) GetTotalStaked() int64 {
	if x != nil {
		return x.TotalStaked
	}
	return 0
}

func (x *StakingData) GetMinEpochsToClaim() uint32 {
	if x != nil {
		return x.MinEpochsToClaim
	}
	return 0
}

func (x *StakingData) GetMinEpochsToUnstake() uint32 {
	if x != nil {
		return x.MinEpochsToUnstake
	}
	return 0
}

func (x *StakingData) GetMinEpochsToWithdraw() uint32 {
	if x != nil {
		return x.MinEpochsToWithdraw
	}
	return 0
}

type APRData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	Value         uint32                 `protobuf:"varint,3,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APRData) Reset() {
	*x = APRData{}
	mi := &file_staking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APRData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APRData) ProtoMessage() {}

func (x *APRData) ProtoReflect() protoreflect.Message {
	mi := &file_staking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APRData.ProtoReflect.Descriptor instead.
func (*APRData) Descriptor() ([]byte, []int) {
	return file_staking_proto_rawDescGZIP(), []int{1}
}

func (x *APRData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *APRData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *APRData) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FPRData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   int64                  `protobuf:"varint,1,opt,name=TotalAmount,json=totalAmount,proto3" json:"TotalAmount,omitempty"`
	TotalStaked   int64                  `protobuf:"varint,2,opt,name=TotalStaked,json=totalStaked,proto3" json:"TotalStaked,omitempty"`
	Epoch         uint32                 `protobuf:"varint,4,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	TotalClaimed  int64                  `protobuf:"varint,5,opt,name=TotalClaimed,json=totalClaimed,proto3" json:"TotalClaimed,omitempty"`
	KDAS          map[string]*KDAFPRData `protobuf:"bytes,6,rep,name=KDAS,json=kdas,omitempty,proto3" json:"KDAS,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FPRData) Reset() {
	*x = FPRData{}
	mi := &file_staking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FPRData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPRData) ProtoMessage() {}

func (x *FPRData) ProtoReflect() protoreflect.Message {
	mi := &file_staking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPRData.ProtoReflect.Descriptor instead.
func (*FPRData) Descriptor() ([]byte, []int) {
	return file_staking_proto_rawDescGZIP(), []int{2}
}

func (x *FPRData) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *FPRData) GetTotalStaked() int64 {
	if x != nil {
		return x.TotalStaked
	}
	return 0
}

func (x *FPRData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *FPRData) GetTotalClaimed() int64 {
	if x != nil {
		return x.TotalClaimed
	}
	return 0
}

func (x *FPRData) GetKDAS() map[string]*KDAFPRData {
	if x != nil {
		return x.KDAS
	}
	return nil
}

type KDAFPRData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   int64                  `protobuf:"varint,1,opt,name=TotalAmount,json=totalAmount,proto3" json:"TotalAmount,omitempty"`
	TotalClaimed  int64                  `protobuf:"varint,2,opt,name=TotalClaimed,json=totalClaimed,proto3" json:"TotalClaimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KDAFPRData) Reset() {
	*x = KDAFPRData{}
	mi := &file_staking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KDAFPRData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDAFPRData) ProtoMessage() {}

func (x *KDAFPRData) ProtoReflect() protoreflect.Message {
	mi := &file_staking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDAFPRData.ProtoReflect.Descriptor instead.
func (*KDAFPRData) Descriptor() ([]byte, []int) {
	return file_staking_proto_rawDescGZIP(), []int{3}
}

func (x *KDAFPRData) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *KDAFPRData) GetTotalClaimed() int64 {
	if x != nil {
		return x.TotalClaimed
	}
	return 0
}

var File_staking_proto protoreflect.FileDescriptor

const file_staking_proto_rawDesc = "" +
	"\n" +
	"\rstaking.proto\x12\x05proto\"\x9e\x03\n" +
	"\vStakingData\x12G\n" +
	"\fInterestType\x18\x01 \x01(\x0e2#.proto.StakingData.EnumInterestTypeR\finterestType\x12 \n" +
	"\x03APR\x18\x02 \x03(\v2\x0e.proto.APRDataR\x03apr\x12 \n" +
	"\x03FPR\x18\x03 \x03(\v2\x0e.proto.FPRDataR\x03fpr\x12*\n" +
	"\x10CurrentFPRAmount\x18\x04 \x01(\x03R\x10currentFPRAmount\x12 \n" +
	"\vTotalStaked\x18\x05 \x01(\x03R\vtotalStaked\x12*\n" +
	"\x10MinEpochsToClaim\x18\x06 \x01(\rR\x10minEpochsToClaim\x12.\n" +
	"\x12MinEpochsToUnstake\x18\a \x01(\rR\x12minEpochsToUnstake\x120\n" +
	"\x13MinEpochsToWithdraw\x18\b \x01(\rR\x13minEpochsToWithdraw\"&\n" +
	"\x10EnumInterestType\x12\b\n" +
	"\x04APRI\x10\x00\x12\b\n" +
	"\x04FPRI\x10\x01\"S\n" +
	"\aAPRData\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05Epoch\x18\x02 \x01(\rR\x05epoch\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\rR\x05value\"\x8b\x02\n" +
	"\aFPRData\x12 \n" +
	"\vTotalAmount\x18\x01 \x01(\x03R\vtotalAmount\x12 \n" +
	"\vTotalStaked\x18\x02 \x01(\x03R\vtotalStaked\x12\x14\n" +
	"\x05Epoch\x18\x04 \x01(\rR\x05epoch\x12\"\n" +
	"\fTotalClaimed\x18\x05 \x01(\x03R\ftotalClaimed\x126\n" +
	"\x04KDAS\x18\x06 \x03(\v2\x18.proto.FPRData.KDASEntryR\x0ekdas,omitempty\x1aJ\n" +
	"\tKDASEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.KDAFPRDataR\x05value:\x028\x01\"R\n" +
	"\n" +
	"KDAFPRData\x12 \n" +
	"\vTotalAmount\x18\x01 \x01(\x03R\vtotalAmount\x12\"\n" +
	"\fTotalClaimed\x18\x02 \x01(\x03R\ftotalClaimedB\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_staking_proto_rawDescOnce sync.Once
	file_staking_proto_rawDescData []byte
)

func file_staking_proto_rawDescGZIP() []byte {
	file_staking_proto_rawDescOnce.Do(func() {
		file_staking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staking_proto_rawDesc), len(file_staking_proto_rawDesc)))
	})
	return file_staking_proto_rawDescData
}

var file_staking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_staking_proto_goTypes = []any{
	(StakingData_EnumInterestType)(0), // 0: proto.StakingData.EnumInterestType
	(*StakingData)(nil),               // 1: proto.StakingData
	(*APRData)(nil),                   // 2: proto.APRData
	(*FPRData)(nil),                   // 3: proto.FPRData
	(*KDAFPRData)(nil),                // 4: proto.KDAFPRData
	nil,                               // 5: proto.FPRData.KDASEntry
}
var file_staking_proto_depIdxs = []int32{
	0, // 0: proto.StakingData.InterestType:type_name -> proto.StakingData.EnumInterestType
	2, // 1: proto.StakingData.APR:type_name -> proto.APRData
	3, // 2: proto.StakingData.FPR:type_name -> proto.FPRData
	5, // 3: proto.FPRData.KDAS:type_name -> proto.FPRData.KDASEntry
	4, // 4: proto.FPRData.KDASEntry.value:type_name -> proto.KDAFPRData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_staking_proto_init() }
func file_staking_proto_init() {
	if File_staking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staking_proto_rawDesc), len(file_staking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staking_proto_goTypes,
		DependencyIndexes: file_staking_proto_depIdxs,
		EnumInfos:         file_staking_proto_enumTypes,
		MessageInfos:      file_staking_proto_msgTypes,
	}.Build()
	File_staking_proto = out.File
	file_staking_proto_goTypes = nil
	file_staking_proto_depIdxs = nil
}
