// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.27.0
// source: systemAccount.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Circulation int64       `protobuf:"varint,1,opt,name=Circulation,json=circulation,proto3" json:"Circulation,omitempty"`
	MaxSupply   int64       `protobuf:"varint,2,opt,name=MaxSupply,json=maxSupply,proto3" json:"MaxSupply,omitempty"`
	Metadata    *MetaV2Data `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
}

func (x *MetaV2) Reset() {
	*x = MetaV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_systemAccount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaV2) ProtoMessage() {}

func (x *MetaV2) ProtoReflect() protoreflect.Message {
	mi := &file_systemAccount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaV2.ProtoReflect.Descriptor instead.
func (*MetaV2) Descriptor() ([]byte, []int) {
	return file_systemAccount_proto_rawDescGZIP(), []int{0}
}

func (x *MetaV2) GetCirculation() int64 {
	if x != nil {
		return x.Circulation
	}
	return 0
}

func (x *MetaV2) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *MetaV2) GetMetadata() *MetaV2Data {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetaV2Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       []byte `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Hash       []byte `protobuf:"bytes,2,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	Attributes []byte `protobuf:"bytes,3,opt,name=Attributes,json=attributes,proto3" json:"Attributes,omitempty"`
}

func (x *MetaV2Data) Reset() {
	*x = MetaV2Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_systemAccount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaV2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaV2Data) ProtoMessage() {}

func (x *MetaV2Data) ProtoReflect() protoreflect.Message {
	mi := &file_systemAccount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaV2Data.ProtoReflect.Descriptor instead.
func (*MetaV2Data) Descriptor() ([]byte, []int) {
	return file_systemAccount_proto_rawDescGZIP(), []int{1}
}

func (x *MetaV2Data) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MetaV2Data) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MetaV2Data) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_systemAccount_proto protoreflect.FileDescriptor

var file_systemAccount_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x06,
	0x4d, 0x65, 0x74, 0x61, 0x56, 0x32, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x69, 0x72, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x69, 0x72,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x56, 0x32, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x56, 0x32, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x6b, 0x61, 0x70, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_systemAccount_proto_rawDescOnce sync.Once
	file_systemAccount_proto_rawDescData = file_systemAccount_proto_rawDesc
)

func file_systemAccount_proto_rawDescGZIP() []byte {
	file_systemAccount_proto_rawDescOnce.Do(func() {
		file_systemAccount_proto_rawDescData = protoimpl.X.CompressGZIP(file_systemAccount_proto_rawDescData)
	})
	return file_systemAccount_proto_rawDescData
}

var file_systemAccount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_systemAccount_proto_goTypes = []interface{}{
	(*MetaV2)(nil),     // 0: proto.MetaV2
	(*MetaV2Data)(nil), // 1: proto.MetaV2Data
}
var file_systemAccount_proto_depIdxs = []int32{
	1, // 0: proto.MetaV2.Metadata:type_name -> proto.MetaV2Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_systemAccount_proto_init() }
func file_systemAccount_proto_init() {
	if File_systemAccount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_systemAccount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_systemAccount_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaV2Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_systemAccount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_systemAccount_proto_goTypes,
		DependencyIndexes: file_systemAccount_proto_depIdxs,
		MessageInfos:      file_systemAccount_proto_msgTypes,
	}.Build()
	File_systemAccount_proto = out.File
	file_systemAccount_proto_rawDesc = nil
	file_systemAccount_proto_goTypes = nil
	file_systemAccount_proto_depIdxs = nil
}
