// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: systemAccount.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Circulation   int64                  `protobuf:"varint,1,opt,name=Circulation,json=circulation,proto3" json:"Circulation,omitempty"`
	MaxSupply     int64                  `protobuf:"varint,2,opt,name=MaxSupply,json=maxSupply,proto3" json:"MaxSupply,omitempty"`
	Metadata      *MetaV2Data            `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaV2) Reset() {
	*x = MetaV2{}
	mi := &file_systemAccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaV2) ProtoMessage() {}

func (x *MetaV2) ProtoReflect() protoreflect.Message {
	mi := &file_systemAccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaV2.ProtoReflect.Descriptor instead.
func (*MetaV2) Descriptor() ([]byte, []int) {
	return file_systemAccount_proto_rawDescGZIP(), []int{0}
}

func (x *MetaV2) GetCirculation() int64 {
	if x != nil {
		return x.Circulation
	}
	return 0
}

func (x *MetaV2) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *MetaV2) GetMetadata() *MetaV2Data {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetaV2Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	Attributes    []byte                 `protobuf:"bytes,3,opt,name=Attributes,json=attributes,proto3" json:"Attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaV2Data) Reset() {
	*x = MetaV2Data{}
	mi := &file_systemAccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaV2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaV2Data) ProtoMessage() {}

func (x *MetaV2Data) ProtoReflect() protoreflect.Message {
	mi := &file_systemAccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaV2Data.ProtoReflect.Descriptor instead.
func (*MetaV2Data) Descriptor() ([]byte, []int) {
	return file_systemAccount_proto_rawDescGZIP(), []int{1}
}

func (x *MetaV2Data) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MetaV2Data) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MetaV2Data) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_systemAccount_proto protoreflect.FileDescriptor

const file_systemAccount_proto_rawDesc = "" +
	"\n" +
	"\x13systemAccount.proto\x12\x05proto\"w\n" +
	"\x06MetaV2\x12 \n" +
	"\vCirculation\x18\x01 \x01(\x03R\vcirculation\x12\x1c\n" +
	"\tMaxSupply\x18\x02 \x01(\x03R\tmaxSupply\x12-\n" +
	"\bMetadata\x18\x03 \x01(\v2\x11.proto.MetaV2DataR\bmetadata\"T\n" +
	"\n" +
	"MetaV2Data\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\fR\x04name\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\fR\x04hash\x12\x1e\n" +
	"\n" +
	"Attributes\x18\x03 \x01(\fR\n" +
	"attributesB\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_systemAccount_proto_rawDescOnce sync.Once
	file_systemAccount_proto_rawDescData []byte
)

func file_systemAccount_proto_rawDescGZIP() []byte {
	file_systemAccount_proto_rawDescOnce.Do(func() {
		file_systemAccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_systemAccount_proto_rawDesc), len(file_systemAccount_proto_rawDesc)))
	})
	return file_systemAccount_proto_rawDescData
}

var file_systemAccount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_systemAccount_proto_goTypes = []any{
	(*MetaV2)(nil),     // 0: proto.MetaV2
	(*MetaV2Data)(nil), // 1: proto.MetaV2Data
}
var file_systemAccount_proto_depIdxs = []int32{
	1, // 0: proto.MetaV2.Metadata:type_name -> proto.MetaV2Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_systemAccount_proto_init() }
func file_systemAccount_proto_init() {
	if File_systemAccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_systemAccount_proto_rawDesc), len(file_systemAccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_systemAccount_proto_goTypes,
		DependencyIndexes: file_systemAccount_proto_depIdxs,
		MessageInfos:      file_systemAccount_proto_msgTypes,
	}.Build()
	File_systemAccount_proto = out.File
	file_systemAccount_proto_goTypes = nil
	file_systemAccount_proto_depIdxs = nil
}
