// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: userKapps.proto

package kapps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserKDA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=Balance,json=balance,omitempty,proto3" json:"Balance,omitempty"`
	FrozenBalance int64                  `protobuf:"varint,2,opt,name=FrozenBalance,json=frozenBalance,omitempty,proto3" json:"FrozenBalance,omitempty"`
	LastClaim     *LastClaim             `protobuf:"bytes,3,opt,name=LastClaim,json=lastClaim,omitempty,proto3" json:"LastClaim,omitempty"`
	Buckets       map[string]*UserBucket `protobuf:"bytes,4,rep,name=Buckets,json=buckets,omitempty,proto3" json:"Buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MIME          []byte                 `protobuf:"bytes,5,opt,name=MIME,json=mime,omitempty,proto3" json:"MIME,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=Metadata,json=metadata,omitempty,proto3" json:"Metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKDA) Reset() {
	*x = UserKDA{}
	mi := &file_userKapps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKDA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKDA) ProtoMessage() {}

func (x *UserKDA) ProtoReflect() protoreflect.Message {
	mi := &file_userKapps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKDA.ProtoReflect.Descriptor instead.
func (*UserKDA) Descriptor() ([]byte, []int) {
	return file_userKapps_proto_rawDescGZIP(), []int{0}
}

func (x *UserKDA) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserKDA) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *UserKDA) GetLastClaim() *LastClaim {
	if x != nil {
		return x.LastClaim
	}
	return nil
}

func (x *UserKDA) GetBuckets() map[string]*UserBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *UserKDA) GetMIME() []byte {
	if x != nil {
		return x.MIME
	}
	return nil
}

func (x *UserKDA) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LastClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=Epoch,json=epoch,proto3" json:"Epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastClaim) Reset() {
	*x = LastClaim{}
	mi := &file_userKapps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastClaim) ProtoMessage() {}

func (x *LastClaim) ProtoReflect() protoreflect.Message {
	mi := &file_userKapps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastClaim.ProtoReflect.Descriptor instead.
func (*LastClaim) Descriptor() ([]byte, []int) {
	return file_userKapps_proto_rawDescGZIP(), []int{1}
}

func (x *LastClaim) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LastClaim) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type UserBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakedAt      int64                  `protobuf:"varint,1,opt,name=StakedAt,json=stakedAt,proto3" json:"StakedAt,omitempty"`
	StakedEpoch   uint32                 `protobuf:"varint,2,opt,name=StakedEpoch,json=stakedEpoch,proto3" json:"StakedEpoch,omitempty"`
	UnstakedEpoch uint32                 `protobuf:"varint,3,opt,name=UnstakedEpoch,json=unstakedEpoch,proto3" json:"UnstakedEpoch,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Delegation    []byte                 `protobuf:"bytes,5,opt,name=Delegation,json=delegation,omitempty,proto3" json:"Delegation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBucket) Reset() {
	*x = UserBucket{}
	mi := &file_userKapps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBucket) ProtoMessage() {}

func (x *UserBucket) ProtoReflect() protoreflect.Message {
	mi := &file_userKapps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBucket.ProtoReflect.Descriptor instead.
func (*UserBucket) Descriptor() ([]byte, []int) {
	return file_userKapps_proto_rawDescGZIP(), []int{2}
}

func (x *UserBucket) GetStakedAt() int64 {
	if x != nil {
		return x.StakedAt
	}
	return 0
}

func (x *UserBucket) GetStakedEpoch() uint32 {
	if x != nil {
		return x.StakedEpoch
	}
	return 0
}

func (x *UserBucket) GetUnstakedEpoch() uint32 {
	if x != nil {
		return x.UnstakedEpoch
	}
	return 0
}

func (x *UserBucket) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UserBucket) GetDelegation() []byte {
	if x != nil {
		return x.Delegation
	}
	return nil
}

var File_userKapps_proto protoreflect.FileDescriptor

const file_userKapps_proto_rawDesc = "" +
	"\n" +
	"\x0fuserKapps.proto\x12\x05proto\"\xeb\x02\n" +
	"\aUserKDA\x12\"\n" +
	"\aBalance\x18\x01 \x01(\x03R\x11balance,omitempty\x12.\n" +
	"\rFrozenBalance\x18\x02 \x01(\x03R\x17frozenBalance,omitempty\x128\n" +
	"\tLastClaim\x18\x03 \x01(\v2\x10.proto.LastClaimR\x13lastClaim,omitempty\x12?\n" +
	"\aBuckets\x18\x04 \x03(\v2\x1b.proto.UserKDA.BucketsEntryR\x11buckets,omitempty\x12\x1c\n" +
	"\x04MIME\x18\x05 \x01(\fR\x0emime,omitempty\x12$\n" +
	"\bMetadata\x18\x06 \x01(\fR\x12metadata,omitempty\x1aM\n" +
	"\fBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.UserBucketR\x05value:\x028\x01\"?\n" +
	"\tLastClaim\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05Epoch\x18\x02 \x01(\rR\x05epoch\"\xb0\x01\n" +
	"\n" +
	"UserBucket\x12\x1a\n" +
	"\bStakedAt\x18\x01 \x01(\x03R\bstakedAt\x12 \n" +
	"\vStakedEpoch\x18\x02 \x01(\rR\vstakedEpoch\x12$\n" +
	"\rUnstakedEpoch\x18\x03 \x01(\rR\runstakedEpoch\x12\x14\n" +
	"\x05Value\x18\x04 \x01(\x03R\x05value\x12(\n" +
	"\n" +
	"Delegation\x18\x05 \x01(\fR\x14delegation,omitemptyB\n" +
	"Z\b./;kappsb\x06proto3"

var (
	file_userKapps_proto_rawDescOnce sync.Once
	file_userKapps_proto_rawDescData []byte
)

func file_userKapps_proto_rawDescGZIP() []byte {
	file_userKapps_proto_rawDescOnce.Do(func() {
		file_userKapps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userKapps_proto_rawDesc), len(file_userKapps_proto_rawDesc)))
	})
	return file_userKapps_proto_rawDescData
}

var file_userKapps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userKapps_proto_goTypes = []any{
	(*UserKDA)(nil),    // 0: proto.UserKDA
	(*LastClaim)(nil),  // 1: proto.LastClaim
	(*UserBucket)(nil), // 2: proto.UserBucket
	nil,                // 3: proto.UserKDA.BucketsEntry
}
var file_userKapps_proto_depIdxs = []int32{
	1, // 0: proto.UserKDA.LastClaim:type_name -> proto.LastClaim
	3, // 1: proto.UserKDA.Buckets:type_name -> proto.UserKDA.BucketsEntry
	2, // 2: proto.UserKDA.BucketsEntry.value:type_name -> proto.UserBucket
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userKapps_proto_init() }
func file_userKapps_proto_init() {
	if File_userKapps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userKapps_proto_rawDesc), len(file_userKapps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userKapps_proto_goTypes,
		DependencyIndexes: file_userKapps_proto_depIdxs,
		MessageInfos:      file_userKapps_proto_msgTypes,
	}.Build()
	File_userKapps_proto = out.File
	file_userKapps_proto_goTypes = nil
	file_userKapps_proto_depIdxs = nil
}
