package data

import (
	"time"

	"github.com/klever-io/klever-go/data/transaction"
)

// Transaction is a structure containing all the fields that need
//
//	to be saved for a transaction. It has all the default fields
//	plus some extra information for ease of search and filter
type Transaction struct {
	Hash          string                   `json:"hash"`
	BlockNum      uint64                   `json:"blockNum,omitempty"`
	Sender        string                   `json:"sender"`
	Nonce         uint64                   `json:"nonce"`
	PermissionID  int32                    `json:"permissionID,omitempty"`
	Data          []string                 `json:"data,omitempty"`
	Timestamp     time.Duration            `json:"timestamp,omitempty"`
	KAppFee       int64                    `json:"kAppFee"`
	KDAFee        *KDAFee                  `json:"kdaFee,omitempty"`
	BandwidthFee  int64                    `json:"bandwidthFee"`
	Status        string                   `json:"status"`
	ResultCode    string                   `json:"resultCode,omitempty"`
	Version       uint32                   `json:"version,omitempty"`
	ChainID       string                   `json:"chainID,omitempty"`
	Signature     []string                 `json:"signature,omitempty"`
	SearchOrder   uint32                   `json:"searchOrder"`
	Receipts      []map[string]interface{} `json:"receipts"`
	Contracts     []*TXContract            `json:"contract"`
	Logs          *Logs                    `json:"logs,omitempty"`
	HasLogs       bool                     `json:"hasLogs,omitempty"`
	HasOperations bool                     `json:"hasOperations,omitempty"`
}

// Logs represents logs with changed fields
type Logs struct {
	ID         string        `json:"-"`
	Address    string        `json:"address"`
	ContractID int32         `json:"contractId"`
	Timestamp  time.Duration `json:"timestamp"`
	Events     []*Event      `json:"events"`
}

// Events represents the events generated by a transaction with changed fields
type Event struct {
	Address    string   `json:"address"`
	Identifier string   `json:"identifier"`
	Topics     []string `json:"topics"`
	Data       []string `json:"data"`
	Order      int      `json:"order"`
}

type KDAFee struct {
	KDA    string `json:"kda"`
	Amount int64  `json:"amount"`
}

type AssetType struct {
	Type       string `json:"type"`
	Collection string `json:"collection"`
}

type TXContract struct {
	Type       transaction.TXContract_ContractType `json:"type"`
	TypeString string                              `json:"typeString"`
	Parameter  interface{}                         `json:"parameter,omitempty"`
}

// -- TransferContract

type TransferContract struct {
	AssetID      string    `json:"assetId,omitempty"`
	ToAddress    string    `json:"toAddress,omitempty"`
	Amount       int64     `json:"amount,omitempty"`
	KDARoyalties int64     `json:"kdaRoyalties,omitempty"`
	KLVRoyalties int64     `json:"klvRoyalties,omitempty"`
	AssetType    AssetType `json:"assetType,omitempty"`
}

// -- CreateAssetContract
type CreateAssetContract struct {
	Type              string          `json:"type"`
	Name              string          `json:"name"`
	Ticker            string          `json:"ticker"`
	Logo              string          `json:"logo"`
	OwnerAddress      string          `json:"ownerAddress"`
	AdminAddress      string          `json:"adminAddress"`
	URIs              []*URI          `json:"uris"`
	Precision         uint32          `json:"precision"`
	InitialSupply     int64           `json:"initialSupply"`
	CirculatingSupply int64           `json:"circulatingSupply"`
	MaxSupply         int64           `json:"maxSupply"`
	MintedValue       int64           `json:"mintedValue"`
	BurnedValue       int64           `json:"burnedValue"`
	IssueDate         int64           `json:"issueDate"`
	Royalties         *RoyaltiesInfo  `json:"royalties"`
	Properties        *PropertiesInfo `json:"properties"`
	Attributes        *AttributesInfo `json:"attributes"`
	Staking           *Staking        `json:"staking"`
	Roles             []*RolesInfo    `json:"roles"`
	Metadata          *Meta           `json:"meta,omitempty"`
}

type RolesInfo struct {
	Address             string `json:"address"`
	HasRoleMint         bool   `json:"hasRoleMint"`
	HasRoleSetITOPrices bool   `json:"hasRoleSetITOPrices"`
	HasRoleDeposit      bool   `json:"hasRoleDeposit"`
	HasRoleTransfer     bool   `json:"hasRoleTransfer"`
}

type RoyaltiesInfo struct {
	Address            string              `json:"address,omitempty"`
	TransferPercentage []*RoyaltyDataInfo  `json:"transferPercentage"`
	TransferFixed      int64               `json:"transferFixed"`
	MarketPercentage   uint32              `json:"marketPercentage"`
	MarketFixed        int64               `json:"marketFixed"`
	ITOPercentage      uint32              `json:"itoPercentage"`
	ITOFixed           int64               `json:"itoFixed"`
	SplitRoyalties     []*RoyaltySplitInfo `json:"splitRoyalties"`
}

type RoyaltyDataInfo struct {
	Amount     int64  `json:"amount,omitempty"`
	Percentage uint32 `json:"percentage,omitempty"`
}

type RoyaltySplitInfo struct {
	Address                   string `json:"address,omitempty"`
	PercentTransferPercentage uint32 `json:"percentTransferPercentage,omitempty"`
	PercentTransferFixed      uint32 `json:"percentTransferFixed,omitempty"`
	PercentMarketPercentage   uint32 `json:"percentMarketPercentage,omitempty"`
	PercentMarketFixed        uint32 `json:"percentMarketFixed,omitempty"`
	PercentITOPercentage      uint32 `json:"percentITOPercentage,omitempty"`
	PercentITOFixed           uint32 `json:"percentITOFixed,omitempty"`
}

type PropertiesInfo struct {
	CanFreeze      bool `json:"canFreeze"`
	CanWipe        bool `json:"canWipe"`
	CanPause       bool `json:"canPause"`
	CanMint        bool `json:"canMint"`
	CanBurn        bool `json:"canBurn"`
	CanChangeOwner bool `json:"canChangeOwner"`
	CanAddRoles    bool `json:"canAddRoles"`
	LimitTransfer  bool `json:"limitTransfer"`
}

type AttributesInfo struct {
	IsPaused                 bool `json:"isPaused"`
	IsNFTMintStopped         bool `json:"isNFTMintStopped"`
	IsRoyaltiesChangeStopped bool `json:"isRoyaltiesChangeStopped"`
}

type Staking struct {
	Type                string `json:"type,omitempty"`
	APR                 uint32 `json:"apr,omitempty"`
	MinEpochsToClaim    uint32 `json:"minEpochsToClaim,omitempty"`
	MinEpochsToUnstake  uint32 `json:"minEpochsToUnstake,omitempty"`
	MinEpochsToWithdraw uint32 `json:"minEpochsToWithdraw,omitempty"`
}

type StakingData struct {
	InterestType        string     `json:"interestType"`
	APR                 []*APRData `json:"apr"`
	FPR                 []*FPRData `json:"fpr"`
	TotalStaked         int64      `json:"totalStaked"`
	CurrentFPRAmount    int64      `json:"currentFPRAmount"`
	MinEpochsToClaim    uint32     `json:"minEpochsToClaim"`
	MinEpochsToUnstake  uint32     `json:"minEpochsToUnstake"`
	MinEpochsToWithdraw uint32     `json:"minEpochsToWithdraw"`
}

type KDAPool struct {
	KDA          string `json:"kda"`
	Active       bool   `json:"active"`
	AdminAddress string `json:"adminAddress"`
	FRatioKLV    int64  `json:"fRatioKLV"`
	FRatioKDA    int64  `json:"fRatioKDA"`
}

type Meta struct {
	MaxSupply   int64    `json:"maxSupply"`
	Circulation int64    `json:"circulationSupply"`
	Metadata    Metadata `json:"metadata"`
}

type Metadata struct {
	Name       string `json:"name"`
	Hash       string `json:"hash"`
	Attributes string `json:"attributes"`
}

type KDAPoolData struct {
	OwnerAddress  string `json:"ownerAddress"`
	KDA           string `json:"kda"`
	Active        bool   `json:"active"`
	KLVBalance    int64  `json:"klvBalance"`
	KDABalance    int64  `json:"kdaBalance"`
	ConvertedFees int64  `json:"convertedFees"`
	AdminAddress  string `json:"adminAddress"`
	FRatioKLV     int64  `json:"fRatioKLV"`
	FRatioKDA     int64  `json:"fRatioKDA"`
	Hidden        *bool  `json:"hidden,omitempty"`
	Verified      *bool  `json:"verified,omitempty"`
}

type APRData struct {
	Timestamp int64  `json:"timestamp"`
	Epoch     uint32 `json:"epoch"`
	Value     uint32 `json:"value"`
}

type FPRData struct {
	TotalAmount  int64         `json:"totalAmount"`
	TotalStaked  int64         `json:"totalStaked"`
	Epoch        uint32        `json:"epoch"`
	TotalClaimed int64         `json:"TotalClaimed"`
	KDA          []*KDAFPRData `json:"kda"`
}

type KDAFPRData struct {
	KDA          string `json:"kda"`
	TotalAmount  int64  `json:"totalAmount"`
	TotalClaimed int64  `json:"totalClaimed"`
}

// -- CreateValidatorContract
type CreateValidatorContract struct {
	OwnerAddress string          `json:"ownerAddress"`
	Config       ValidatorConfig `json:"config"`
}

// -- ValidatorConfigContract
type ValidatorConfigContract struct {
	Config ValidatorConfig `json:"config,omitempty"`
}

// -- ValidatorConfig
type ValidatorConfig struct {
	BLSPublicKey        string `json:"blsPublicKey,omitempty"`
	RewardAddress       string `json:"rewardAddress,omitempty"`
	CanDelegate         bool   `json:"canDelegate"`
	Commission          uint32 `json:"commission"`
	MaxDelegationAmount int64  `json:"maxDelegationAmount"`
	Logo                string `json:"logo"`
	URIs                []*URI `json:"uris"`
	Name                string `json:"name"`
}

// -- FreezeContract
type FreezeContract struct {
	Amount    int64     `json:"amount,omitempty"`
	AssetID   string    `json:"assetId,omitempty"`
	AssetType AssetType `json:"assetType,omitempty"`
}

// -- UnfreezeContract
type UnfreezeContract struct {
	BucketID  string    `json:"bucketID,omitempty"`
	AssetID   string    `json:"assetId,omitempty"`
	AssetType AssetType `json:"assetType,omitempty"`
}

// -- DelegateContract
type DelegateContract struct {
	ToAddress string `json:"toAddress,omitempty"`
	BucketID  string `json:"bucketID,omitempty"`
}

// -- UndelegateContract
type UndelegateContract struct {
	BucketID string `json:"bucketID,omitempty"`
}

// --  WithdrawContract
type WithdrawContract struct {
	AssetID            string                                        `json:"assetId,omitempty"`
	WithdrawTypeString string                                        `json:"withdrawTypeString,omitempty"`
	WithdrawType       transaction.WithdrawContract_EnumWithdrawType `json:"withdrawType,omitempty"`
	Amount             int64                                         `json:"amount,omitempty"`
	CurrencyID         string                                        `json:"currencyID,omitempty"`
	AssetType          AssetType                                     `json:"assetType,omitempty"`
}

// --  DepositContract
type DepositContract struct {
	DepositTypeString string                                      `json:"depositTypeString,omitempty"`
	DepositType       transaction.DepositContract_EnumDepositType `json:"depositType,omitempty"`
	ID                string                                      `json:"id,omitempty"`
	Amount            int64                                       `json:"amount,omitempty"`
	CurrencyID        string                                      `json:"currencyID,omitempty"`
	AssetType         AssetType                                   `json:"assetType,omitempty"`
}

// -- UnjailContract
type UnjailContract struct {
}

// -- RedeemContract
type RedeemContract struct {
}

// -- ClaimContract
type ClaimContract struct {
	ClaimType string    `json:"claimType,omitempty"`
	ID        string    `json:"id,omitempty"`
	AssetType AssetType `json:"assetType,omitempty"`
}

// -- SetAccountNameContract
type SetAccountNameContract struct {
	Name string `json:"name"`
}

// -- AssetTriggerContract
type AssetTriggerContract struct {
	TriggerType string         `json:"triggerType"`
	AssetID     string         `json:"assetId"`
	ToAddress   string         `json:"toAddress,omitempty"`
	Amount      int64          `json:"amount,omitempty"`
	MIME        string         `json:"mime,omitempty"`
	Logo        string         `json:"logo,omitempty"`
	URIs        []*URI         `json:"uris,omitempty"`
	Role        *RolesInfo     `json:"role,omitempty"`
	Royalties   *RoyaltiesInfo `json:"royalties,omitempty"`
	Staking     *Staking       `json:"staking,omitempty"`
	KDAPool     *KDAPool       `json:"kdaPool,omitempty"`
	AssetType   AssetType      `json:"assetType,omitempty"`
}

// -- ProposalContract
type ProposalContract struct {
	Parameters     map[int32]string `json:"parameters"`
	Description    string           `json:"description"`
	EpochsDuration uint32           `json:"epochsDuration"`
}

// -- VoteContract
type VoteContract struct {
	Type       string `json:"type"`
	ProposalID uint64 `json:"proposalId"`
	Amount     int64  `json:"amount"`
}

// -- ConfigITOContract
type ConfigITOContract struct {
	AssetID                string           `json:"assetId,omitempty"`
	ReceiverAddress        string           `json:"receiverAddress,omitempty"`
	Status                 string           `json:"status,omitempty"`
	MaxAmount              int64            `json:"maxAmount,omitempty"`
	PackInfo               []*PackInfo      `json:"packInfo,omitempty"`
	DefaultLimitPerAddress int64            `json:"defaultLimitPerAddress,omitempty"`
	WhitelistStatus        string           `json:"whitelistStatus,omitempty"`
	WhitelistInfo          []*WhitelistInfo `json:"whitelistInfo,omitempty"`
	WhitelistStartTime     int64            `json:"whitelistStartTime,omitempty"`
	WhitelistEndTime       int64            `json:"whitelistEndTime,omitempty"`
	StartTime              int64            `json:"startTime,omitempty"`
	EndTime                int64            `json:"endTime,omitempty"`
	AssetType              AssetType        `json:"assetType,omitempty"`
}

// -- WhitelistInfo
type WhitelistInfo struct {
	Address string `json:"address"`
	Limit   int64  `json:"limit,omitempty"`
}

// -- ITOTriggerContract
type ITOTriggerContract struct {
	TriggerType            string           `json:"triggerType,omitempty"`
	AssetID                string           `json:"assetId,omitempty"`
	ReceiverAddress        string           `json:"receiverAddress,omitempty"`
	Status                 string           `json:"status,omitempty"`
	MaxAmount              int64            `json:"maxAmount,omitempty"`
	PackInfo               []*PackInfo      `json:"packInfo,omitempty"`
	DefaultLimitPerAddress int64            `json:"defaultLimitPerAddress,omitempty"`
	WhitelistStatus        string           `json:"whitelistStatus,omitempty"`
	WhitelistInfo          []*WhitelistInfo `json:"whitelistInfo,omitempty"`
	WhitelistStartTime     int64            `json:"whitelistStartTime,omitempty"`
	WhitelistEndTime       int64            `json:"whitelistEndTime,omitempty"`
	StartTime              int64            `json:"startTime,omitempty"`
	EndTime                int64            `json:"endTime,omitempty"`
	Timestamp              int64            `json:"timestamp,omitempty"`
	AssetType              AssetType        `json:"assetType,omitempty"`
}

// -- SetITOPricesContract
type SetITOPricesContract struct {
	AssetID  string      `json:"assetId,omitempty"`
	PackInfo []*PackInfo `json:"packInfo,omitempty"`
}

// PackInfo holds the pack list structure for the ITO contract
type PackInfo struct {
	Key   string      `json:"key,omitempty"`
	Packs []*PackItem `json:"packs,omitempty"`
}

// PackItem hold the pack structure for the ITO contract
type PackItem struct {
	Amount int64 `json:"amount,omitempty"`
	Price  int64 `json:"price,omitempty"`
}

// -- BuyContract
type BuyContract struct {
	BuyType    string    `json:"buyType,omitempty"`
	ID         string    `json:"id,omitempty"`
	CurrencyID string    `json:"currencyID,omitempty"`
	Amount     int64     `json:"amount,omitempty"`
	AssetType  AssetType `json:"assetType,omitempty"`
}

// -- SellContract
type SellContract struct {
	MarketType    string    `json:"marketType,omitempty"`
	MarketplaceID string    `json:"marketplaceID,omitempty"`
	AssetID       string    `json:"assetId,omitempty"`
	CurrencyID    string    `json:"currencyID,omitempty"`
	Price         int64     `json:"price,omitempty"`
	ReservePrice  int64     `json:"reservePrice,omitempty"`
	EndTime       int64     `json:"endTime,omitempty"`
	AssetType     AssetType `json:"assetType,omitempty"`
}

// -- CancelMarketOrderContract
type CancelMarketOrderContract struct {
	OrderID string `json:"orderID,omitempty"`
}

// -- CreateMarketplaceContract
type CreateMarketplaceContract struct {
	Name               string `json:"name,omitempty"`
	ReferralAddress    string `json:"referralAddress,omitempty"`
	ReferralPercentage uint32 `json:"referralPercentage,omitempty"`
}

// -- ConfigMarketplaceContract
type ConfigMarketplaceContract struct {
	MarketplaceID      string `json:"marketplaceID,omitempty"`
	Name               string `json:"name,omitempty"`
	ReferralAddress    string `json:"referralAddress,omitempty"`
	ReferralPercentage uint32 `json:"referralPercentage,omitempty"`
}

type AccKey struct {
	Address string `json:"address"`
	Weight  int64  `json:"weight"`
}

type AccPermission struct {
	Type           int32    `json:"type"`
	PermissionName string   `json:"permissionName"`
	Threshold      int64    `json:"threshold"`
	Operations     string   `json:"operations"`
	Signers        []AccKey `json:"signers"`
}

// -- UpdateAccountPermissionContract
type UpdateAccountPermissionContract struct {
	Permissions []AccPermission `json:"permissions"`
}

// SmartContract is a structure containing all the fields that need
type SmartContract struct {
	Type      string        `json:"type"`
	TypeValue int32         `json:"typeValue"`
	Address   string        `json:"address"`
	CallValue []SCCallValue `json:"callValue"`
}

// SCCallValue
type SCCallValue struct {
	Asset        string `json:"asset"`
	Value        int64  `json:"value"`
	KDARoyalties int64  `json:"kdaRoyalties"`
	KLVRoyalties int64  `json:"klvRoyalties"`
}
