// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: dkda.proto

package dkda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KDigitalToken holds the data for a Electronic standard digital token transaction
type KDigitalToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          uint32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value         int64     `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Properties    []byte    `protobuf:"bytes,3,opt,name=Properties,proto3" json:"Properties,omitempty"`
	TokenMetaData *MetaData `protobuf:"bytes,4,opt,name=TokenMetaData,json=MetaData,proto3" json:"TokenMetaData,omitempty"`
	Reserved      []byte    `protobuf:"bytes,5,opt,name=Reserved,proto3" json:"Reserved,omitempty"`
}

func (x *KDigitalToken) Reset() {
	*x = KDigitalToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KDigitalToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDigitalToken) ProtoMessage() {}

func (x *KDigitalToken) ProtoReflect() protoreflect.Message {
	mi := &file_dkda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDigitalToken.ProtoReflect.Descriptor instead.
func (*KDigitalToken) Descriptor() ([]byte, []int) {
	return file_dkda_proto_rawDescGZIP(), []int{0}
}

func (x *KDigitalToken) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *KDigitalToken) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *KDigitalToken) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *KDigitalToken) GetTokenMetaData() *MetaData {
	if x != nil {
		return x.TokenMetaData
	}
	return nil
}

func (x *KDigitalToken) GetReserved() []byte {
	if x != nil {
		return x.Reserved
	}
	return nil
}

// KDARoles holds the roles for a given token and the given address
type KDARoles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles [][]byte `protobuf:"bytes,1,rep,name=Roles,json=roles,proto3" json:"Roles,omitempty"`
}

func (x *KDARoles) Reset() {
	*x = KDARoles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KDARoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDARoles) ProtoMessage() {}

func (x *KDARoles) ProtoReflect() protoreflect.Message {
	mi := &file_dkda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDARoles.ProtoReflect.Descriptor instead.
func (*KDARoles) Descriptor() ([]byte, []int) {
	return file_dkda_proto_rawDescGZIP(), []int{1}
}

func (x *KDARoles) GetRoles() [][]byte {
	if x != nil {
		return x.Roles
	}
	return nil
}

// MetaData hold the metadata structure for the KDA token
type MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce      uint64   `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Name       []byte   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Creator    []byte   `protobuf:"bytes,3,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Royalties  uint32   `protobuf:"varint,4,opt,name=Royalties,proto3" json:"Royalties,omitempty"`
	Hash       []byte   `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash,omitempty"`
	URIs       [][]byte `protobuf:"bytes,6,rep,name=URIs,proto3" json:"URIs,omitempty"`
	Attributes []byte   `protobuf:"bytes,7,opt,name=Attributes,proto3" json:"Attributes,omitempty"`
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkda_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_dkda_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_dkda_proto_rawDescGZIP(), []int{2}
}

func (x *MetaData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MetaData) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MetaData) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MetaData) GetRoyalties() uint32 {
	if x != nil {
		return x.Royalties
	}
	return 0
}

func (x *MetaData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MetaData) GetURIs() [][]byte {
	if x != nil {
		return x.URIs
	}
	return nil
}

func (x *MetaData) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_dkda_proto protoreflect.FileDescriptor

var file_dkda_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6b, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x49, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x4b, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x40, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75,
	0x69, 0x6c, 0x74, 0x49, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x22, 0x20, 0x0a,
	0x08, 0x4b, 0x44, 0x41, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22,
	0xb4, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x52, 0x49, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x55, 0x52, 0x49, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x64, 0x6b, 0x64,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dkda_proto_rawDescOnce sync.Once
	file_dkda_proto_rawDescData = file_dkda_proto_rawDesc
)

func file_dkda_proto_rawDescGZIP() []byte {
	file_dkda_proto_rawDescOnce.Do(func() {
		file_dkda_proto_rawDescData = protoimpl.X.CompressGZIP(file_dkda_proto_rawDescData)
	})
	return file_dkda_proto_rawDescData
}

var file_dkda_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dkda_proto_goTypes = []interface{}{
	(*KDigitalToken)(nil), // 0: protoBuiltInFunctions.KDigitalToken
	(*KDARoles)(nil),      // 1: protoBuiltInFunctions.KDARoles
	(*MetaData)(nil),      // 2: protoBuiltInFunctions.MetaData
}
var file_dkda_proto_depIdxs = []int32{
	2, // 0: protoBuiltInFunctions.KDigitalToken.TokenMetaData:type_name -> protoBuiltInFunctions.MetaData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dkda_proto_init() }
func file_dkda_proto_init() {
	if File_dkda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dkda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KDigitalToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KDARoles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkda_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dkda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dkda_proto_goTypes,
		DependencyIndexes: file_dkda_proto_depIdxs,
		MessageInfos:      file_dkda_proto_msgTypes,
	}.Build()
	File_dkda_proto = out.File
	file_dkda_proto_rawDesc = nil
	file_dkda_proto_goTypes = nil
	file_dkda_proto_depIdxs = nil
}
