name: Go Setup and Lint

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.25'
      go-private:
        required: false
        type: string
        default: 'github.com/klever-io/*'
      golangci-lint-version:
        required: false
        type: string
        default: 'v1.64.8'
    secrets:
      git-user:
        required: false
      git-pass:
        required: false
    outputs:
      lint-results:
        description: "Lint results from golangci-lint"
        value: ${{ jobs.setup-and-lint.outputs.lint-results }}

jobs:
  setup-and-lint:
    runs-on: klever-pipe
    outputs:
      lint-results: ${{ steps.lint.outputs.results }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ inputs.go-version }}
          go-private: ${{ inputs.go-private }}
          git-user: ${{ secrets.git-user }}
          git-pass: ${{ secrets.git-pass }}

      - name: GoImports Formatter
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go mod tidy
          make goimports

      - name: Verify no changes from goimports
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi

      - name: Ensure code is buildable
        run: |
          go vet -unsafeptr=false $(go list ./... | grep -v /vendor/)

      - name: Install and Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ inputs.golangci-lint-version }}
          golangci-lint run > golangci-report.xml || true

      - name: Upload lint results
        uses: actions/upload-artifact@v5
        with:
          name: lint-results
          path: golangci-report.xml
          retention-days: 1
          overwrite: true