name: Main Branch Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  setup-and-lint:
    uses: ./.github/workflows/go-setup-lint.yaml
    with:
      go-version: ${{ vars.GO_VERSION || '1.25' }}
      golangci-lint-version: ${{ vars.GOLANGCI_VERSION || 'latest' }}
    secrets:
      git-user: ${{ secrets.GIT_USER }}
      git-pass: ${{ secrets.GIT_PASS }}

  validate-and-build:
    needs: [setup-and-lint]
    runs-on: klever-pipe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ vars.GO_VERSION || '1.25' }}

      - name: Build
        run: |
          make build-operator
          make build-validator
          
      - name: Save artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build
          path: |
            bin/operator
            bin/validator
            kvm/wasmer2/libvmexeccapi.so
            kvm/wasmer2/libvmexeccapi.dylib
            kvm/wasmer2/libvmexeccapi_arm.dylib
