name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  config:
    uses: ./.github/workflows/go-setup.yaml
    secrets:
      git_user: ${{ secrets.GIT_USER }}
      git_pass: ${{ secrets.GIT_PASS }}

  build:
    permissions:
      contents: write
    needs: [config]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            name: linux
            extension: .tar.gz
          - os: macos-13
            name: darwin
            extension: .tar.gz
          - os: macos-latest
            name: darwin-arm64
            extension: .tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION || '1.22' }}
          cache: false

      - name: Cache Go dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          fail-on-cache-miss: true
          path: |
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          enableCrossOsArchive: true

      - name: Build
        run: |
          make build-operator
          make build-validator

      - name: Create tarball
        run: |
          cp kvm/wasmer2/libvmexeccapi* bin/
          cd bin
          if [[ "${{ matrix.name }}" == "darwin-arm64" ]]; then
            tar -czf klevergo-operator${{ matrix.extension }} operator libvmexeccapi_arm.dylib
            tar -czf klevergo-node${{ matrix.extension }} validator libvmexeccapi_arm.dylib
          elif [[ "${{ matrix.name }}" == "darwin" ]]; then
            tar -czf klevergo-operator${{ matrix.extension }} operator libvmexeccapi.dylib
            tar -czf klevergo-node${{ matrix.extension }} validator libvmexeccapi.dylib
          elif [[ "${{ matrix.name }}" == "windows" ]]; then
            powershell Compress-Archive -Path operator, libvmexeccapi.so -DestinationPath klevergo-operator${{ matrix.extension }}
            powershell Compress-Archive -Path validator, libvmexeccapi.so -DestinationPath klevergo-node${{ matrix.extension }}
          else
            tar -czf klevergo-operator${{ matrix.extension }} operator libvmexeccapi.so
            tar -czf klevergo-node${{ matrix.extension }} validator libvmexeccapi.so
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            bin/klevergo-node${{ matrix.extension }}
            bin/klevergo-operator${{ matrix.extension }}
          generate_release_notes: true
          draft: true
          prerelease: true

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Configure GCP service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CLOUD_RUN_SA }}'

      - name: Upload files to bucket
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'bin/klevergo-operator${{ matrix.extension }}'
          destination: 'kleverchain-public/koperator/${{ matrix.name }}/${{ env.VERSION }}'

