name: Tests Dispatch

on:
  workflow_dispatch:
    inputs:
      go_version:
        description: Custom GO Version
        required: false
        type: string
        default: "1.22"
      verbose:
        description: Verbose mode
        required: false
        type: boolean
        default: false
      run_unit_tests:
        description: Run unit tests
        required: false
        type: boolean
        default: true
      run_integration_tests:
        description: Run integration tests
        required: false
        type: boolean
        default: true
      run_kvm_tests:
        description: Run kvm tests
        required: false
        type: boolean
        default: true

jobs:
  config:
    uses: ./.github/workflows/go-setup.yaml
    secrets:
      git_user: ${{ secrets.GIT_USER }}
      git_pass: ${{ secrets.GIT_PASS }}

  validate:
    needs: [config]
    runs-on: klever-pipe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Cache Go dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          fail-on-cache-miss: true
          path: |
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

      - name: GoImports Formatter
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go mod tidy
          make goimports

      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi

      - name: ensure code is buildable
        run: |
          go vet -unsafeptr=false $(go list ./... | grep -v /vendor/) 


  unit-tests:
    needs: [validate]
    if: ${{ inputs.run_unit_tests }}
    runs-on: klever-pipe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Cache Go dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          fail-on-cache-miss: true
          path: |
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

      - name: ensure all unit test is passing
        env:
          verbose: ${{ inputs.verbose }}
        run: |
          make tests-unit
  
  integration-tests:
    needs: [validate]
    if: ${{ inputs.run_integration_tests }}
    runs-on: klever-pipe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Cache Go dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          fail-on-cache-miss: true
          path: |
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

      - name: integration tests
        env:
            verbose: ${{ inputs.verbose }}
        run: |
          make tests-integration

  kvm-tests:
    needs: [validate]
    if: ${{ inputs.run_kvm_tests }}
    runs-on: klever-pipe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Cache Go dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          fail-on-cache-miss: true
          path: |
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

      - name: ensure all unit test is passing
        env:
          verbose: ${{ inputs.verbose }}
        run: |
          make tests-kvm
