name: Tests Dispatch

on:
  workflow_dispatch:
    inputs:
      go_version:
        description: Custom GO Version
        required: false
        type: string
        default: "1.22"
      verbose:
        description: Verbose mode
        required: false
        type: boolean
        default: false
      run_unit_tests:
        description: Run unit tests
        required: false
        type: boolean
        default: true
      run_integration_tests:
        description: Run integration tests
        required: false
        type: boolean
        default: true
      run_kvm_tests:
        description: Run kvm tests
        required: false
        type: boolean
        default: true

env:
  GO_VERSION: ${{ inputs.go_version }}
  GOLANGCI_VERSION: ${{ vars.GOLANGCI_VERSION || 'v1.61.0' }}

jobs:
  setup-and-lint:
    uses: ./.github/workflows/go-setup-lint.yaml
    with:
      go-version: ${{ inputs.go_version }}
      golangci-lint-version: ${{ vars.GOLANGCI_VERSION || 'v1.61.0' }}
    secrets:
      git-user: ${{ secrets.GIT_USER }}
      git-pass: ${{ secrets.GIT_PASS }}

  unit-tests:
    if: ${{ inputs.run_unit_tests }}
    needs: [setup-and-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ensure all unit test is passing
        env:
          verbose: ${{ inputs.verbose }}
        run: |
          make tests-unit
  
  integration-tests:
    if: ${{ inputs.run_integration_tests }}
    needs: [setup-and-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: integration tests
        env:
            verbose: ${{ inputs.verbose }}
        run: |
          make tests-integration

  kvm-tests:
    if: ${{ inputs.run_kvm_tests }}
    needs: [setup-and-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ensure all unit test is passing
        env:
          verbose: ${{ inputs.verbose }}
        run: |
          make tests-kvm
