package api

import (
	"github.com/klever-io/klever-go/data/block"
	"github.com/klever-io/klever-go/data/transaction"
)

const (
	// TRANSACTION_STATUS_ON_CHAIN represents the status of a transaction that is on-chain
	TRANSACTION_STATUS_ON_CHAIN = "onChain"
	// TRANSACTION_STATUS_PENDING represents the status of a transaction that is pending
	TRANSACTION_STATUS_PENDING = "pending"
)

// Block block with tarnsactions for API response
type Block struct {
	*block.Block
	Hash         string         `json:"hash"`
	Status       string         `json:"status"`
	Transactions []*Transaction `json:"transactions,omitempty"`
}

// Transaction -
type Transaction struct {
	*transaction.Transaction
	Status    string   `json:"status"`
	Hash      string   `json:"hash"`
	Signature []string `json:"signature,omitempty"`
	Logs      *Logs    `json:"logs,omitempty"`
}

// ApiLogs represents logs with changed fields' types in order to make it friendly for API's json
type Logs struct {
	Address    string    `json:"address"`
	ContractID int32     `json:"contractId"`
	Events     []*Events `json:"events"`
}

// Events represents the events generated by a transaction with changed fields' types in order to make it friendly for API's json
type Events struct {
	Address    string   `json:"address"`
	Identifier string   `json:"identifier"`
	Topics     []string `json:"topics"`
	Data       []string `json:"data"`
}

type Marketplace struct {
	ID                 string `json:"id"`
	Name               string `json:"name,omitempty"`
	OwnerAddress       string `json:"ownerAddress,omitempty"`
	ReferralAddress    string `json:"referralAddress,omitempty"`
	ReferralPercentage uint32 `json:"referralPercentage,omitempty"`
}
