package vmhooksgenerate

import "fmt"

func WriteVMHooksWrapperTest(out *eiGenWriter, eiMetadata *EIMetadata) {
	out.WriteString(getVMWrapperTestFileHeader())

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(buildVMWrapperFunctionTest(funcMetadata))
	}
}

func buildVMWrapperFunctionTest(function *EIFunction) string {
	category := getHookCategoryConstant(function.Name)
	hasReturnValue := function.Result != nil

	// Build the basic "should call hook and forward return value" test
	basicTest := buildBasicHookTest(function, hasReturnValue)

	// For slow hooks, add timeout test
	var timeoutTest string
	if category == "HookCategorySlow" {
		timeoutTest = buildTimeoutTest(function)
	}

	return fmt.Sprintf(`func Test%s(t *testing.T) {
%s%s}

`,
		upperInitial(function.Name),
		basicTest,
		timeoutTest)
}

func buildBasicHookTest(function *EIFunction, hasReturnValue bool) string {
	testName := fmt.Sprintf("%s should call hook", upperInitial(function.Name))
	if hasReturnValue {
		testName += " and forward return value"
	}

	var returnCheck string
	if hasReturnValue {
		returnType := vmHooksWrapperType(function.Result.Type)
		expectedValue := getInitializedWrapperType(function.Result.Type)
		returnCheck = fmt.Sprintf(`
		result := wrapper.%s%s
		assert.Equal(t, %s(%s), result)`,
			upperInitial(function.Name),
			getDummyFunctionCallArguments(function),
			returnType,
			expectedValue)
	} else {
		returnCheck = fmt.Sprintf(`
		wrapper.%s%s`,
			upperInitial(function.Name),
			getDummyFunctionCallArguments(function))
	}

	return fmt.Sprintf(`	t.Run("%s", func(t *testing.T) {
		called := false
		wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
			%sCalled: func%s {
				called = true
				%s
			},
		}, &NoLogger{})%s
		assert.True(t, called)
	})
`,
		testName,
		upperInitial(function.Name),
		getFunctionSignature(function),
		getDummyFunctionReturn(function),
		returnCheck)
}

func buildTimeoutTest(function *EIFunction) string {
	testName := fmt.Sprintf("%s should timeout when context expires", upperInitial(function.Name))

	return fmt.Sprintf(`
	t.Run("%s", func(t *testing.T) {
		// Create a context that's already expired
		ctx, cancel := context.WithTimeout(context.Background(), 1*time.Nanosecond)
		time.Sleep(2 * time.Millisecond) // Ensure timeout
		defer cancel()

		// Create a simple mock host that returns the expired context
		mockHost := &simpleVMHost{ctx: ctx}

		wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
			GetVMHostCalled: func() vmhost.VMHost {
				return mockHost
			},
			%sCalled: func%s {
				time.Sleep(10 * time.Millisecond) // Simulate slow operation
				%s
			},
		}, &NoLogger{})

		panicked := false
		func() {
			defer func() {
				if r := recover(); r != nil {
					panicked = true
				}
			}()
			wrapper.%s%s
		}()

		assert.True(t, panicked, "Expected timeout panic for slow hook")
	})
`,
		testName,
		upperInitial(function.Name),
		getFunctionSignature(function),
		getDummyFunctionReturn(function),
		upperInitial(function.Name),
		getDummyFunctionCallArguments(function))
}

func getVMWrapperTestFileHeader() string {
	return `package executorwrapper

// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"github.com/klever-io/klever-go/kvm/executor"
	"github.com/klever-io/klever-go/kvm/mock/stub"
	"github.com/klever-io/klever-go/kvm/vmhost"
)

// simpleVMHost is a minimal mock for testing timeout behavior
type simpleVMHost struct {
	vmhost.VMHost
	ctx context.Context
}

func (h *simpleVMHost) GetExecutionContext() context.Context {
	return h.ctx
}

func (h *simpleVMHost) IsInterfaceNil() bool {
	return h == nil
}

`
}

func getFunctionSignature(function *EIFunction) string {
	signature := "("
	for argIndex, arg := range function.Arguments {
		if argIndex > 0 {
			signature += ", "
		}
		signature += fmt.Sprintf("%s %s", arg.Name, vmHooksWrapperType(arg.Type))
	}
	signature += ")"
	if function.Result != nil {
		signature += fmt.Sprintf(" %s", vmHooksWrapperType(function.Result.Type))
	}
	return signature
}

func getDummyFunctionReturn(function *EIFunction) string {
	if function.Result != nil {
		return fmt.Sprintf("return %s", getInitializedWrapperType(function.Result.Type))
	}
	return "return"
}

func getDummyFunctionCallArguments(function *EIFunction) string {
	signature := "("
	for argIndex, arg := range function.Arguments {
		if argIndex > 0 {
			signature += ", "
		}
		signature += getInitializedWrapperType(arg.Type)
	}
	signature += ")"
	return signature
}

func getInitializedWrapperType(eiType EIType) string {
	switch eiType {
	case EITypeInt32:
		return "0"
	case EITypeInt64:
		return "0"
	case EITypeMemPtr:
		return "0"
	case EITypeMemLength:
		return "0"
	default:
		panic("unhandled default case")
	}
}
