package vmhooksgenerate

import (
	"testing"
)

func TestBuildCommaSeparatedArgumentNames(t *testing.T) {
	tests := []struct {
		name      string
		arguments []*EIFunctionArg
		expected  string
	}{
		{
			name:      "no arguments",
			arguments: []*EIFunctionArg{},
			expected:  "",
		},
		{
			name: "single argument",
			arguments: []*EIFunctionArg{
				{Name: "arg1"},
			},
			expected: "arg1",
		},
		{
			name: "two arguments",
			arguments: []*EIFunctionArg{
				{Name: "arg1"},
				{Name: "arg2"},
			},
			expected: "arg1, arg2",
		},
		{
			name: "multiple arguments",
			arguments: []*EIFunctionArg{
				{Name: "arg1"},
				{Name: "arg2"},
				{Name: "arg3"},
			},
			expected: "arg1, arg2, arg3",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := buildCommaSeparatedArgumentNames(tt.arguments)
			if result != tt.expected {
				t.Errorf("Test %s failed: got %q, expected %q", tt.name, result, tt.expected)
			}
		})
	}
}

func TestBuildCallInfo(t *testing.T) {
	tests := []struct {
		name     string
		funcMeta *EIFunction
		expected string
	}{
		{
			name: "function with no arguments",
			funcMeta: &EIFunction{
				Name:      "myFunc",
				Arguments: []*EIFunctionArg{},
			},
			expected: "\n\tcallInfo := \"MyFunc()\"",
		},
		{
			name: "function with one argument",
			funcMeta: &EIFunction{
				Name: "myFunc",
				Arguments: []*EIFunctionArg{
					{Name: "arg1"},
				},
			},
			expected: "\n\tcallInfo := fmt.Sprintf(\"MyFunc(%d)\", arg1)",
		},
		{
			name: "function with two arguments",
			funcMeta: &EIFunction{
				Name: "myFunc",
				Arguments: []*EIFunctionArg{
					{Name: "arg1"},
					{Name: "arg2"},
				},
			},
			expected: "\n\tcallInfo := fmt.Sprintf(\"MyFunc(%d, %d)\", arg1, arg2)",
		},
		{
			name: "function with uppercase function name",
			funcMeta: &EIFunction{
				Name: "MyFunc",
				Arguments: []*EIFunctionArg{
					{Name: "arg1"},
					{Name: "arg2"},
				},
			},
			expected: "\n\tcallInfo := fmt.Sprintf(\"MyFunc(%d, %d)\", arg1, arg2)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := buildCallInfo(tt.funcMeta)
			if result != tt.expected {
				t.Errorf("Test %s failed: got %q, expected %q", tt.name, result, tt.expected)
			}
		})
	}
}

func TestBuildVMWrapperFileHeader(t *testing.T) {
	expected := `package executorwrapper

// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import (
	"fmt"

	"github.com/klever-io/klever-go/kvm/executor"
)

// WrapperVMHooks wraps a VMHooks instance and optionally performs some logging.
type WrapperVMHooks struct {
	logger         ExecutorLogger
	wrappedVMHooks executor.VMHooks
}

// NewWrapperVMHooks creates a new instance of WrapperVMHooks.
func NewWrapperVMHooks(wrappedVMHooks executor.VMHooks, logger ExecutorLogger) *WrapperVMHooks {
	return &WrapperVMHooks{
		wrappedVMHooks: wrappedVMHooks,
		logger:         logger,
	}
}
`

	result := buildVMWrapperFileHeader()
	if result != expected {
		t.Errorf("buildVMWrapperFileHeader() returned incorrect output:\nGot:\n%s\n\nExpected:\n%s", result, expected)
	}
}

func TestBuildVMWrapperFunction(t *testing.T) {
	tests := []struct {
		name     string
		funcMeta *EIFunction
		expected string
	}{
		{
			name: "no arguments and no return",
			funcMeta: &EIFunction{
				Name:      "simpleFunc",
				Arguments: []*EIFunctionArg{},
				Result:    nil,
			},
			expected: `
// SimpleFunc VM hook wrapper
func (w *WrapperVMHooks) SimpleFunc() {
	callInfo := "SimpleFunc()"
	w.logger.LogVMHookCallBefore(callInfo)
	_ = FailAfterTimeout(func() any {
		w.wrappedVMHooks.SimpleFunc()
		return nil
	}, HookCategoryFast)
	w.logger.LogVMHookCallAfter(callInfo)
}
`,
		},
		{
			name: "one argument, no return",
			funcMeta: &EIFunction{
				Name: "oneArgFunc",
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
				},
				Result: nil,
			},
			expected: `
// OneArgFunc VM hook wrapper
func (w *WrapperVMHooks) OneArgFunc(arg1 int32) {
	callInfo := fmt.Sprintf("OneArgFunc(%d)", arg1)
	w.logger.LogVMHookCallBefore(callInfo)
	_ = FailAfterTimeout(func() any {
		w.wrappedVMHooks.OneArgFunc(arg1)
		return nil
	}, HookCategoryFast)
	w.logger.LogVMHookCallAfter(callInfo)
}
`,
		},
		{
			name: "multiple arguments, no return",
			funcMeta: &EIFunction{
				Name: "multiArgFunc",
				Arguments: []*EIFunctionArg{
					{Name: "arg1", Type: EITypeInt32},
					{Name: "arg2", Type: EITypeInt64},
				},
				Result: nil,
			},
			expected: `
// MultiArgFunc VM hook wrapper
func (w *WrapperVMHooks) MultiArgFunc(arg1 int32, arg2 int64) {
	callInfo := fmt.Sprintf("MultiArgFunc(%d, %d)", arg1, arg2)
	w.logger.LogVMHookCallBefore(callInfo)
	_ = FailAfterTimeout(func() any {
		w.wrappedVMHooks.MultiArgFunc(arg1, arg2)
		return nil
	}, HookCategoryFast)
	w.logger.LogVMHookCallAfter(callInfo)
}
`,
		},
		{
			name: "one argument, with return",
			funcMeta: &EIFunction{
				Name: "funcWithReturn",
				Arguments: []*EIFunctionArg{
					{Name: "arg1", Type: EITypeInt32},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: `
// FuncWithReturn VM hook wrapper
func (w *WrapperVMHooks) FuncWithReturn(arg1 int32) int32 {
	callInfo := fmt.Sprintf("FuncWithReturn(%d)", arg1)
	w.logger.LogVMHookCallBefore(callInfo)
	result := FailAfterTimeout(func() int32 {
		return w.wrappedVMHooks.FuncWithReturn(arg1)
	}, HookCategoryFast)
	w.logger.LogVMHookCallAfter(callInfo)
	return result
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := buildVMWrapperFunction(tt.funcMeta)
			if result != tt.expected {
				t.Errorf("Test %s failed: got:\n%s\n\nexpected:\n%s", tt.name, result, tt.expected)
			}
		})
	}
}
