package vmhooksgenerate

import (
	"fmt"
)

func WriteVMHooksWrapper(out *eiGenWriter, eiMetadata *EIMetadata) {
	out.WriteString(buildVMWrapperFileHeader())

	for _, funcMetadata := range eiMetadata.AllFunctions {
		out.WriteString(buildVMWrapperFunction(funcMetadata))
	}
}

func buildVMWrapperFunction(funcMetadata *EIFunction) string {
	function := ""
	function += fmt.Sprintf("\n// %s VM hook wrapper", upperInitial(funcMetadata.Name))
	function += fmt.Sprintf("\nfunc (w *WrapperVMHooks) %s(", upperInitial(funcMetadata.Name))
	for argIndex, arg := range funcMetadata.Arguments {
		if argIndex > 0 {
			function += ", "
		}
		function += fmt.Sprintf("%s %s", arg.Name, vmHooksWrapperType(arg.Type))
	}
	function += ")"
	if funcMetadata.Result != nil {
		function += fmt.Sprintf(" %s", vmHooksWrapperType(funcMetadata.Result.Type))
	}
	function += " {"
	function += buildCallInfo(funcMetadata)
	function += "\n\tw.logger.LogVMHookCallBefore(callInfo)"
	function += "\n\t"
	functionReturnType := "any"
	if funcMetadata.Result != nil {
		functionReturnType = vmHooksWrapperType(funcMetadata.Result.Type)
		function += "result := "
	} else {
		function += "_ = "
	}
	function += fmt.Sprintf("FailAfterTimeout(func() %s {\n\t\t", functionReturnType)
	if funcMetadata.Result != nil {
		function += "return "
	}
	function += fmt.Sprintf("w.wrappedVMHooks.%s(", upperInitial(funcMetadata.Name))
	function += buildCommaSeparatedArgumentNames(funcMetadata.Arguments)
	function += ")"
	if funcMetadata.Result == nil {
		function += "\n\t\treturn nil"
	}
	// Determine category at generation time
	category := getHookCategoryConstant(funcMetadata.Name)
	function += fmt.Sprintf("\n\t}, %s, w)", category)
	function += "\n\tw.logger.LogVMHookCallAfter(callInfo)"
	if funcMetadata.Result != nil {
		function += "\n\treturn result"
	}
	function += "\n}\n"
	return function
}

func buildVMWrapperFileHeader() string {
	return `package executorwrapper

// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import (
	"context"
	"fmt"

	"github.com/klever-io/klever-go/kvm/executor"
	"github.com/klever-io/klever-go/kvm/vmhost"
)

// WrapperVMHooks wraps a VMHooks instance and optionally performs some logging.
type WrapperVMHooks struct {
	logger         ExecutorLogger
	wrappedVMHooks executor.VMHooks
	vmHost         vmhost.VMHost // Cached to avoid repeated type assertions
}

// NewWrapperVMHooks creates a new instance of WrapperVMHooks.
func NewWrapperVMHooks(wrappedVMHooks executor.VMHooks, logger ExecutorLogger) *WrapperVMHooks {
	wrapper := &WrapperVMHooks{
		wrappedVMHooks: wrappedVMHooks,
		logger:         logger,
	}

	// Cache the VMHost reference to optimize FailAfterTimeout performance
	// This eliminates repeated type assertions on every hook call
	type vmHostGetter interface {
		GetVMHost() vmhost.VMHost
	}
	if hostGetter, ok := wrappedVMHooks.(vmHostGetter); ok {
		wrapper.vmHost = hostGetter.GetVMHost()
	}

	return wrapper
}

// getExecutionContext retrieves the current execution context from the cached VMHost.
// Returns nil if no VMHost or no context is available.
func (w *WrapperVMHooks) getExecutionContext() context.Context {
	if w == nil || w.vmHost == nil {
		return nil
	}
	return w.vmHost.GetExecutionContext()
}
`
}

func buildCallInfo(funcMetadata *EIFunction) string {
	if len(funcMetadata.Arguments) == 0 {
		return fmt.Sprintf("\n\tcallInfo := \"%s()\"", upperInitial(funcMetadata.Name))
	}
	callInfo := ""
	callInfo += fmt.Sprintf("\n\tcallInfo := fmt.Sprintf(\"%s(", upperInitial(funcMetadata.Name))
	for argIndex := range funcMetadata.Arguments {
		if argIndex > 0 {
			callInfo += ", "
		}
		callInfo += "%d"
	}
	callInfo += ")\", "
	callInfo += buildCommaSeparatedArgumentNames(funcMetadata.Arguments)
	callInfo += ")"
	return callInfo
}

func buildCommaSeparatedArgumentNames(arguments []*EIFunctionArg) string {
	argumentNames := ""
	for argIndex, arg := range arguments {
		if argIndex > 0 {
			argumentNames += ", "
		}
		argumentNames += fmt.Sprintf("%s", arg.Name)
	}
	return argumentNames
}

// getHookCategoryConstant returns the category constant for a hook at generation time.
// This eliminates runtime string lookups - the category is baked into the generated code.
func getHookCategoryConstant(hookName string) string {
	// Only these hooks need expensive goroutine protection
	slowHooks := map[string]bool{
		// Contract execution - can run arbitrary WASM
		"ExecuteOnSameContext":              true,
		"ExecuteOnDestContext":              true,
		"ExecuteReadOnly":                   true,
		"CreateContract":                    true,
		"UpgradeContract":                   true,
		"DeployFromSourceContract":          true,
		"UpgradeFromSourceContract":         true,
		"DeleteContract":                    true,
		"ManagedExecuteOnSameContext":       true,
		"ManagedExecuteOnDestContext":       true,
		"ManagedExecuteReadOnly":            true,
		"ManagedCreateContract":             true,
		"ManagedUpgradeContract":            true,
		"ManagedDeployFromSourceContract":   true,
		"ManagedUpgradeFromSourceContract":  true,
		"ManagedDeleteContract":             true,
		"ManagedMultiTransferKDANFTExecute": true,

		// Exponential math - can have many iterations
		"BigIntPow":   true,
		"BigFloatPow": true,
	}

	if slowHooks[hookName] {
		return "HookCategorySlow"
	}
	return "HookCategoryFast"
}
