package vmhooksgenerate

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGetFunctionSignature(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No arguments, no return",
			function: &EIFunction{},
			expected: "()",
		},
		{
			name: "No arguments, return",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "() int32",
		},
		{
			name: "4 arguments, no return",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeInt64,
					},
					{
						Name: "arg3",
						Type: EITypeMemPtr,
					},
					{
						Name: "arg4",
						Type: EITypeMemLength,
					},
				},
			},
			expected: "(arg1 int32, arg2 int64, arg3 executor.MemPtr, arg4 executor.MemLength)",
		},
		{
			name: "4 arguments, return",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeInt64,
					},
					{
						Name: "arg3",
						Type: EITypeMemPtr,
					},
					{
						Name: "arg4",
						Type: EITypeMemLength,
					},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "(arg1 int32, arg2 int64, arg3 executor.MemPtr, arg4 executor.MemLength) int32",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getFunctionSignature(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetDummyFunctionReturn(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No return",
			function: &EIFunction{},
			expected: "return",
		},
		{
			name: "Return int32",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return int64",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt64,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return MemPtr",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeMemPtr,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return MemLength",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeMemLength,
				},
			},
			expected: "return 0",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getDummyFunctionReturn(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetDummyFunctionCallArguments(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No arguments",
			function: &EIFunction{},
			expected: "()",
		},
		{
			name: "1 argument",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
				},
			},
			expected: "(0)",
		},
		{
			name: "2 arguments",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeMemPtr,
					},
				},
			},
			expected: "(0, 0)",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getDummyFunctionCallArguments(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetInitializeWrapperType(t *testing.T) {
	var testCases = []struct {
		name     string
		eiType   EIType
		expected string
	}{
		{
			name:     "EITypeInt32",
			eiType:   EITypeInt32,
			expected: "0",
		},
		{
			name:     "EITypeInt64",
			eiType:   EITypeInt64,
			expected: "0",
		},
		{
			name:     "EITypeMemPtr",
			eiType:   EITypeMemPtr,
			expected: "0",
		},
		{
			name:     "EITypeMemLength",
			eiType:   EITypeMemLength,
			expected: "0",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getInitializedWrapperType(tc.eiType)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetVMWrapperTestFileHeader(t *testing.T) {
	expected := `package executorwrapper

// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"github.com/klever-io/klever-go/kvm/executor"
	"github.com/klever-io/klever-go/kvm/mock/stub"
	"github.com/klever-io/klever-go/kvm/vmhost"
)

// simpleVMHost is a minimal mock for testing timeout behavior
type simpleVMHost struct {
	vmhost.VMHost
	ctx context.Context
}

func (h *simpleVMHost) GetExecutionContext() context.Context {
	return h.ctx
}

func (h *simpleVMHost) IsInterfaceNil() bool {
	return h == nil
}

`
	actual := getVMWrapperTestFileHeader()
	if actual != expected {
		t.Errorf("Expected %s, got %s", expected, actual)
	}
}

func TestBuildVMWrapperFunctionTest(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name: "No arguments, no return",
			function: &EIFunction{
				Name: "NoArgsNoReturn",
			},
			expected: `func TestNoArgsNoReturn(t *testing.T) {
	t.Run("NoArgsNoReturn should call hook", func(t *testing.T) {
		called := false
		wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
			NoArgsNoReturnCalled: func() {
				called = true
				return
			},
		}, &NoLogger{})
		wrapper.NoArgsNoReturn()
		assert.True(t, called)
	})
}

`,
		},
		{
			name: "2 arguments, return",
			function: &EIFunction{
				Name: "TwoArgsWithReturn",
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeMemPtr,
					},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: `func TestTwoArgsWithReturn(t *testing.T) {
	t.Run("TwoArgsWithReturn should call hook and forward return value", func(t *testing.T) {
		called := false
		wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
			TwoArgsWithReturnCalled: func(arg1 int32, arg2 executor.MemPtr) int32 {
				called = true
				return 0
			},
		}, &NoLogger{})
		result := wrapper.TwoArgsWithReturn(0, 0)
		assert.Equal(t, int32(0), result)
		assert.True(t, called)
	})
}

`,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := buildVMWrapperFunctionTest(tc.function)
			assert.Equal(t, tc.expected, actual)
		})
	}
}

func TestBuildBasicHookTest(t *testing.T) {
	testCases := []struct {
		name           string
		function       *EIFunction
		hasReturnValue bool
		expectedSubstr []string
	}{
		{
			name: "Function with no return value",
			function: &EIFunction{
				Name: "SimpleHook",
			},
			hasReturnValue: false,
			expectedSubstr: []string{
				"SimpleHook should call hook",
				"called := false",
				"SimpleHookCalled: func()",
				"wrapper.SimpleHook()",
				"assert.True(t, called)",
			},
		},
		{
			name: "Function with int32 return value",
			function: &EIFunction{
				Name: "HookWithReturn",
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			hasReturnValue: true,
			expectedSubstr: []string{
				"HookWithReturn should call hook and forward return value",
				"result := wrapper.HookWithReturn()",
				"assert.Equal(t, int32(0), result)",
			},
		},
		{
			name: "Function with arguments and return",
			function: &EIFunction{
				Name: "ComplexHook",
				Arguments: []*EIFunctionArg{
					{Name: "arg1", Type: EITypeInt32},
					{Name: "arg2", Type: EITypeInt64},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt64,
				},
			},
			hasReturnValue: true,
			expectedSubstr: []string{
				"ComplexHook should call hook and forward return value",
				"ComplexHookCalled: func(arg1 int32, arg2 int64) int64",
				"result := wrapper.ComplexHook(0, 0)",
				"assert.Equal(t, int64(0), result)",
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := buildBasicHookTest(tc.function, tc.hasReturnValue)

			for _, substr := range tc.expectedSubstr {
				assert.Contains(t, result, substr, "Expected substring not found: %s", substr)
			}
		})
	}
}

func TestBuildTimeoutTest(t *testing.T) {
	testCases := []struct {
		name           string
		function       *EIFunction
		expectedSubstr []string
	}{
		{
			name: "Slow hook timeout test - no args, no return",
			function: &EIFunction{
				Name: "ExecuteOnDestContext",
			},
			expectedSubstr: []string{
				"ExecuteOnDestContext should timeout when context expires",
				"ctx, cancel := context.WithTimeout(context.Background(), 1*time.Nanosecond)",
				"time.Sleep(2 * time.Millisecond)",
				"mockHost := &simpleVMHost{ctx: ctx}",
				"ExecuteOnDestContextCalled: func()",
				"time.Sleep(10 * time.Millisecond)",
				"panicked := false",
				"assert.True(t, panicked",
			},
		},
		{
			name: "Slow hook timeout test - with args",
			function: &EIFunction{
				Name: "CreateContract",
				Arguments: []*EIFunctionArg{
					{Name: "gasLimit", Type: EITypeInt64},
					{Name: "valueOffset", Type: EITypeMemPtr},
				},
			},
			expectedSubstr: []string{
				"CreateContract should timeout when context expires",
				"CreateContractCalled: func(gasLimit int64, valueOffset executor.MemPtr)",
				"wrapper.CreateContract(0, 0)",
			},
		},
		{
			name: "Slow hook timeout test - with return value",
			function: &EIFunction{
				Name: "BigIntPow",
				Arguments: []*EIFunctionArg{
					{Name: "destHandle", Type: EITypeInt32},
					{Name: "baseHandle", Type: EITypeInt32},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expectedSubstr: []string{
				"BigIntPow should timeout when context expires",
				"BigIntPowCalled: func(destHandle int32, baseHandle int32) int32",
				"wrapper.BigIntPow(0, 0)",
				"return 0",
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := buildTimeoutTest(tc.function)

			for _, substr := range tc.expectedSubstr {
				assert.Contains(t, result, substr, "Expected substring not found: %s", substr)
			}
		})
	}
}

func TestBuildVMWrapperFunctionTest_SlowHooks(t *testing.T) {
	testCases := []struct {
		name              string
		function          *EIFunction
		shouldHaveTimeout bool
	}{
		{
			name: "ExecuteOnDestContext (slow hook)",
			function: &EIFunction{
				Name: "ExecuteOnDestContext",
			},
			shouldHaveTimeout: true,
		},
		{
			name: "CreateContract (slow hook)",
			function: &EIFunction{
				Name: "CreateContract",
			},
			shouldHaveTimeout: true,
		},
		{
			name: "UpgradeContract (slow hook)",
			function: &EIFunction{
				Name: "UpgradeContract",
			},
			shouldHaveTimeout: true,
		},
		{
			name: "GetGasLeft (fast hook)",
			function: &EIFunction{
				Name: "GetGasLeft",
			},
			shouldHaveTimeout: false,
		},
		{
			name: "GetBlockTimestamp (fast hook)",
			function: &EIFunction{
				Name: "GetBlockTimestamp",
			},
			shouldHaveTimeout: false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := buildVMWrapperFunctionTest(tc.function)

			if tc.shouldHaveTimeout {
				assert.Contains(t, result, "should timeout when context expires",
					"Slow hook should have timeout test")
				assert.Contains(t, result, "simpleVMHost",
					"Timeout test should use simpleVMHost")
			} else {
				assert.NotContains(t, result, "should timeout when context expires",
					"Fast hook should not have timeout test")
			}
		})
	}
}

func TestWriteVMHooksWrapperTest(t *testing.T) {
	t.Run("Generates test file with header and multiple function tests", func(t *testing.T) {
		metadata := &EIMetadata{
			AllFunctions: []*EIFunction{
				{Name: "GetGasLeft"},
				{Name: "ExecuteOnDestContext"},
			},
		}

		// Create temp file for testing
		tmpDir := t.TempDir()
		filename := "test_wrapper.go"
		writer := NewEIGenWriter(tmpDir, filename)
		defer writer.Close()

		WriteVMHooksWrapperTest(writer, metadata)
		writer.Close()

		// Read the generated file
		tmpFile := filepath.Join(tmpDir, filename)
		content, err := os.ReadFile(tmpFile)
		assert.NoError(t, err)
		output := string(content)

		// Check header is present
		assert.Contains(t, output, "package executorwrapper")
		assert.Contains(t, output, "Code generated by vmhooks generator. DO NOT EDIT.")
		assert.Contains(t, output, "simpleVMHost")

		// Check both function tests are present
		assert.Contains(t, output, "func TestGetGasLeft(t *testing.T)")
		assert.Contains(t, output, "func TestExecuteOnDestContext(t *testing.T)")

		// Fast hook should not have timeout test
		assert.NotContains(t, output, "GetGasLeft should timeout")

		// Slow hook should have timeout test
		assert.Contains(t, output, "ExecuteOnDestContext should timeout")
	})
}

func TestGetInitializedWrapperType_AllTypes(t *testing.T) {
	testCases := []struct {
		name     string
		eiType   EIType
		expected string
	}{
		{"Int32", EITypeInt32, "0"},
		{"Int64", EITypeInt64, "0"},
		{"MemPtr", EITypeMemPtr, "0"},
		{"MemLength", EITypeMemLength, "0"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := getInitializedWrapperType(tc.eiType)
			assert.Equal(t, tc.expected, result)
		})
	}
}

func TestGetInitializedWrapperType_Panic(t *testing.T) {
	t.Run("Panics on invalid type", func(t *testing.T) {
		defer func() {
			r := recover()
			assert.NotNil(t, r, "Expected panic for invalid type")
			assert.Contains(t, r, "unhandled default case")
		}()

		// Use an invalid EIType value
		getInitializedWrapperType(EIType(999))
	})
}
