package vmhooksgenerate

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGetFunctionSignature(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No arguments, no return",
			function: &EIFunction{},
			expected: "()",
		},
		{
			name: "No arguments, return",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "() int32",
		},
		{
			name: "4 arguments, no return",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeInt64,
					},
					{
						Name: "arg3",
						Type: EITypeMemPtr,
					},
					{
						Name: "arg4",
						Type: EITypeMemLength,
					},
				},
			},
			expected: "(arg1 int32, arg2 int64, arg3 executor.MemPtr, arg4 executor.MemLength)",
		},
		{
			name: "4 arguments, return",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeInt64,
					},
					{
						Name: "arg3",
						Type: EITypeMemPtr,
					},
					{
						Name: "arg4",
						Type: EITypeMemLength,
					},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "(arg1 int32, arg2 int64, arg3 executor.MemPtr, arg4 executor.MemLength) int32",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getFunctionSignature(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetDummyFunctionReturn(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No return",
			function: &EIFunction{},
			expected: "return",
		},
		{
			name: "Return int32",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return int64",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeInt64,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return MemPtr",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeMemPtr,
				},
			},
			expected: "return 0",
		},
		{
			name: "Return MemLength",
			function: &EIFunction{
				Result: &EIFunctionResult{
					Type: EITypeMemLength,
				},
			},
			expected: "return 0",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getDummyFunctionReturn(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetDummyFunctionCallArguments(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name:     "No arguments",
			function: &EIFunction{},
			expected: "()",
		},
		{
			name: "1 argument",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
				},
			},
			expected: "(0)",
		},
		{
			name: "2 arguments",
			function: &EIFunction{
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeMemPtr,
					},
				},
			},
			expected: "(0, 0)",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getDummyFunctionCallArguments(tc.function)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetInitializeWrapperType(t *testing.T) {
	var testCases = []struct {
		name     string
		eiType   EIType
		expected string
	}{
		{
			name:     "EITypeInt32",
			eiType:   EITypeInt32,
			expected: "0",
		},
		{
			name:     "EITypeInt64",
			eiType:   EITypeInt64,
			expected: "0",
		},
		{
			name:     "EITypeMemPtr",
			eiType:   EITypeMemPtr,
			expected: "0",
		},
		{
			name:     "EITypeMemLength",
			eiType:   EITypeMemLength,
			expected: "0",
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := getInitializedWrapperType(tc.eiType)
			if actual != tc.expected {
				t.Errorf("Expected %s, got %s", tc.expected, actual)
			}
		})
	}
}

func TestGetVMWrapperTestFileHeader(t *testing.T) {
	expected := `package executorwrapper

// Code generated by vmhooks generator. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import (
	"github.com/klever-io/klever-go/kvm/executor"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"github.com/klever-io/klever-go/kvm/mock/stub"
)

`
	actual := getVMWrapperTestFileHeader()
	if actual != expected {
		t.Errorf("Expected %s, got %s", expected, actual)
	}
}

func TestBuildVMWrapperFunctionTest(t *testing.T) {
	var testCases = []struct {
		name     string
		function *EIFunction
		expected string
	}{
		{
			name: "No arguments, no return",
			function: &EIFunction{
				Name: "NoArgsNoReturn",
			},
			expected: `func TestNoArgsNoReturn(t *testing.T) {
	var testCases = []struct {
		name        string
		shouldPanic bool
		shouldCall  bool
		delay       time.Duration
		timeout     time.Duration
	}{
		{
			name:        "NoArgsNoReturn should call hook",
			shouldPanic: false,
			shouldCall:  true,
			delay:       0,
			timeout:     time.Second * 1,
		},
		{
			name:        "NoArgsNoReturn should timeout",
			shouldPanic: true,
			shouldCall:  true,
			delay:       time.Millisecond * 10,
			timeout:     0,
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			called := false
			panicked := false
			defer func() {
				r := recover()
				panicked = r != nil
			}()
			wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
				NoArgsNoReturnCalled: func () {
					called = true
					time.Sleep(tc.delay)
					return
				},
			}, &NoLogger{}, tc.timeout)
			wrapper.NoArgsNoReturn()
			assert.Equal(t, tc.shouldCall, called)
			assert.Equal(t, tc.shouldPanic, panicked)
		})
	}
}

`,
		},
		{
			name: "2 arguments, return",
			function: &EIFunction{
				Name: "TwoArgsWithReturn",
				Arguments: []*EIFunctionArg{
					{
						Name: "arg1",
						Type: EITypeInt32,
					},
					{
						Name: "arg2",
						Type: EITypeMemPtr,
					},
				},
				Result: &EIFunctionResult{
					Type: EITypeInt32,
				},
			},
			expected: `func TestTwoArgsWithReturn(t *testing.T) {
	var testCases = []struct {
		name        string
		shouldPanic bool
		shouldCall  bool
		delay       time.Duration
		timeout     time.Duration
	}{
		{
			name:        "TwoArgsWithReturn should call hook",
			shouldPanic: false,
			shouldCall:  true,
			delay:       0,
			timeout:     time.Second * 1,
		},
		{
			name:        "TwoArgsWithReturn should timeout",
			shouldPanic: true,
			shouldCall:  true,
			delay:       time.Millisecond * 10,
			timeout:     0,
		},
	}
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			called := false
			panicked := false
			defer func() {
				r := recover()
				panicked = r != nil
			}()
			wrapper := NewWrapperVMHooks(&stub.VMHooksStub{
				TwoArgsWithReturnCalled: func (arg1 int32, arg2 executor.MemPtr) int32 {
					called = true
					time.Sleep(tc.delay)
					return 0
				},
			}, &NoLogger{}, tc.timeout)
			wrapper.TwoArgsWithReturn(0, 0)
			assert.Equal(t, tc.shouldCall, called)
			assert.Equal(t, tc.shouldPanic, panicked)
		})
	}
}

`,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := buildVMWrapperFunctionTest(tc.function)
			assert.Equal(t, tc.expected, actual)
		})
	}
}
